/*
 * Java bean class for entity "iscritto_t_isee"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_isee"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTIsee implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  valore_isee, " +
		"  dt_sottoscrizione, " +
		"  id_domanda_iscrizione " +
		"from iscritto_t_isee ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_isee (" +
		"  valore_isee, " +
		"  dt_sottoscrizione, " +
		"  id_domanda_iscrizione " +
		") " +
		"values (" +
		"  :valoreIsee, " +
		"  :dtSottoscrizione, " +
		"  :idDomandaIscrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_isee where " +
		"  id_domanda_iscrizione = :idDomandaIscrizione ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_isee";

	//////////////////////////////////////////////////////////////////////


    private Long       idDomandaIscrizione ; // Id or Primary Key

    private Double     valoreIsee   ;
    private Date       dtSottoscrizione ;

    /**
     * Set the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @param idDomandaIscrizione
     */
	public void setIdDomandaIscrizione(Long idDomandaIscrizione) {
        this.idDomandaIscrizione = idDomandaIscrizione ;
    }

    /**
     * Get the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdDomandaIscrizione() {
        return this.idDomandaIscrizione;
    }

    /**
     * Set the "valoreIsee" field value
     * This field is mapped on the database column "valore_isee" ( type "numeric", NotNull : true )
     * @param valoreIsee
     */
    public void setValoreIsee(Double valoreIsee) {
        this.valoreIsee = valoreIsee;
    }

    /**
     * Get the "valoreIsee" field value
     * This field is mapped on the database column "valore_isee" ( type "numeric", NotNull : true )
     * @return the field value
     */
    public Double getValoreIsee() {
        return this.valoreIsee;
    }

    /**
     * Set the "dtSottoscrizione" field value
     * This field is mapped on the database column "dt_sottoscrizione" ( type "timestamp", NotNull : true )
     * @param dtSottoscrizione
     */
    public void setDtSottoscrizione(Date dtSottoscrizione) {
        this.dtSottoscrizione = dtSottoscrizione;
    }

    /**
     * Get the "dtSottoscrizione" field value
     * This field is mapped on the database column "dt_sottoscrizione" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtSottoscrizione() {
        return this.dtSottoscrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(valoreIsee);
        sb.append("|");
        sb.append(dtSottoscrizione);
        sb.append("|");
        sb.append(idDomandaIscrizione);
        return sb.toString(); 
    } 

}
