/*
 * Java bean class for entity "iscritto_t_utente"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:24 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_utente"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTUtente implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_utente, " +
		"  codice_fiscale, " +
		"  cognome, " +
		"  nome, " +
//		"  id_profilo, " +
		"  fl_eliminato " +
		"from iscritto_t_utente ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_utente (" +
		"  id_utente, " +
		"  codice_fiscale, " +
		"  cognome, " +
		"  nome, " +
//		"  id_profilo, " +
		"  fl_eliminato " +
		") " +
		"values (" +
		"  :idUtente, " +
		"  :codiceFiscale, " +
		"  :cognome, " +
		"  :nome, " +
//		"  :idProfilo, " +
		"  :flEliminato " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_utente where " +
		"  id_utente = :idUtente ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_utente";

	//////////////////////////////////////////////////////////////////////


    private Long       idUtente     ; // Id or Primary Key

    private String     codiceFiscale ;
    private String     cognome      ;
    private String     nome         ;
    //private Long       idProfilo    ;
    private String     flEliminato  ;

    /**
     * Set the "idUtente" field value
     * This field is mapped on the database column "id_utente" ( type "int4", NotNull : true )
     * @param idUtente
     */
	public void setIdUtente(Long idUtente) {
        this.idUtente = idUtente ;
    }

    /**
     * Get the "idUtente" field value
     * This field is mapped on the database column "id_utente" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdUtente() {
        return this.idUtente;
    }

    /**
     * Set the "codiceFiscale" field value
     * This field is mapped on the database column "codice_fiscale" ( type "varchar", NotNull : true )
     * @param codiceFiscale
     */
    public void setCodiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }

    /**
     * Get the "codiceFiscale" field value
     * This field is mapped on the database column "codice_fiscale" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodiceFiscale() {
        return this.codiceFiscale;
    }

    /**
     * Set the "cognome" field value
     * This field is mapped on the database column "cognome" ( type "varchar", NotNull : true )
     * @param cognome
     */
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    /**
     * Get the "cognome" field value
     * This field is mapped on the database column "cognome" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCognome() {
        return this.cognome;
    }

    /**
     * Set the "nome" field value
     * This field is mapped on the database column "nome" ( type "varchar", NotNull : true )
     * @param nome
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * Get the "nome" field value
     * This field is mapped on the database column "nome" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getNome() {
        return this.nome;
    }

    /**
     * Set the "idProfilo" field value
     * This field is mapped on the database column "id_profilo" ( type "int4", NotNull : true )
     * @param idProfilo
     */
//    public void setIdProfilo(Long idProfilo) {
//        this.idProfilo = idProfilo;
//    }

    /**
     * Get the "idProfilo" field value
     * This field is mapped on the database column "id_profilo" ( type "int4", NotNull : true )
     * @return the field value
     */
//    public Long getIdProfilo() {
//        return this.idProfilo;
//    }

    /**
     * Set the "flEliminato" field value
     * This field is mapped on the database column "fl_eliminato" ( type "varchar", NotNull : true )
     * @param flEliminato
     */
    public void setFlEliminato(String flEliminato) {
        this.flEliminato = flEliminato;
    }

    /**
     * Get the "flEliminato" field value
     * This field is mapped on the database column "fl_eliminato" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlEliminato() {
        return this.flEliminato;
    }


    @Override
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(idUtente);
        sb.append("|");
        sb.append(codiceFiscale);
        sb.append("|");
        sb.append(cognome);
        sb.append("|");
        sb.append(nome);
        sb.append("|");
//        sb.append(idProfilo);
        sb.append("|");
        sb.append(flEliminato);
        return sb.toString();
    }

}
