/*
 * Java bean class for entity "iscritto_d_log_level"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_log_level"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDLogLevel implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_log_level, " +
		"  descrizione, " +
		"  n_livello " +
		"from iscritto_d_log_level ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_log_level (" +
		"  id_log_level, " +
		"  descrizione, " +
		"  n_livello " +
		") " +
		"values (" +
		"  :idLogLevel, " +
		"  :descrizione, " +
		"  :nLivello " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_log_level where " +
		"  id_log_level = :idLogLevel ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_log_level";

	//////////////////////////////////////////////////////////////////////


    private Long       idLogLevel   ; // Id or Primary Key

    private String     descrizione  ;
    private Integer    nLivello     ;

    /**
     * Set the "idLogLevel" field value
     * This field is mapped on the database column "id_log_level" ( type "numeric", NotNull : true )
     * @param idLogLevel
     */
	public void setIdLogLevel(Long idLogLevel) {
        this.idLogLevel = idLogLevel ;
    }

    /**
     * Get the "idLogLevel" field value
     * This field is mapped on the database column "id_log_level" ( type "numeric", NotNull : true )
     * @return the field value
     */
	public Long getIdLogLevel() {
        return this.idLogLevel;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }

    /**
     * Set the "nLivello" field value
     * This field is mapped on the database column "n_livello" ( type "numeric", NotNull : false )
     * @param nLivello
     */
    public void setNLivello(Integer nLivello) {
        this.nLivello = nLivello;
    }

    /**
     * Get the "nLivello" field value
     * This field is mapped on the database column "n_livello" ( type "numeric", NotNull : false )
     * @return the field value
     */
    public Integer getNLivello() {
        return this.nLivello;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idLogLevel);
        sb.append("|");
        sb.append(descrizione);
        sb.append("|");
        sb.append(nLivello);
        return sb.toString(); 
    } 

}
