/*
 * Java bean class for entity "iscritto_d_coabitazione"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_coabitazione"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDCoabitazione implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_coabitazione, " +
		"  cod_coabitazione, " +
		"  descrizione " +
		"from iscritto_d_coabitazione ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_coabitazione (" +
		"  id_coabitazione, " +
		"  cod_coabitazione, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idCoabitazione, " +
		"  :codCoabitazione, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_coabitazione where " +
		"  id_coabitazione = :idCoabitazione ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_coabitazione";

	//////////////////////////////////////////////////////////////////////


    private Long       idCoabitazione ; // Id or Primary Key

    private String     codCoabitazione ;
    private String     descrizione  ;

    /**
     * Set the "idCoabitazione" field value
     * This field is mapped on the database column "id_coabitazione" ( type "int4", NotNull : true )
     * @param idCoabitazione
     */
	public void setIdCoabitazione(Long idCoabitazione) {
        this.idCoabitazione = idCoabitazione ;
    }

    /**
     * Get the "idCoabitazione" field value
     * This field is mapped on the database column "id_coabitazione" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdCoabitazione() {
        return this.idCoabitazione;
    }

    /**
     * Set the "codCoabitazione" field value
     * This field is mapped on the database column "cod_coabitazione" ( type "varchar", NotNull : true )
     * @param codCoabitazione
     */
    public void setCodCoabitazione(String codCoabitazione) {
        this.codCoabitazione = codCoabitazione;
    }

    /**
     * Get the "codCoabitazione" field value
     * This field is mapped on the database column "cod_coabitazione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodCoabitazione() {
        return this.codCoabitazione;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idCoabitazione);
        sb.append("|");
        sb.append(codCoabitazione);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
