/*
 * Java bean class for entity "iscritto_t_stato"
 * Created on 2020-01-30 ( Date ISO 2020-01-30 - Time 14:08:35 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_stato"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTStato implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_stato, " +
		"  id_stato_ministero, " +
		"  continente, " +
		"  stato, " +
		"  codice, " +
		"  dt_start, " +
		"  dt_stop, " +
		"  rel_status, " +
		"  codice_istat, " +
		"  cittadinanza " +
		"from iscritto_t_stato ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_stato (" +
		"  id_stato, " +
		"  id_stato_ministero, " +
		"  continente, " +
		"  stato, " +
		"  codice, " +
		"  dt_start, " +
		"  dt_stop, " +
		"  rel_status, " +
		"  codice_istat, " +
		"  cittadinanza " +
		") " +
		"values (" +
		"  :idStato, " +
		"  :idStatoMinistero, " +
		"  :continente, " +
		"  :stato, " +
		"  :codice, " +
		"  :dtStart, " +
		"  :dtStop, " +
		"  :relStatus, " +
		"  :codiceIstat, " +
		"  :cittadinanza " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_stato where " +
		"  id_stato = :idStato ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_stato";

	//////////////////////////////////////////////////////////////////////


    private Long       idStato      ; // Id or Primary Key

    private Long       idStatoMinistero ;
    private String     continente   ;
    private String     stato        ;
    private String     codice       ;
    private Date       dtStart      ;
    private Date       dtStop       ;
    private String     relStatus    ;
    private String     codiceIstat  ;
    private String     cittadinanza ;

    /**
     * Set the "idStato" field value
     * This field is mapped on the database column "id_stato" ( type "int4", NotNull : true )
     * @param idStato
     */
	public void setIdStato(Long idStato) {
        this.idStato = idStato ;
    }

    /**
     * Get the "idStato" field value
     * This field is mapped on the database column "id_stato" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdStato() {
        return this.idStato;
    }

    /**
     * Set the "idStatoMinistero" field value
     * This field is mapped on the database column "id_stato_ministero" ( type "int4", NotNull : true )
     * @param idStatoMinistero
     */
    public void setIdStatoMinistero(Long idStatoMinistero) {
        this.idStatoMinistero = idStatoMinistero;
    }

    /**
     * Get the "idStatoMinistero" field value
     * This field is mapped on the database column "id_stato_ministero" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdStatoMinistero() {
        return this.idStatoMinistero;
    }

    /**
     * Set the "continente" field value
     * This field is mapped on the database column "continente" ( type "varchar", NotNull : true )
     * @param continente
     */
    public void setContinente(String continente) {
        this.continente = continente;
    }

    /**
     * Get the "continente" field value
     * This field is mapped on the database column "continente" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getContinente() {
        return this.continente;
    }

    /**
     * Set the "stato" field value
     * This field is mapped on the database column "stato" ( type "varchar", NotNull : true )
     * @param stato
     */
    public void setStato(String stato) {
        this.stato = stato;
    }

    /**
     * Get the "stato" field value
     * This field is mapped on the database column "stato" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getStato() {
        return this.stato;
    }

    /**
     * Set the "codice" field value
     * This field is mapped on the database column "codice" ( type "varchar", NotNull : true )
     * @param codice
     */
    public void setCodice(String codice) {
        this.codice = codice;
    }

    /**
     * Get the "codice" field value
     * This field is mapped on the database column "codice" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodice() {
        return this.codice;
    }

    /**
     * Set the "dtStart" field value
     * This field is mapped on the database column "dt_start" ( type "timestamp", NotNull : true )
     * @param dtStart
     */
    public void setDtStart(Date dtStart) {
        this.dtStart = dtStart;
    }

    /**
     * Get the "dtStart" field value
     * This field is mapped on the database column "dt_start" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtStart() {
        return this.dtStart;
    }

    /**
     * Set the "dtStop" field value
     * This field is mapped on the database column "dt_stop" ( type "timestamp", NotNull : true )
     * @param dtStop
     */
    public void setDtStop(Date dtStop) {
        this.dtStop = dtStop;
    }

    /**
     * Get the "dtStop" field value
     * This field is mapped on the database column "dt_stop" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtStop() {
        return this.dtStop;
    }

    /**
     * Set the "relStatus" field value
     * This field is mapped on the database column "rel_status" ( type "varchar", NotNull : true )
     * @param relStatus
     */
    public void setRelStatus(String relStatus) {
        this.relStatus = relStatus;
    }

    /**
     * Get the "relStatus" field value
     * This field is mapped on the database column "rel_status" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getRelStatus() {
        return this.relStatus;
    }

    /**
     * Set the "codiceIstat" field value
     * This field is mapped on the database column "codice_istat" ( type "varchar", NotNull : false )
     * @param codiceIstat
     */
    public void setCodiceIstat(String codiceIstat) {
        this.codiceIstat = codiceIstat;
    }

    /**
     * Get the "codiceIstat" field value
     * This field is mapped on the database column "codice_istat" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getCodiceIstat() {
        return this.codiceIstat;
    }

    /**
     * Set the "cittadinanza" field value
     * This field is mapped on the database column "cittadinanza" ( type "varchar", NotNull : false )
     * @param cittadinanza
     */
    public void setCittadinanza(String cittadinanza) {
        this.cittadinanza = cittadinanza;
    }

    /**
     * Get the "cittadinanza" field value
     * This field is mapped on the database column "cittadinanza" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getCittadinanza() {
        return this.cittadinanza;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idStato);
        sb.append("|");
        sb.append(idStatoMinistero);
        sb.append("|");
        sb.append(continente);
        sb.append("|");
        sb.append(stato);
        sb.append("|");
        sb.append(codice);
        sb.append("|");
        sb.append(dtStart);
        sb.append("|");
        sb.append(dtStop);
        sb.append("|");
        sb.append(relStatus);
        sb.append("|");
        sb.append(codiceIstat);
        sb.append("|");
        sb.append(cittadinanza);
        return sb.toString(); 
    } 

}
