/*
 * Java bean class for entity "iscritto_t_eta_fratello_freq"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_eta_fratello_freq"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTEtaFratelloFreq implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_anagrafica_gra, " +
		"  id_categoria_scu, " +
		"  id_ordine_scuola, " +
		"  data_da, " +
		"  data_a " +
		"from iscritto_t_eta_fratello_freq ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_eta_fratello_freq (" +
		"  id_anagrafica_gra, " +
		"  id_categoria_scu, " +
		"  id_ordine_scuola, " +
		"  data_da, " +
		"  data_a " +
		") " +
		"values (" +
		"  :idAnagraficaGra, " +
		"  :idCategoriaScu, " +
		"  :idOrdineScuola, " +
		"  :dataDa, " +
		"  :dataA " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_eta_fratello_freq where " +
		"  id_anagrafica_gra = :idAnagraficaGra and " +
		"  id_categoria_scu = :idCategoriaScu and " +
		"  id_ordine_scuola = :idOrdineScuola ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_eta_fratello_freq";

	//////////////////////////////////////////////////////////////////////


    private Long       idAnagraficaGra ; // Id or Primary Key
    private Long       idCategoriaScu ; // Id or Primary Key
    private Long       idOrdineScuola ; // Id or Primary Key

    private Date       dataDa       ;
    private Date       dataA        ;

    /**
     * Set the "idAnagraficaGra" field value
     * This field is mapped on the database column "id_anagrafica_gra" ( type "int4", NotNull : true )
     * @param idAnagraficaGra
     */
	public void setIdAnagraficaGra(Long idAnagraficaGra) {
        this.idAnagraficaGra = idAnagraficaGra ;
    }

    /**
     * Get the "idAnagraficaGra" field value
     * This field is mapped on the database column "id_anagrafica_gra" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdAnagraficaGra() {
        return this.idAnagraficaGra;
    }
    /**
     * Set the "idCategoriaScu" field value
     * This field is mapped on the database column "id_categoria_scu" ( type "int4", NotNull : true )
     * @param idCategoriaScu
     */
	public void setIdCategoriaScu(Long idCategoriaScu) {
        this.idCategoriaScu = idCategoriaScu ;
    }

    /**
     * Get the "idCategoriaScu" field value
     * This field is mapped on the database column "id_categoria_scu" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdCategoriaScu() {
        return this.idCategoriaScu;
    }
    /**
     * Set the "idOrdineScuola" field value
     * This field is mapped on the database column "id_ordine_scuola" ( type "int4", NotNull : true )
     * @param idOrdineScuola
     */
	public void setIdOrdineScuola(Long idOrdineScuola) {
        this.idOrdineScuola = idOrdineScuola ;
    }

    /**
     * Get the "idOrdineScuola" field value
     * This field is mapped on the database column "id_ordine_scuola" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdOrdineScuola() {
        return this.idOrdineScuola;
    }

    /**
     * Set the "dataDa" field value
     * This field is mapped on the database column "data_da" ( type "timestamp", NotNull : true )
     * @param dataDa
     */
    public void setDataDa(Date dataDa) {
        this.dataDa = dataDa;
    }

    /**
     * Get the "dataDa" field value
     * This field is mapped on the database column "data_da" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDataDa() {
        return this.dataDa;
    }

    /**
     * Set the "dataA" field value
     * This field is mapped on the database column "data_a" ( type "timestamp", NotNull : true )
     * @param dataA
     */
    public void setDataA(Date dataA) {
        this.dataA = dataA;
    }

    /**
     * Get the "dataA" field value
     * This field is mapped on the database column "data_a" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDataA() {
        return this.dataA;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idAnagraficaGra);
        sb.append("|");
        sb.append(idCategoriaScu);
        sb.append("|");
        sb.append(idOrdineScuola);
        sb.append("|");
        sb.append(dataDa);
        sb.append("|");
        sb.append(dataA);
        return sb.toString(); 
    } 

}
