/*
 * Java bean class for entity "iscritto_t_privilegio"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_privilegio"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTPrivilegio implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_privilegio, " +
		"  cod_privilegio, " +
		"  descrizione, " +
		"  id_attivita " +
		"from iscritto_t_privilegio ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_privilegio (" +
		"  id_privilegio, " +
		"  cod_privilegio, " +
		"  descrizione, " +
		"  id_attivita " +
		") " +
		"values (" +
		"  :idPrivilegio, " +
		"  :codPrivilegio, " +
		"  :descrizione, " +
		"  :idAttivita " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_privilegio where " +
		"  id_privilegio = :idPrivilegio ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_privilegio";

	//////////////////////////////////////////////////////////////////////


    private Long       idPrivilegio ; // Id or Primary Key

    private String     codPrivilegio ;
    private String     descrizione  ;
    private Long       idAttivita   ;

    /**
     * Set the "idPrivilegio" field value
     * This field is mapped on the database column "id_privilegio" ( type "int4", NotNull : true )
     * @param idPrivilegio
     */
	public void setIdPrivilegio(Long idPrivilegio) {
        this.idPrivilegio = idPrivilegio ;
    }

    /**
     * Get the "idPrivilegio" field value
     * This field is mapped on the database column "id_privilegio" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdPrivilegio() {
        return this.idPrivilegio;
    }

    /**
     * Set the "codPrivilegio" field value
     * This field is mapped on the database column "cod_privilegio" ( type "varchar", NotNull : false )
     * @param codPrivilegio
     */
    public void setCodPrivilegio(String codPrivilegio) {
        this.codPrivilegio = codPrivilegio;
    }

    /**
     * Get the "codPrivilegio" field value
     * This field is mapped on the database column "cod_privilegio" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getCodPrivilegio() {
        return this.codPrivilegio;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }

    /**
     * Set the "idAttivita" field value
     * This field is mapped on the database column "id_attivita" ( type "int4", NotNull : false )
     * @param idAttivita
     */
    public void setIdAttivita(Long idAttivita) {
        this.idAttivita = idAttivita;
    }

    /**
     * Get the "idAttivita" field value
     * This field is mapped on the database column "id_attivita" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdAttivita() {
        return this.idAttivita;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idPrivilegio);
        sb.append("|");
        sb.append(codPrivilegio);
        sb.append("|");
        sb.append(descrizione);
        sb.append("|");
        sb.append(idAttivita);
        return sb.toString(); 
    } 

}
