/*
 * Java bean class for entity "iscritto_d_stato_gra"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_stato_gra"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDStatoGra implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_stato_gra, " +
		"  cod_stato_gra, " +
		"  descrizione " +
		"from iscritto_d_stato_gra ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_stato_gra (" +
		"  id_stato_gra, " +
		"  cod_stato_gra, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idStatoGra, " +
		"  :codStatoGra, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_stato_gra where " +
		"  id_stato_gra = :idStatoGra ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_stato_gra";

	//////////////////////////////////////////////////////////////////////


    private Long       idStatoGra   ; // Id or Primary Key

    private String     codStatoGra  ;
    private String     descrizione  ;

    /**
     * Set the "idStatoGra" field value
     * This field is mapped on the database column "id_stato_gra" ( type "int4", NotNull : true )
     * @param idStatoGra
     */
	public void setIdStatoGra(Long idStatoGra) {
        this.idStatoGra = idStatoGra ;
    }

    /**
     * Get the "idStatoGra" field value
     * This field is mapped on the database column "id_stato_gra" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdStatoGra() {
        return this.idStatoGra;
    }

    /**
     * Set the "codStatoGra" field value
     * This field is mapped on the database column "cod_stato_gra" ( type "varchar", NotNull : true )
     * @param codStatoGra
     */
    public void setCodStatoGra(String codStatoGra) {
        this.codStatoGra = codStatoGra;
    }

    /**
     * Get the "codStatoGra" field value
     * This field is mapped on the database column "cod_stato_gra" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodStatoGra() {
        return this.codStatoGra;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idStatoGra);
        sb.append("|");
        sb.append(codStatoGra);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
