/*
 * Java bean class for entity "iscritto_t_invio_sise"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_invio_sise"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTInvioSise implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_domanda_iscrizione, " +
		"  data_accettazione, " +
		"  data_invio, " +
		"  telefono, " +
		"  id_tipo_pasto " +
		"from iscritto_t_invio_sise ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_invio_sise (" +
		"  id_domanda_iscrizione, " +
		"  data_accettazione, " +
		"  data_invio, " +
		"  telefono, " +
		"  id_tipo_pasto " +
		") " +
		"values (" +
		"  :idDomandaIscrizione, " +
		"  :dataAccettazione, " +
		"  :dataInvio, " +
		"  :telefono, " +
		"  :idTipoPasto " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_invio_sise where " +
		"  id_domanda_iscrizione = :idDomandaIscrizione ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_invio_sise";

	//////////////////////////////////////////////////////////////////////


    private Long       idDomandaIscrizione ; // Id or Primary Key

    private Date       dataAccettazione ;
    private Date       dataInvio    ;
    private String     telefono     ;
    private Long       idTipoPasto  ;

    /**
     * Set the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @param idDomandaIscrizione
     */
	public void setIdDomandaIscrizione(Long idDomandaIscrizione) {
        this.idDomandaIscrizione = idDomandaIscrizione ;
    }

    /**
     * Get the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdDomandaIscrizione() {
        return this.idDomandaIscrizione;
    }

    /**
     * Set the "dataAccettazione" field value
     * This field is mapped on the database column "data_accettazione" ( type "date", NotNull : false )
     * @param dataAccettazione
     */
    public void setDataAccettazione(Date dataAccettazione) {
        this.dataAccettazione = dataAccettazione;
    }

    /**
     * Get the "dataAccettazione" field value
     * This field is mapped on the database column "data_accettazione" ( type "date", NotNull : false )
     * @return the field value
     */
    public Date getDataAccettazione() {
        return this.dataAccettazione;
    }

    /**
     * Set the "dataInvio" field value
     * This field is mapped on the database column "data_invio" ( type "date", NotNull : false )
     * @param dataInvio
     */
    public void setDataInvio(Date dataInvio) {
        this.dataInvio = dataInvio;
    }

    /**
     * Get the "dataInvio" field value
     * This field is mapped on the database column "data_invio" ( type "date", NotNull : false )
     * @return the field value
     */
    public Date getDataInvio() {
        return this.dataInvio;
    }

    /**
     * Set the "telefono" field value
     * This field is mapped on the database column "telefono" ( type "varchar", NotNull : false )
     * @param telefono
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * Get the "telefono" field value
     * This field is mapped on the database column "telefono" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getTelefono() {
        return this.telefono;
    }

    /**
     * Set the "idTipoPasto" field value
     * This field is mapped on the database column "id_tipo_pasto" ( type "int4", NotNull : false )
     * @param idTipoPasto
     */
    public void setIdTipoPasto(Long idTipoPasto) {
        this.idTipoPasto = idTipoPasto;
    }

    /**
     * Get the "idTipoPasto" field value
     * This field is mapped on the database column "id_tipo_pasto" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdTipoPasto() {
        return this.idTipoPasto;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idDomandaIscrizione);
        sb.append("|");
        sb.append(dataAccettazione);
        sb.append("|");
        sb.append(dataInvio);
        sb.append("|");
        sb.append(telefono);
        sb.append("|");
        sb.append(idTipoPasto);
        return sb.toString(); 
    } 

}
