/*
 * Java bean class for entity "iscritto_d_tipo_fra"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_tipo_fra"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDTipoFra implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_tipo_fratello, " +
		"  cod_tipo_fratello, " +
		"  descrizione " +
		"from iscritto_d_tipo_fra ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_tipo_fra (" +
		"  id_tipo_fratello, " +
		"  cod_tipo_fratello, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idTipoFratello, " +
		"  :codTipoFratello, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_tipo_fra where " +
		"  id_tipo_fratello = :idTipoFratello ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_tipo_fra";

	//////////////////////////////////////////////////////////////////////


    private Long       idTipoFratello ; // Id or Primary Key

    private String     codTipoFratello ;
    private String     descrizione  ;

    /**
     * Set the "idTipoFratello" field value
     * This field is mapped on the database column "id_tipo_fratello" ( type "int4", NotNull : true )
     * @param idTipoFratello
     */
	public void setIdTipoFratello(Long idTipoFratello) {
        this.idTipoFratello = idTipoFratello ;
    }

    /**
     * Get the "idTipoFratello" field value
     * This field is mapped on the database column "id_tipo_fratello" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdTipoFratello() {
        return this.idTipoFratello;
    }

    /**
     * Set the "codTipoFratello" field value
     * This field is mapped on the database column "cod_tipo_fratello" ( type "varchar", NotNull : true )
     * @param codTipoFratello
     */
    public void setCodTipoFratello(String codTipoFratello) {
        this.codTipoFratello = codTipoFratello;
    }

    /**
     * Get the "codTipoFratello" field value
     * This field is mapped on the database column "cod_tipo_fratello" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodTipoFratello() {
        return this.codTipoFratello;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTipoFratello);
        sb.append("|");
        sb.append(codTipoFratello);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
