/*
 * Java bean class for entity "iscritto_t_dipendente"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_dipendente"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTDipendente implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_condizione_occupazionale, " +
		"  azienda, " +
		"  comune_lavoro, " +
		"  indirizzo_lavoro, " +
		"  provincia_lavoro " +
		"from iscritto_t_dipendente ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_dipendente (" +
		"  id_condizione_occupazionale, " +
		"  azienda, " +
		"  comune_lavoro, " +
		"  indirizzo_lavoro, " +
		"  provincia_lavoro " +
		") " +
		"values (" +
		"  :idCondizioneOccupazionale, " +
		"  :azienda, " +
		"  :comuneLavoro, " +
		"  :indirizzoLavoro, " +
		"  :provinciaLavoro " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_dipendente where " +
		"  id_condizione_occupazionale = :idCondizioneOccupazionale ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_dipendente";

	//////////////////////////////////////////////////////////////////////


    private Long       idCondizioneOccupazionale ; // Id or Primary Key

    private String     azienda      ;
    private String     comuneLavoro ;
    private String     indirizzoLavoro ;
    private String     provinciaLavoro ;

    /**
     * Set the "idCondizioneOccupazionale" field value
     * This field is mapped on the database column "id_condizione_occupazionale" ( type "int4", NotNull : true )
     * @param idCondizioneOccupazionale
     */
	public void setIdCondizioneOccupazionale(Long idCondizioneOccupazionale) {
        this.idCondizioneOccupazionale = idCondizioneOccupazionale ;
    }

    /**
     * Get the "idCondizioneOccupazionale" field value
     * This field is mapped on the database column "id_condizione_occupazionale" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdCondizioneOccupazionale() {
        return this.idCondizioneOccupazionale;
    }

    /**
     * Set the "azienda" field value
     * This field is mapped on the database column "azienda" ( type "varchar", NotNull : false )
     * @param azienda
     */
    public void setAzienda(String azienda) {
        this.azienda = azienda;
    }

    /**
     * Get the "azienda" field value
     * This field is mapped on the database column "azienda" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getAzienda() {
        return this.azienda;
    }

    /**
     * Set the "comuneLavoro" field value
     * This field is mapped on the database column "comune_lavoro" ( type "varchar", NotNull : false )
     * @param comuneLavoro
     */
    public void setComuneLavoro(String comuneLavoro) {
        this.comuneLavoro = comuneLavoro;
    }

    /**
     * Get the "comuneLavoro" field value
     * This field is mapped on the database column "comune_lavoro" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getComuneLavoro() {
        return this.comuneLavoro;
    }

    /**
     * Set the "indirizzoLavoro" field value
     * This field is mapped on the database column "indirizzo_lavoro" ( type "varchar", NotNull : false )
     * @param indirizzoLavoro
     */
    public void setIndirizzoLavoro(String indirizzoLavoro) {
        this.indirizzoLavoro = indirizzoLavoro;
    }

    /**
     * Get the "indirizzoLavoro" field value
     * This field is mapped on the database column "indirizzo_lavoro" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getIndirizzoLavoro() {
        return this.indirizzoLavoro;
    }

    /**
     * Set the "provinciaLavoro" field value
     * This field is mapped on the database column "provincia_lavoro" ( type "varchar", NotNull : false )
     * @param provinciaLavoro
     */
    public void setProvinciaLavoro(String provinciaLavoro) {
        this.provinciaLavoro = provinciaLavoro;
    }

    /**
     * Get the "provinciaLavoro" field value
     * This field is mapped on the database column "provincia_lavoro" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getProvinciaLavoro() {
        return this.provinciaLavoro;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idCondizioneOccupazionale);
        sb.append("|");
        sb.append(azienda);
        sb.append("|");
        sb.append(comuneLavoro);
        sb.append("|");
        sb.append(indirizzoLavoro);
        sb.append("|");
        sb.append(provinciaLavoro);
        return sb.toString(); 
    } 

}
