/*
 * Java bean class for entity "iscritto_t_condizione_occ"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_condizione_occ"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTCondizioneOcc implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_condizione_occupazionale, " +
		"  id_anagrafica_soggetto, " +
		"  id_tip_cond_occupazionale " +
		"from iscritto_t_condizione_occ ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_condizione_occ (" +
		"  id_condizione_occupazionale, " +
		"  id_anagrafica_soggetto, " +
		"  id_tip_cond_occupazionale " +
		") " +
		"values (" +
		"  :idCondizioneOccupazionale, " +
		"  :idAnagraficaSoggetto, " +
		"  :idTipCondOccupazionale " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_condizione_occ where " +
		"  id_condizione_occupazionale = :idCondizioneOccupazionale ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_condizione_occ";

	//////////////////////////////////////////////////////////////////////


    private Long       idCondizioneOccupazionale ; // Id or Primary Key

    private Long       idAnagraficaSoggetto ;
    private Long       idTipCondOccupazionale ;

    /**
     * Set the "idCondizioneOccupazionale" field value
     * This field is mapped on the database column "id_condizione_occupazionale" ( type "int4", NotNull : true )
     * @param idCondizioneOccupazionale
     */
	public void setIdCondizioneOccupazionale(Long idCondizioneOccupazionale) {
        this.idCondizioneOccupazionale = idCondizioneOccupazionale ;
    }

    /**
     * Get the "idCondizioneOccupazionale" field value
     * This field is mapped on the database column "id_condizione_occupazionale" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdCondizioneOccupazionale() {
        return this.idCondizioneOccupazionale;
    }

    /**
     * Set the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : true )
     * @param idAnagraficaSoggetto
     */
    public void setIdAnagraficaSoggetto(Long idAnagraficaSoggetto) {
        this.idAnagraficaSoggetto = idAnagraficaSoggetto;
    }

    /**
     * Get the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdAnagraficaSoggetto() {
        return this.idAnagraficaSoggetto;
    }

    /**
     * Set the "idTipCondOccupazionale" field value
     * This field is mapped on the database column "id_tip_cond_occupazionale" ( type "int4", NotNull : true )
     * @param idTipCondOccupazionale
     */
    public void setIdTipCondOccupazionale(Long idTipCondOccupazionale) {
        this.idTipCondOccupazionale = idTipCondOccupazionale;
    }

    /**
     * Get the "idTipCondOccupazionale" field value
     * This field is mapped on the database column "id_tip_cond_occupazionale" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdTipCondOccupazionale() {
        return this.idTipCondOccupazionale;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idCondizioneOccupazionale);
        sb.append("|");
        sb.append(idAnagraficaSoggetto);
        sb.append("|");
        sb.append(idTipCondOccupazionale);
        return sb.toString(); 
    } 

}
