/*
 * Java bean class for entity "iscritto_d_stato_dom"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_stato_dom"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDStatoDom implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_stato_dom, " +
		"  cod_stato_dom, " +
		"  descrizione " +
		"from iscritto_d_stato_dom ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_stato_dom (" +
		"  id_stato_dom, " +
		"  cod_stato_dom, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idStatoDom, " +
		"  :codStatoDom, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_stato_dom where " +
		"  id_stato_dom = :idStatoDom ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_stato_dom";

	//////////////////////////////////////////////////////////////////////


    private Long       idStatoDom   ; // Id or Primary Key

    private String     codStatoDom  ;
    private String     descrizione  ;

    /**
     * Set the "idStatoDom" field value
     * This field is mapped on the database column "id_stato_dom" ( type "int4", NotNull : true )
     * @param idStatoDom
     */
	public void setIdStatoDom(Long idStatoDom) {
        this.idStatoDom = idStatoDom ;
    }

    /**
     * Get the "idStatoDom" field value
     * This field is mapped on the database column "id_stato_dom" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdStatoDom() {
        return this.idStatoDom;
    }

    /**
     * Set the "codStatoDom" field value
     * This field is mapped on the database column "cod_stato_dom" ( type "varchar", NotNull : true )
     * @param codStatoDom
     */
    public void setCodStatoDom(String codStatoDom) {
        this.codStatoDom = codStatoDom;
    }

    /**
     * Get the "codStatoDom" field value
     * This field is mapped on the database column "cod_stato_dom" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodStatoDom() {
        return this.codStatoDom;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idStatoDom);
        sb.append("|");
        sb.append(codStatoDom);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
