/*
 * Java bean class for entity "iscritto_t_indirizzo_res"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_indirizzo_res"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTIndirizzoRes implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  indirizzo, " +
		"  cap, " +
		"  id_anagrafica_soggetto, " +
		"  id_comune, " +
		"  id_stato_residenza " +
		"from iscritto_t_indirizzo_res ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_indirizzo_res (" +
		"  indirizzo, " +
		"  cap, " +
		"  id_anagrafica_soggetto, " +
		"  id_comune, " +
		"  id_stato_residenza " +
		") " +
		"values (" +
		"  :indirizzo, " +
		"  :cap, " +
		"  :idAnagraficaSoggetto, " +
		"  :idComune, " +
		"  :idStatoResidenza " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_indirizzo_res where " +
		"  id_anagrafica_soggetto = :idAnagraficaSoggetto ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_indirizzo_res";

	//////////////////////////////////////////////////////////////////////


    private Long       idAnagraficaSoggetto ; // Id or Primary Key

    private String     indirizzo    ;
    private String     cap          ;
    private Long       idComune     ;
    private Long       idStatoResidenza ;

    /**
     * Set the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : true )
     * @param idAnagraficaSoggetto
     */
	public void setIdAnagraficaSoggetto(Long idAnagraficaSoggetto) {
        this.idAnagraficaSoggetto = idAnagraficaSoggetto ;
    }

    /**
     * Get the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdAnagraficaSoggetto() {
        return this.idAnagraficaSoggetto;
    }

    /**
     * Set the "indirizzo" field value
     * This field is mapped on the database column "indirizzo" ( type "varchar", NotNull : false )
     * @param indirizzo
     */
    public void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }

    /**
     * Get the "indirizzo" field value
     * This field is mapped on the database column "indirizzo" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getIndirizzo() {
        return this.indirizzo;
    }

    /**
     * Set the "cap" field value
     * This field is mapped on the database column "cap" ( type "varchar", NotNull : false )
     * @param cap
     */
    public void setCap(String cap) {
        this.cap = cap;
    }

    /**
     * Get the "cap" field value
     * This field is mapped on the database column "cap" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getCap() {
        return this.cap;
    }

    /**
     * Set the "idComune" field value
     * This field is mapped on the database column "id_comune" ( type "int4", NotNull : false )
     * @param idComune
     */
    public void setIdComune(Long idComune) {
        this.idComune = idComune;
    }

    /**
     * Get the "idComune" field value
     * This field is mapped on the database column "id_comune" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdComune() {
        return this.idComune;
    }

    /**
     * Set the "idStatoResidenza" field value
     * This field is mapped on the database column "id_stato_residenza" ( type "int4", NotNull : true )
     * @param idStatoResidenza
     */
    public void setIdStatoResidenza(Long idStatoResidenza) {
        this.idStatoResidenza = idStatoResidenza;
    }

    /**
     * Get the "idStatoResidenza" field value
     * This field is mapped on the database column "id_stato_residenza" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdStatoResidenza() {
        return this.idStatoResidenza;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(indirizzo);
        sb.append("|");
        sb.append(cap);
        sb.append("|");
        sb.append(idAnagraficaSoggetto);
        sb.append("|");
        sb.append(idComune);
        sb.append("|");
        sb.append(idStatoResidenza);
        return sb.toString(); 
    } 

}
