/*
 * Java bean class for entity "iscritto_d_tipo_pasto"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_tipo_pasto"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDTipoPasto implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_tipo_pasto, " +
		"  cod_tipo_pasto, " +
		"  descrizione " +
		"from iscritto_d_tipo_pasto ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_tipo_pasto (" +
		"  id_tipo_pasto, " +
		"  cod_tipo_pasto, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idTipoPasto, " +
		"  :codTipoPasto, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_tipo_pasto where " +
		"  id_tipo_pasto = :idTipoPasto ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_tipo_pasto";

	//////////////////////////////////////////////////////////////////////


    private Long       idTipoPasto  ; // Id or Primary Key

    private String     codTipoPasto ;
    private String     descrizione  ;

    /**
     * Set the "idTipoPasto" field value
     * This field is mapped on the database column "id_tipo_pasto" ( type "int4", NotNull : true )
     * @param idTipoPasto
     */
	public void setIdTipoPasto(Long idTipoPasto) {
        this.idTipoPasto = idTipoPasto ;
    }

    /**
     * Get the "idTipoPasto" field value
     * This field is mapped on the database column "id_tipo_pasto" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdTipoPasto() {
        return this.idTipoPasto;
    }

    /**
     * Set the "codTipoPasto" field value
     * This field is mapped on the database column "cod_tipo_pasto" ( type "varchar", NotNull : false )
     * @param codTipoPasto
     */
    public void setCodTipoPasto(String codTipoPasto) {
        this.codTipoPasto = codTipoPasto;
    }

    /**
     * Get the "codTipoPasto" field value
     * This field is mapped on the database column "cod_tipo_pasto" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getCodTipoPasto() {
        return this.codTipoPasto;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTipoPasto);
        sb.append("|");
        sb.append(codTipoPasto);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
