/*
 * Java bean class for entity "iscritto_r_profilo_pri"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_r_profilo_pri"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoRProfiloPri implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_profilo, " +
		"  id_privilegio, " +
		"  fl_rw " +
		"from iscritto_r_profilo_pri ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_r_profilo_pri (" +
		"  id_profilo, " +
		"  id_privilegio, " +
		"  fl_rw " +
		") " +
		"values (" +
		"  :idProfilo, " +
		"  :idPrivilegio, " +
		"  :flRw " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_r_profilo_pri where " +
		"  id_profilo = :idProfilo and " +
		"  id_privilegio = :idPrivilegio ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_r_profilo_pri";

	//////////////////////////////////////////////////////////////////////


    private Long       idProfilo    ; // Id or Primary Key
    private Long       idPrivilegio ; // Id or Primary Key

    private String     flRw         ;

    /**
     * Set the "idProfilo" field value
     * This field is mapped on the database column "id_profilo" ( type "int4", NotNull : true )
     * @param idProfilo
     */
	public void setIdProfilo(Long idProfilo) {
        this.idProfilo = idProfilo ;
    }

    /**
     * Get the "idProfilo" field value
     * This field is mapped on the database column "id_profilo" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdProfilo() {
        return this.idProfilo;
    }
    /**
     * Set the "idPrivilegio" field value
     * This field is mapped on the database column "id_privilegio" ( type "int4", NotNull : true )
     * @param idPrivilegio
     */
	public void setIdPrivilegio(Long idPrivilegio) {
        this.idPrivilegio = idPrivilegio ;
    }

    /**
     * Get the "idPrivilegio" field value
     * This field is mapped on the database column "id_privilegio" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdPrivilegio() {
        return this.idPrivilegio;
    }

    /**
     * Set the "flRw" field value
     * This field is mapped on the database column "fl_rw" ( type "varchar", NotNull : true )
     * @param flRw
     */
    public void setFlRw(String flRw) {
        this.flRw = flRw;
    }

    /**
     * Get the "flRw" field value
     * This field is mapped on the database column "fl_rw" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlRw() {
        return this.flRw;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idProfilo);
        sb.append("|");
        sb.append(idPrivilegio);
        sb.append("|");
        sb.append(flRw);
        return sb.toString(); 
    } 

}
