/*
 * Java bean class for entity "iscritto_d_categoria_scu"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_categoria_scu"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDCategoriaScu implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_categoria_scu, " +
		"  codice_categoria_scu, " +
		"  descrizione " +
		"from iscritto_d_categoria_scu ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_categoria_scu (" +
		"  id_categoria_scu, " +
		"  codice_categoria_scu, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idCategoriaScu, " +
		"  :codiceCategoriaScu, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_categoria_scu where " +
		"  id_categoria_scu = :idCategoriaScu ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_categoria_scu";

	//////////////////////////////////////////////////////////////////////


    private Long       idCategoriaScu ; // Id or Primary Key

    private String     codiceCategoriaScu ;
    private String     descrizione  ;

    /**
     * Set the "idCategoriaScu" field value
     * This field is mapped on the database column "id_categoria_scu" ( type "int4", NotNull : true )
     * @param idCategoriaScu
     */
	public void setIdCategoriaScu(Long idCategoriaScu) {
        this.idCategoriaScu = idCategoriaScu ;
    }

    /**
     * Get the "idCategoriaScu" field value
     * This field is mapped on the database column "id_categoria_scu" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdCategoriaScu() {
        return this.idCategoriaScu;
    }

    /**
     * Set the "codiceCategoriaScu" field value
     * This field is mapped on the database column "codice_categoria_scu" ( type "varchar", NotNull : true )
     * @param codiceCategoriaScu
     */
    public void setCodiceCategoriaScu(String codiceCategoriaScu) {
        this.codiceCategoriaScu = codiceCategoriaScu;
    }

    /**
     * Get the "codiceCategoriaScu" field value
     * This field is mapped on the database column "codice_categoria_scu" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodiceCategoriaScu() {
        return this.codiceCategoriaScu;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idCategoriaScu);
        sb.append("|");
        sb.append(codiceCategoriaScu);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
