/*
 * Java bean class for entity "iscritto_t_log_dett"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_log_dett"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTLogDett implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_log, " +
		"  id_log_dett, " +
		"  d_inserimento, " +
		"  s_proc_log_dett, " +
		"  s_nota_log_dett, " +
		"  s_valore1, " +
		"  s_valore2, " +
		"  s_valore3, " +
		"  s_valore4, " +
		"  s_valore5, " +
		"  id_log_level " +
		"from iscritto_t_log_dett ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_log_dett (" +
		"  id_log, " +
		"  id_log_dett, " +
		"  d_inserimento, " +
		"  s_proc_log_dett, " +
		"  s_nota_log_dett, " +
		"  s_valore1, " +
		"  s_valore2, " +
		"  s_valore3, " +
		"  s_valore4, " +
		"  s_valore5, " +
		"  id_log_level " +
		") " +
		"values (" +
		"  :idLog, " +
		"  :idLogDett, " +
		"  :dInserimento, " +
		"  :sProcLogDett, " +
		"  :sNotaLogDett, " +
		"  :sValore1, " +
		"  :sValore2, " +
		"  :sValore3, " +
		"  :sValore4, " +
		"  :sValore5, " +
		"  :idLogLevel " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_log_dett where " +
		"  id_log = :idLog and " +
		"  id_log_dett = :idLogDett ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_log_dett";

	//////////////////////////////////////////////////////////////////////


    private Long       idLog        ; // Id or Primary Key
    private Long       idLogDett    ; // Id or Primary Key

    private Date       dInserimento ;
    private String     sProcLogDett ;
    private String     sNotaLogDett ;
    private String     sValore1     ;
    private String     sValore2     ;
    private String     sValore3     ;
    private String     sValore4     ;
    private String     sValore5     ;
    private Long       idLogLevel   ;

    /**
     * Set the "idLog" field value
     * This field is mapped on the database column "id_log" ( type "numeric", NotNull : true )
     * @param idLog
     */
	public void setIdLog(Long idLog) {
        this.idLog = idLog ;
    }

    /**
     * Get the "idLog" field value
     * This field is mapped on the database column "id_log" ( type "numeric", NotNull : true )
     * @return the field value
     */
	public Long getIdLog() {
        return this.idLog;
    }
    /**
     * Set the "idLogDett" field value
     * This field is mapped on the database column "id_log_dett" ( type "int4", NotNull : true )
     * @param idLogDett
     */
	public void setIdLogDett(Long idLogDett) {
        this.idLogDett = idLogDett ;
    }

    /**
     * Get the "idLogDett" field value
     * This field is mapped on the database column "id_log_dett" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdLogDett() {
        return this.idLogDett;
    }

    /**
     * Set the "dInserimento" field value
     * This field is mapped on the database column "d_inserimento" ( type "timestamp", NotNull : false )
     * @param dInserimento
     */
    public void setDInserimento(Date dInserimento) {
        this.dInserimento = dInserimento;
    }

    /**
     * Get the "dInserimento" field value
     * This field is mapped on the database column "d_inserimento" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDInserimento() {
        return this.dInserimento;
    }

    /**
     * Set the "sProcLogDett" field value
     * This field is mapped on the database column "s_proc_log_dett" ( type "varchar", NotNull : false )
     * @param sProcLogDett
     */
    public void setSProcLogDett(String sProcLogDett) {
        this.sProcLogDett = sProcLogDett;
    }

    /**
     * Get the "sProcLogDett" field value
     * This field is mapped on the database column "s_proc_log_dett" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getSProcLogDett() {
        return this.sProcLogDett;
    }

    /**
     * Set the "sNotaLogDett" field value
     * This field is mapped on the database column "s_nota_log_dett" ( type "varchar", NotNull : false )
     * @param sNotaLogDett
     */
    public void setSNotaLogDett(String sNotaLogDett) {
        this.sNotaLogDett = sNotaLogDett;
    }

    /**
     * Get the "sNotaLogDett" field value
     * This field is mapped on the database column "s_nota_log_dett" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getSNotaLogDett() {
        return this.sNotaLogDett;
    }

    /**
     * Set the "sValore1" field value
     * This field is mapped on the database column "s_valore1" ( type "varchar", NotNull : false )
     * @param sValore1
     */
    public void setSValore1(String sValore1) {
        this.sValore1 = sValore1;
    }

    /**
     * Get the "sValore1" field value
     * This field is mapped on the database column "s_valore1" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getSValore1() {
        return this.sValore1;
    }

    /**
     * Set the "sValore2" field value
     * This field is mapped on the database column "s_valore2" ( type "varchar", NotNull : false )
     * @param sValore2
     */
    public void setSValore2(String sValore2) {
        this.sValore2 = sValore2;
    }

    /**
     * Get the "sValore2" field value
     * This field is mapped on the database column "s_valore2" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getSValore2() {
        return this.sValore2;
    }

    /**
     * Set the "sValore3" field value
     * This field is mapped on the database column "s_valore3" ( type "varchar", NotNull : false )
     * @param sValore3
     */
    public void setSValore3(String sValore3) {
        this.sValore3 = sValore3;
    }

    /**
     * Get the "sValore3" field value
     * This field is mapped on the database column "s_valore3" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getSValore3() {
        return this.sValore3;
    }

    /**
     * Set the "sValore4" field value
     * This field is mapped on the database column "s_valore4" ( type "varchar", NotNull : false )
     * @param sValore4
     */
    public void setSValore4(String sValore4) {
        this.sValore4 = sValore4;
    }

    /**
     * Get the "sValore4" field value
     * This field is mapped on the database column "s_valore4" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getSValore4() {
        return this.sValore4;
    }

    /**
     * Set the "sValore5" field value
     * This field is mapped on the database column "s_valore5" ( type "varchar", NotNull : false )
     * @param sValore5
     */
    public void setSValore5(String sValore5) {
        this.sValore5 = sValore5;
    }

    /**
     * Get the "sValore5" field value
     * This field is mapped on the database column "s_valore5" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getSValore5() {
        return this.sValore5;
    }

    /**
     * Set the "idLogLevel" field value
     * This field is mapped on the database column "id_log_level" ( type "int2", NotNull : false )
     * @param idLogLevel
     */
    public void setIdLogLevel(Long idLogLevel) {
        this.idLogLevel = idLogLevel;
    }

    /**
     * Get the "idLogLevel" field value
     * This field is mapped on the database column "id_log_level" ( type "int2", NotNull : false )
     * @return the field value
     */
    public Long getIdLogLevel() {
        return this.idLogLevel;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idLog);
        sb.append("|");
        sb.append(idLogDett);
        sb.append("|");
        sb.append(dInserimento);
        sb.append("|");
        sb.append(sProcLogDett);
        sb.append("|");
        sb.append(sNotaLogDett);
        sb.append("|");
        sb.append(sValore1);
        sb.append("|");
        sb.append(sValore2);
        sb.append("|");
        sb.append(sValore3);
        sb.append("|");
        sb.append(sValore4);
        sb.append("|");
        sb.append(sValore5);
        sb.append("|");
        sb.append(idLogLevel);
        return sb.toString(); 
    } 

}
