/*
 * Java bean class for entity "iscritto_t_step_gra"
 * Created on 2019-05-20 ( Date ISO 2019-05-20 - Time 09:56:14 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_step_gra"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTStepGra implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  step, " +
		"  dt_step_gra, " +
		"  id_step_gra, " +
		"  id_anagrafica_gra, " +
		"  dt_dom_inv_da, " +
		"  dt_dom_inv_a, " +
		"  dt_allegati " +
		"from iscritto_t_step_gra ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_step_gra (" +
		"  step, " +
		"  dt_step_gra, " +
		"  id_step_gra, " +
		"  id_anagrafica_gra, " +
		"  dt_dom_inv_da, " +
		"  dt_dom_inv_a, " +
		"  dt_allegati " +
		") " +
		"values (" +
		"  :step, " +
		"  :dtStepGra, " +
		"  :idStepGra, " +
		"  :idAnagraficaGra, " +
		"  :dtDomInvDa, " +
		"  :dtDomInvA, " +
		"  :dtAllegati " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_step_gra where " +
		"  id_step_gra = :idStepGra ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_step_gra";

	//////////////////////////////////////////////////////////////////////


    private Long       idStepGra    ; // Id or Primary Key

    private Integer    step         ;
    private Date       dtStepGra    ;
    private Long       idAnagraficaGra ;
    private Date       dtDomInvDa   ;
    private Date       dtDomInvA    ;
    private Date       dtAllegati   ;

    /**
     * Set the "idStepGra" field value
     * This field is mapped on the database column "id_step_gra" ( type "int4", NotNull : true )
     * @param idStepGra
     */
	public void setIdStepGra(Long idStepGra) {
        this.idStepGra = idStepGra ;
    }

    /**
     * Get the "idStepGra" field value
     * This field is mapped on the database column "id_step_gra" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdStepGra() {
        return this.idStepGra;
    }

    /**
     * Set the "step" field value
     * This field is mapped on the database column "step" ( type "int4", NotNull : true )
     * @param step
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * Get the "step" field value
     * This field is mapped on the database column "step" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Integer getStep() {
        return this.step;
    }

    /**
     * Set the "dtStepGra" field value
     * This field is mapped on the database column "dt_step_gra" ( type "timestamp", NotNull : true )
     * @param dtStepGra
     */
    public void setDtStepGra(Date dtStepGra) {
        this.dtStepGra = dtStepGra;
    }

    /**
     * Get the "dtStepGra" field value
     * This field is mapped on the database column "dt_step_gra" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtStepGra() {
        return this.dtStepGra;
    }

    /**
     * Set the "idAnagraficaGra" field value
     * This field is mapped on the database column "id_anagrafica_gra" ( type "int4", NotNull : true )
     * @param idAnagraficaGra
     */
    public void setIdAnagraficaGra(Long idAnagraficaGra) {
        this.idAnagraficaGra = idAnagraficaGra;
    }

    /**
     * Get the "idAnagraficaGra" field value
     * This field is mapped on the database column "id_anagrafica_gra" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdAnagraficaGra() {
        return this.idAnagraficaGra;
    }

    /**
     * Set the "dtDomInvDa" field value
     * This field is mapped on the database column "dt_dom_inv_da" ( type "timestamp", NotNull : true )
     * @param dtDomInvDa
     */
    public void setDtDomInvDa(Date dtDomInvDa) {
        this.dtDomInvDa = dtDomInvDa;
    }

    /**
     * Get the "dtDomInvDa" field value
     * This field is mapped on the database column "dt_dom_inv_da" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtDomInvDa() {
        return this.dtDomInvDa;
    }

    /**
     * Set the "dtDomInvA" field value
     * This field is mapped on the database column "dt_dom_inv_a" ( type "timestamp", NotNull : true )
     * @param dtDomInvA
     */
    public void setDtDomInvA(Date dtDomInvA) {
        this.dtDomInvA = dtDomInvA;
    }

    /**
     * Get the "dtDomInvA" field value
     * This field is mapped on the database column "dt_dom_inv_a" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtDomInvA() {
        return this.dtDomInvA;
    }

    /**
     * Set the "dtAllegati" field value
     * This field is mapped on the database column "dt_allegati" ( type "timestamp", NotNull : false )
     * @param dtAllegati
     */
    public void setDtAllegati(Date dtAllegati) {
        this.dtAllegati = dtAllegati;
    }

    /**
     * Get the "dtAllegati" field value
     * This field is mapped on the database column "dt_allegati" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtAllegati() {
        return this.dtAllegati;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(step);
        sb.append("|");
        sb.append(dtStepGra);
        sb.append("|");
        sb.append(idStepGra);
        sb.append("|");
        sb.append(idAnagraficaGra);
        sb.append("|");
        sb.append(dtDomInvDa);
        sb.append("|");
        sb.append(dtDomInvA);
        sb.append("|");
        sb.append(dtAllegati);
        return sb.toString(); 
    } 

}
