/*
 * Java bean class for entity "iscritto_d_tipo_cambio_res"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_tipo_cambio_res"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDTipoCambioRes implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_tipo_cambio_res, " +
		"  cod_tipo_cambio_res, " +
		"  descrizione " +
		"from iscritto_d_tipo_cambio_res ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_tipo_cambio_res (" +
		"  id_tipo_cambio_res, " +
		"  cod_tipo_cambio_res, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idTipoCambioRes, " +
		"  :codTipoCambioRes, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_tipo_cambio_res where " +
		"  id_tipo_cambio_res = :idTipoCambioRes ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_tipo_cambio_res";

	//////////////////////////////////////////////////////////////////////


    private Long       idTipoCambioRes ; // Id or Primary Key

    private String     codTipoCambioRes ;
    private String     descrizione  ;

    /**
     * Set the "idTipoCambioRes" field value
     * This field is mapped on the database column "id_tipo_cambio_res" ( type "int4", NotNull : true )
     * @param idTipoCambioRes
     */
	public void setIdTipoCambioRes(Long idTipoCambioRes) {
        this.idTipoCambioRes = idTipoCambioRes ;
    }

    /**
     * Get the "idTipoCambioRes" field value
     * This field is mapped on the database column "id_tipo_cambio_res" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdTipoCambioRes() {
        return this.idTipoCambioRes;
    }

    /**
     * Set the "codTipoCambioRes" field value
     * This field is mapped on the database column "cod_tipo_cambio_res" ( type "varchar", NotNull : true )
     * @param codTipoCambioRes
     */
    public void setCodTipoCambioRes(String codTipoCambioRes) {
        this.codTipoCambioRes = codTipoCambioRes;
    }

    /**
     * Get the "codTipoCambioRes" field value
     * This field is mapped on the database column "cod_tipo_cambio_res" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodTipoCambioRes() {
        return this.codTipoCambioRes;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTipoCambioRes);
        sb.append("|");
        sb.append(codTipoCambioRes);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
