/*
 * Java bean class for entity "iscritto_d_tipo_pre"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_tipo_pre"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDTipoPre implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_tipo_presentazione, " +
		"  cod_tipo_presentazione, " +
		"  descrizione " +
		"from iscritto_d_tipo_pre ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_tipo_pre (" +
		"  id_tipo_presentazione, " +
		"  cod_tipo_presentazione, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idTipoPresentazione, " +
		"  :codTipoPresentazione, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_tipo_pre where " +
		"  id_tipo_presentazione = :idTipoPresentazione ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_tipo_pre";

	//////////////////////////////////////////////////////////////////////


    private Long       idTipoPresentazione ; // Id or Primary Key

    private String     codTipoPresentazione ;
    private String     descrizione  ;

    /**
     * Set the "idTipoPresentazione" field value
     * This field is mapped on the database column "id_tipo_presentazione" ( type "int4", NotNull : true )
     * @param idTipoPresentazione
     */
	public void setIdTipoPresentazione(Long idTipoPresentazione) {
        this.idTipoPresentazione = idTipoPresentazione ;
    }

    /**
     * Get the "idTipoPresentazione" field value
     * This field is mapped on the database column "id_tipo_presentazione" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdTipoPresentazione() {
        return this.idTipoPresentazione;
    }

    /**
     * Set the "codTipoPresentazione" field value
     * This field is mapped on the database column "cod_tipo_presentazione" ( type "varchar", NotNull : true )
     * @param codTipoPresentazione
     */
    public void setCodTipoPresentazione(String codTipoPresentazione) {
        this.codTipoPresentazione = codTipoPresentazione;
    }

    /**
     * Get the "codTipoPresentazione" field value
     * This field is mapped on the database column "cod_tipo_presentazione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodTipoPresentazione() {
        return this.codTipoPresentazione;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTipoPresentazione);
        sb.append("|");
        sb.append(codTipoPresentazione);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
