/*
 * Java bean class for entity "iscritto_r_nido_contiguo"
 * Created on 2019-11-25 ( Date ISO 2019-11-25 - Time 14:11:49 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_r_nido_contiguo"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoRNidoContiguo implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_domanda_isc, " +
		"  id_anagrafica_soggetto, " +
		"  id_nido_contiguo " +
		"from iscritto_r_nido_contiguo ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_r_nido_contiguo (" +
		"  id_domanda_isc, " +
		"  id_anagrafica_soggetto, " +
		"  id_nido_contiguo " +
		") " +
		"values (" +
		"  :idDomandaIsc, " +
		"  :idAnagraficaSoggetto, " +
		"  :idNidoContiguo " +
		")";

	//////////////////////////////////////////////////////////////////////


	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_r_nido_contiguo";

	//////////////////////////////////////////////////////////////////////



    private Long       idDomandaIsc ;
    private Long       idAnagraficaSoggetto ;
    private Long       idNidoContiguo ;


    /**
     * Set the "idDomandaIsc" field value
     * This field is mapped on the database column "id_domanda_isc" ( type "int4", NotNull : true )
     * @param idDomandaIsc
     */
    public void setIdDomandaIsc(Long idDomandaIsc) {
        this.idDomandaIsc = idDomandaIsc;
    }

    /**
     * Get the "idDomandaIsc" field value
     * This field is mapped on the database column "id_domanda_isc" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdDomandaIsc() {
        return this.idDomandaIsc;
    }

    /**
     * Set the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : true )
     * @param idAnagraficaSoggetto
     */
    public void setIdAnagraficaSoggetto(Long idAnagraficaSoggetto) {
        this.idAnagraficaSoggetto = idAnagraficaSoggetto;
    }

    /**
     * Get the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdAnagraficaSoggetto() {
        return this.idAnagraficaSoggetto;
    }

    /**
     * Set the "idNidoContiguo" field value
     * This field is mapped on the database column "id_nido_contiguo" ( type "int4", NotNull : true )
     * @param idNidoContiguo
     */
    public void setIdNidoContiguo(Long idNidoContiguo) {
        this.idNidoContiguo = idNidoContiguo;
    }

    /**
     * Get the "idNidoContiguo" field value
     * This field is mapped on the database column "id_nido_contiguo" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdNidoContiguo() {
        return this.idNidoContiguo;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idDomandaIsc);
        sb.append("|");
        sb.append(idAnagraficaSoggetto);
        sb.append("|");
        sb.append(idNidoContiguo);
        return sb.toString(); 
    } 

}
