/*
 * Java bean class for entity "iscritto_r_profilo_cp"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_r_profilo_cp"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoRProfiloCp implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_profilo, " +
		"  id_condizione_punteggio " +
		"from iscritto_r_profilo_cp ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_r_profilo_cp (" +
		"  id_profilo, " +
		"  id_condizione_punteggio " +
		") " +
		"values (" +
		"  :idProfilo, " +
		"  :idCondizionePunteggio " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_r_profilo_cp where " +
		"  id_profilo = :idProfilo and " +
		"  id_condizione_punteggio = :idCondizionePunteggio ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_r_profilo_cp";

	//////////////////////////////////////////////////////////////////////


    private Long       idProfilo    ; // Id or Primary Key
    private Long       idCondizionePunteggio ; // Id or Primary Key


    /**
     * Set the "idProfilo" field value
     * This field is mapped on the database column "id_profilo" ( type "int4", NotNull : true )
     * @param idProfilo
     */
	public void setIdProfilo(Long idProfilo) {
        this.idProfilo = idProfilo ;
    }

    /**
     * Get the "idProfilo" field value
     * This field is mapped on the database column "id_profilo" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdProfilo() {
        return this.idProfilo;
    }
    /**
     * Set the "idCondizionePunteggio" field value
     * This field is mapped on the database column "id_condizione_punteggio" ( type "int4", NotNull : true )
     * @param idCondizionePunteggio
     */
	public void setIdCondizionePunteggio(Long idCondizionePunteggio) {
        this.idCondizionePunteggio = idCondizionePunteggio ;
    }

    /**
     * Get the "idCondizionePunteggio" field value
     * This field is mapped on the database column "id_condizione_punteggio" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdCondizionePunteggio() {
        return this.idCondizionePunteggio;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idProfilo);
        sb.append("|");
        sb.append(idCondizionePunteggio);
        return sb.toString(); 
    } 

}
