/*
 * Java bean class for entity "iscritto_t_graduatoria"
 * Created on 2019-05-17 ( Date ISO 2019-05-17 - Time 12:52:46 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_graduatoria"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTGraduatoria implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_graduatoria, " +
		"  id_scuola, " +
		"  id_domanda_iscrizione, " +
		"  punteggio, " +
		"  fl_fuori_termine, " +
		"  id_tipo_frequenza, " +
		"  isee, " +
		"  ordine_preferenza, " +
		"  id_fascia_eta, " +
		"  id_stato_scu, " +
		"  ordinamento, " +
		"  id_step_gra_con " +
		"from iscritto_t_graduatoria ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_graduatoria (" +
		"  id_graduatoria, " +
		"  id_scuola, " +
		"  id_domanda_iscrizione, " +
		"  punteggio, " +
		"  fl_fuori_termine, " +
		"  id_tipo_frequenza, " +
		"  isee, " +
		"  ordine_preferenza, " +
		"  id_fascia_eta, " +
		"  id_stato_scu, " +
		"  ordinamento, " +
		"  id_step_gra_con " +
		") " +
		"values (" +
		"  :idGraduatoria, " +
		"  :idScuola, " +
		"  :idDomandaIscrizione, " +
		"  :punteggio, " +
		"  :flFuoriTermine, " +
		"  :idTipoFrequenza, " +
		"  :isee, " +
		"  :ordinePreferenza, " +
		"  :idFasciaEta, " +
		"  :idStatoScu, " +
		"  :ordinamento, " +
		"  :idStepGraCon " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_graduatoria where " +
		"  id_graduatoria = :idGraduatoria ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_graduatoria";

	//////////////////////////////////////////////////////////////////////


    private Long       idGraduatoria ; // Id or Primary Key

    private Long       idScuola     ;
    private Long       idDomandaIscrizione ;
    private Integer    punteggio    ;
    private String     flFuoriTermine ;
    private Long       idTipoFrequenza ;
    private Double     isee         ;
    private Integer    ordinePreferenza ;
    private Long       idFasciaEta  ;
    private Long       idStatoScu   ;
    private Integer    ordinamento  ;
    private Long       idStepGraCon ;

    /**
     * Set the "idGraduatoria" field value
     * This field is mapped on the database column "id_graduatoria" ( type "int4", NotNull : true )
     * @param idGraduatoria
     */
	public void setIdGraduatoria(Long idGraduatoria) {
        this.idGraduatoria = idGraduatoria ;
    }

    /**
     * Get the "idGraduatoria" field value
     * This field is mapped on the database column "id_graduatoria" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdGraduatoria() {
        return this.idGraduatoria;
    }

    /**
     * Set the "idScuola" field value
     * This field is mapped on the database column "id_scuola" ( type "int4", NotNull : true )
     * @param idScuola
     */
    public void setIdScuola(Long idScuola) {
        this.idScuola = idScuola;
    }

    /**
     * Get the "idScuola" field value
     * This field is mapped on the database column "id_scuola" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdScuola() {
        return this.idScuola;
    }

    /**
     * Set the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @param idDomandaIscrizione
     */
    public void setIdDomandaIscrizione(Long idDomandaIscrizione) {
        this.idDomandaIscrizione = idDomandaIscrizione;
    }

    /**
     * Get the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdDomandaIscrizione() {
        return this.idDomandaIscrizione;
    }

    /**
     * Set the "punteggio" field value
     * This field is mapped on the database column "punteggio" ( type "int4", NotNull : false )
     * @param punteggio
     */
    public void setPunteggio(Integer punteggio) {
        this.punteggio = punteggio;
    }

    /**
     * Get the "punteggio" field value
     * This field is mapped on the database column "punteggio" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Integer getPunteggio() {
        return this.punteggio;
    }

    /**
     * Set the "flFuoriTermine" field value
     * This field is mapped on the database column "fl_fuori_termine" ( type "varchar", NotNull : true )
     * @param flFuoriTermine
     */
    public void setFlFuoriTermine(String flFuoriTermine) {
        this.flFuoriTermine = flFuoriTermine;
    }

    /**
     * Get the "flFuoriTermine" field value
     * This field is mapped on the database column "fl_fuori_termine" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlFuoriTermine() {
        return this.flFuoriTermine;
    }

    /**
     * Set the "idTipoFrequenza" field value
     * This field is mapped on the database column "id_tipo_frequenza" ( type "int4", NotNull : true )
     * @param idTipoFrequenza
     */
    public void setIdTipoFrequenza(Long idTipoFrequenza) {
        this.idTipoFrequenza = idTipoFrequenza;
    }

    /**
     * Get the "idTipoFrequenza" field value
     * This field is mapped on the database column "id_tipo_frequenza" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdTipoFrequenza() {
        return this.idTipoFrequenza;
    }

    /**
     * Set the "isee" field value
     * This field is mapped on the database column "isee" ( type "numeric", NotNull : false )
     * @param isee
     */
    public void setIsee(Double isee) {
        this.isee = isee;
    }

    /**
     * Get the "isee" field value
     * This field is mapped on the database column "isee" ( type "numeric", NotNull : false )
     * @return the field value
     */
    public Double getIsee() {
        return this.isee;
    }

    /**
     * Set the "ordinePreferenza" field value
     * This field is mapped on the database column "ordine_preferenza" ( type "int4", NotNull : true )
     * @param ordinePreferenza
     */
    public void setOrdinePreferenza(Integer ordinePreferenza) {
        this.ordinePreferenza = ordinePreferenza;
    }

    /**
     * Get the "ordinePreferenza" field value
     * This field is mapped on the database column "ordine_preferenza" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Integer getOrdinePreferenza() {
        return this.ordinePreferenza;
    }

    /**
     * Set the "idFasciaEta" field value
     * This field is mapped on the database column "id_fascia_eta" ( type "int4", NotNull : true )
     * @param idFasciaEta
     */
    public void setIdFasciaEta(Long idFasciaEta) {
        this.idFasciaEta = idFasciaEta;
    }

    /**
     * Get the "idFasciaEta" field value
     * This field is mapped on the database column "id_fascia_eta" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdFasciaEta() {
        return this.idFasciaEta;
    }

    /**
     * Set the "idStatoScu" field value
     * This field is mapped on the database column "id_stato_scu" ( type "int4", NotNull : true )
     * @param idStatoScu
     */
    public void setIdStatoScu(Long idStatoScu) {
        this.idStatoScu = idStatoScu;
    }

    /**
     * Get the "idStatoScu" field value
     * This field is mapped on the database column "id_stato_scu" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdStatoScu() {
        return this.idStatoScu;
    }

    /**
     * Set the "ordinamento" field value
     * This field is mapped on the database column "ordinamento" ( type "int4", NotNull : false )
     * @param ordinamento
     */
    public void setOrdinamento(Integer ordinamento) {
        this.ordinamento = ordinamento;
    }

    /**
     * Get the "ordinamento" field value
     * This field is mapped on the database column "ordinamento" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Integer getOrdinamento() {
        return this.ordinamento;
    }

    /**
     * Set the "idStepGraCon" field value
     * This field is mapped on the database column "id_step_gra_con" ( type "int4", NotNull : false )
     * @param idStepGraCon
     */
    public void setIdStepGraCon(Long idStepGraCon) {
        this.idStepGraCon = idStepGraCon;
    }

    /**
     * Get the "idStepGraCon" field value
     * This field is mapped on the database column "id_step_gra_con" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdStepGraCon() {
        return this.idStepGraCon;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idGraduatoria);
        sb.append("|");
        sb.append(idScuola);
        sb.append("|");
        sb.append(idDomandaIscrizione);
        sb.append("|");
        sb.append(punteggio);
        sb.append("|");
        sb.append(flFuoriTermine);
        sb.append("|");
        sb.append(idTipoFrequenza);
        sb.append("|");
        sb.append(isee);
        sb.append("|");
        sb.append(ordinePreferenza);
        sb.append("|");
        sb.append(idFasciaEta);
        sb.append("|");
        sb.append(idStatoScu);
        sb.append("|");
        sb.append(ordinamento);
        sb.append("|");
        sb.append(idStepGraCon);
        return sb.toString(); 
    } 

}
