/*
 * Java bean class for entity "iscritto_t_invio_acc"
 * Created on 2019-05-17 ( Date ISO 2019-05-17 - Time 12:52:46 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_invio_acc"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTInvioAcc implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_accettazione_rin, " +
		"  telefono, " +
		"  dt_invio_sise, " +
		"  dt_invio_scuola " +
		"from iscritto_t_invio_acc ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_invio_acc (" +
		"  id_accettazione_rin, " +
		"  telefono, " +
		"  dt_invio_sise, " +
		"  dt_invio_scuola " +
		") " +
		"values (" +
		"  :idAccettazioneRin, " +
		"  :telefono, " +
		"  :dtInvioSise, " +
		"  :dtInvioScuola " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_invio_acc where " +
		"  id_accettazione_rin = :idAccettazioneRin ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_invio_acc";

	//////////////////////////////////////////////////////////////////////


    private Long       idAccettazioneRin ; // Id or Primary Key

    private String     telefono     ;
    private Date       dtInvioSise  ;
    private Date       dtInvioScuola ;

    /**
     * Set the "idAccettazioneRin" field value
     * This field is mapped on the database column "id_accettazione_rin" ( type "int4", NotNull : true )
     * @param idAccettazioneRin
     */
	public void setIdAccettazioneRin(Long idAccettazioneRin) {
        this.idAccettazioneRin = idAccettazioneRin ;
    }

    /**
     * Get the "idAccettazioneRin" field value
     * This field is mapped on the database column "id_accettazione_rin" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdAccettazioneRin() {
        return this.idAccettazioneRin;
    }

    /**
     * Set the "telefono" field value
     * This field is mapped on the database column "telefono" ( type "varchar", NotNull : true )
     * @param telefono
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * Get the "telefono" field value
     * This field is mapped on the database column "telefono" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getTelefono() {
        return this.telefono;
    }

    /**
     * Set the "dtInvioSise" field value
     * This field is mapped on the database column "dt_invio_sise" ( type "timestamp", NotNull : false )
     * @param dtInvioSise
     */
    public void setDtInvioSise(Date dtInvioSise) {
        this.dtInvioSise = dtInvioSise;
    }

    /**
     * Get the "dtInvioSise" field value
     * This field is mapped on the database column "dt_invio_sise" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtInvioSise() {
        return this.dtInvioSise;
    }

    /**
     * Set the "dtInvioScuola" field value
     * This field is mapped on the database column "dt_invio_scuola" ( type "timestamp", NotNull : false )
     * @param dtInvioScuola
     */
    public void setDtInvioScuola(Date dtInvioScuola) {
        this.dtInvioScuola = dtInvioScuola;
    }

    /**
     * Get the "dtInvioScuola" field value
     * This field is mapped on the database column "dt_invio_scuola" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtInvioScuola() {
        return this.dtInvioScuola;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idAccettazioneRin);
        sb.append("|");
        sb.append(telefono);
        sb.append("|");
        sb.append(dtInvioSise);
        sb.append("|");
        sb.append(dtInvioScuola);
        return sb.toString(); 
    } 

}
