/*
 * Java bean class for entity "iscritto_r_lista_attesa"
 * Created on 2019-11-25 ( Date ISO 2019-11-25 - Time 14:11:49 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_r_lista_attesa"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoRListaAttesa implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_domanda_isc, " +
		"  id_anno_scolastico, " +
		"  scuola_lista " +
		"from iscritto_r_lista_attesa ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_r_lista_attesa (" +
		"  id_domanda_isc, " +
		"  id_anno_scolastico, " +
		"  scuola_lista " +
		") " +
		"values (" +
		"  :idDomandaIsc, " +
		"  :idAnnoScolastico, " +
		"  :scuolaLista " +
		")";

	//////////////////////////////////////////////////////////////////////


	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_r_lista_attesa";

	//////////////////////////////////////////////////////////////////////



    private Long       idDomandaIsc ;
    private Long       idAnnoScolastico ;
    private String     scuolaLista  ;


    /**
     * Set the "idDomandaIsc" field value
     * This field is mapped on the database column "id_domanda_isc" ( type "int4", NotNull : true )
     * @param idDomandaIsc
     */
    public void setIdDomandaIsc(Long idDomandaIsc) {
        this.idDomandaIsc = idDomandaIsc;
    }

    /**
     * Get the "idDomandaIsc" field value
     * This field is mapped on the database column "id_domanda_isc" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdDomandaIsc() {
        return this.idDomandaIsc;
    }

    /**
     * Set the "idAnnoScolastico" field value
     * This field is mapped on the database column "id_anno_scolastico" ( type "int4", NotNull : true )
     * @param idAnnoScolastico
     */
    public void setIdAnnoScolastico(Long idAnnoScolastico) {
        this.idAnnoScolastico = idAnnoScolastico;
    }

    /**
     * Get the "idAnnoScolastico" field value
     * This field is mapped on the database column "id_anno_scolastico" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdAnnoScolastico() {
        return this.idAnnoScolastico;
    }

    /**
     * Set the "scuolaLista" field value
     * This field is mapped on the database column "scuola_lista" ( type "varchar", NotNull : true )
     * @param scuolaLista
     */
    public void setScuolaLista(String scuolaLista) {
        this.scuolaLista = scuolaLista;
    }

    /**
     * Get the "scuolaLista" field value
     * This field is mapped on the database column "scuola_lista" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getScuolaLista() {
        return this.scuolaLista;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idDomandaIsc);
        sb.append("|");
        sb.append(idAnnoScolastico);
        sb.append("|");
        sb.append(scuolaLista);
        return sb.toString(); 
    } 

}
