/*
 * Java bean class for entity "iscritto_t_allegato_red"
 * Created on 2019-05-17 ( Date ISO 2019-05-17 - Time 12:52:45 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_allegato_red"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTAllegatoRed implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_allegato, " +
		"  id_tipo_allegato, " +
		"  data_inizio_validita, " +
		"  data_fine_validita " +
		"from iscritto_t_allegato_red ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_allegato_red (" +
		"  id_allegato, " +
		"  id_tipo_allegato, " +
		"  data_inizio_validita, " +
		"  data_fine_validita " +
		") " +
		"values (" +
		"  :idAllegato, " +
		"  :idTipoAllegato, " +
		"  :dataInizioValidita, " +
		"  :dataFineValidita " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_allegato_red where " +
		"  id_allegato = :idAllegato and " +
		"  data_inizio_validita = :dataInizioValidita ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_allegato_red";

	//////////////////////////////////////////////////////////////////////


    private Long       idAllegato   ; // Id or Primary Key
    private Date       dataInizioValidita ; // Id or Primary Key

    private Long       idTipoAllegato ;
    private Date       dataFineValidita ;

    /**
     * Set the "idAllegato" field value
     * This field is mapped on the database column "id_allegato" ( type "int4", NotNull : true )
     * @param idAllegato
     */
	public void setIdAllegato(Long idAllegato) {
        this.idAllegato = idAllegato ;
    }

    /**
     * Get the "idAllegato" field value
     * This field is mapped on the database column "id_allegato" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdAllegato() {
        return this.idAllegato;
    }
    /**
     * Set the "dataInizioValidita" field value
     * This field is mapped on the database column "data_inizio_validita" ( type "timestamp", NotNull : true )
     * @param dataInizioValidita
     */
	public void setDataInizioValidita(Date dataInizioValidita) {
        this.dataInizioValidita = dataInizioValidita ;
    }

    /**
     * Get the "dataInizioValidita" field value
     * This field is mapped on the database column "data_inizio_validita" ( type "timestamp", NotNull : true )
     * @return the field value
     */
	public Date getDataInizioValidita() {
        return this.dataInizioValidita;
    }

    /**
     * Set the "idTipoAllegato" field value
     * This field is mapped on the database column "id_tipo_allegato" ( type "int4", NotNull : false )
     * @param idTipoAllegato
     */
    public void setIdTipoAllegato(Long idTipoAllegato) {
        this.idTipoAllegato = idTipoAllegato;
    }

    /**
     * Get the "idTipoAllegato" field value
     * This field is mapped on the database column "id_tipo_allegato" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdTipoAllegato() {
        return this.idTipoAllegato;
    }

    /**
     * Set the "dataFineValidita" field value
     * This field is mapped on the database column "data_fine_validita" ( type "timestamp", NotNull : false )
     * @param dataFineValidita
     */
    public void setDataFineValidita(Date dataFineValidita) {
        this.dataFineValidita = dataFineValidita;
    }

    /**
     * Get the "dataFineValidita" field value
     * This field is mapped on the database column "data_fine_validita" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDataFineValidita() {
        return this.dataFineValidita;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idAllegato);
        sb.append("|");
        sb.append(idTipoAllegato);
        sb.append("|");
        sb.append(dataInizioValidita);
        sb.append("|");
        sb.append(dataFineValidita);
        return sb.toString(); 
    } 

}
