/*
 * Java bean class for entity "iscritto_t_invio_sms"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_invio_sms"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTInvioSms implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_invio_sms, " +
		"  testo, " +
		"  id_domanda_iscrizione, " +
		"  dt_inserimento, " +
		"  dt_invio, " +
		"  esito, " +
		"  telefono " +
		"from iscritto_t_invio_sms ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_invio_sms (" +
		"  id_invio_sms, " +
		"  testo, " +
		"  id_domanda_iscrizione, " +
		"  dt_inserimento, " +
		"  dt_invio, " +
		"  esito, " +
		"  telefono " +
		") " +
		"values (" +
		"  :idInvioSms, " +
		"  :testo, " +
		"  :idDomandaIscrizione, " +
		"  :dtInserimento, " +
		"  :dtInvio, " +
		"  :esito, " +
		"  :telefono " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_invio_sms where " +
		"  id_invio_sms = :idInvioSms ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_invio_sms";

	//////////////////////////////////////////////////////////////////////


    private Long       idInvioSms   ; // Id or Primary Key

    private String     testo        ;
    private Long       idDomandaIscrizione ;
    private Date       dtInserimento ;
    private Date       dtInvio      ;
    private String     esito        ;
    private String     telefono     ;

    /**
     * Set the "idInvioSms" field value
     * This field is mapped on the database column "id_invio_sms" ( type "int4", NotNull : true )
     * @param idInvioSms
     */
	public void setIdInvioSms(Long idInvioSms) {
        this.idInvioSms = idInvioSms ;
    }

    /**
     * Get the "idInvioSms" field value
     * This field is mapped on the database column "id_invio_sms" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdInvioSms() {
        return this.idInvioSms;
    }

    /**
     * Set the "testo" field value
     * This field is mapped on the database column "testo" ( type "varchar", NotNull : true )
     * @param testo
     */
    public void setTesto(String testo) {
        this.testo = testo;
    }

    /**
     * Get the "testo" field value
     * This field is mapped on the database column "testo" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getTesto() {
        return this.testo;
    }

    /**
     * Set the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @param idDomandaIscrizione
     */
    public void setIdDomandaIscrizione(Long idDomandaIscrizione) {
        this.idDomandaIscrizione = idDomandaIscrizione;
    }

    /**
     * Get the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdDomandaIscrizione() {
        return this.idDomandaIscrizione;
    }

    /**
     * Set the "dtInserimento" field value
     * This field is mapped on the database column "dt_inserimento" ( type "timestamp", NotNull : true )
     * @param dtInserimento
     */
    public void setDtInserimento(Date dtInserimento) {
        this.dtInserimento = dtInserimento;
    }

    /**
     * Get the "dtInserimento" field value
     * This field is mapped on the database column "dt_inserimento" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtInserimento() {
        return this.dtInserimento;
    }

    /**
     * Set the "dtInvio" field value
     * This field is mapped on the database column "dt_invio" ( type "timestamp", NotNull : false )
     * @param dtInvio
     */
    public void setDtInvio(Date dtInvio) {
        this.dtInvio = dtInvio;
    }

    /**
     * Get the "dtInvio" field value
     * This field is mapped on the database column "dt_invio" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtInvio() {
        return this.dtInvio;
    }

    /**
     * Set the "esito" field value
     * This field is mapped on the database column "esito" ( type "varchar", NotNull : false )
     * @param esito
     */
    public void setEsito(String esito) {
        this.esito = esito;
    }

    /**
     * Get the "esito" field value
     * This field is mapped on the database column "esito" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getEsito() {
        return this.esito;
    }

    /**
     * Set the "telefono" field value
     * This field is mapped on the database column "telefono" ( type "varchar", NotNull : true )
     * @param telefono
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * Get the "telefono" field value
     * This field is mapped on the database column "telefono" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getTelefono() {
        return this.telefono;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idInvioSms);
        sb.append("|");
        sb.append(testo);
        sb.append("|");
        sb.append(idDomandaIscrizione);
        sb.append("|");
        sb.append(dtInserimento);
        sb.append("|");
        sb.append(dtInvio);
        sb.append("|");
        sb.append(esito);
        sb.append("|");
        sb.append(telefono);
        return sb.toString(); 
    } 

}
