/*
 * Java bean class for entity "iscritto_t_punteggio"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_punteggio"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTPunteggio implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_punteggio, " +
		"  punti, " +
		"  dt_inizio_validita, " +
		"  dt_fine_validita, " +
		"  id_condizione_punteggio " +
		"from iscritto_t_punteggio ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_punteggio (" +
		"  id_punteggio, " +
		"  punti, " +
		"  dt_inizio_validita, " +
		"  dt_fine_validita, " +
		"  id_condizione_punteggio " +
		") " +
		"values (" +
		"  :idPunteggio, " +
		"  :punti, " +
		"  :dtInizioValidita, " +
		"  :dtFineValidita, " +
		"  :idCondizionePunteggio " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_punteggio where " +
		"  id_punteggio = :idPunteggio ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_punteggio";

	//////////////////////////////////////////////////////////////////////


    private Long       idPunteggio  ; // Id or Primary Key

    private Integer    punti        ;
    private Date       dtInizioValidita ;
    private Date       dtFineValidita ;
    private Long       idCondizionePunteggio ;

    /**
     * Set the "idPunteggio" field value
     * This field is mapped on the database column "id_punteggio" ( type "int4", NotNull : true )
     * @param idPunteggio
     */
	public void setIdPunteggio(Long idPunteggio) {
        this.idPunteggio = idPunteggio ;
    }

    /**
     * Get the "idPunteggio" field value
     * This field is mapped on the database column "id_punteggio" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdPunteggio() {
        return this.idPunteggio;
    }

    /**
     * Set the "punti" field value
     * This field is mapped on the database column "punti" ( type "int4", NotNull : true )
     * @param punti
     */
    public void setPunti(Integer punti) {
        this.punti = punti;
    }

    /**
     * Get the "punti" field value
     * This field is mapped on the database column "punti" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Integer getPunti() {
        return this.punti;
    }

    /**
     * Set the "dtInizioValidita" field value
     * This field is mapped on the database column "dt_inizio_validita" ( type "timestamp", NotNull : true )
     * @param dtInizioValidita
     */
    public void setDtInizioValidita(Date dtInizioValidita) {
        this.dtInizioValidita = dtInizioValidita;
    }

    /**
     * Get the "dtInizioValidita" field value
     * This field is mapped on the database column "dt_inizio_validita" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtInizioValidita() {
        return this.dtInizioValidita;
    }

    /**
     * Set the "dtFineValidita" field value
     * This field is mapped on the database column "dt_fine_validita" ( type "timestamp", NotNull : false )
     * @param dtFineValidita
     */
    public void setDtFineValidita(Date dtFineValidita) {
        this.dtFineValidita = dtFineValidita;
    }

    /**
     * Get the "dtFineValidita" field value
     * This field is mapped on the database column "dt_fine_validita" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtFineValidita() {
        return this.dtFineValidita;
    }

    /**
     * Set the "idCondizionePunteggio" field value
     * This field is mapped on the database column "id_condizione_punteggio" ( type "int4", NotNull : true )
     * @param idCondizionePunteggio
     */
    public void setIdCondizionePunteggio(Long idCondizionePunteggio) {
        this.idCondizionePunteggio = idCondizionePunteggio;
    }

    /**
     * Get the "idCondizionePunteggio" field value
     * This field is mapped on the database column "id_condizione_punteggio" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdCondizionePunteggio() {
        return this.idCondizionePunteggio;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idPunteggio);
        sb.append("|");
        sb.append(punti);
        sb.append("|");
        sb.append(dtInizioValidita);
        sb.append("|");
        sb.append(dtFineValidita);
        sb.append("|");
        sb.append(idCondizionePunteggio);
        return sb.toString(); 
    } 

}
