/*
 * Java bean class for entity "iscritto_t_attivita"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_attivita"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTAttivita implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_attivita, " +
		"  cod_attivita, " +
		"  descrizione, " +
		"  id_funzione, " +
		"  link, " +
		"  ordinamento " +
		"from iscritto_t_attivita ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_attivita (" +
		"  id_attivita, " +
		"  cod_attivita, " +
		"  descrizione, " +
		"  id_funzione, " +
		"  link, " +
		"  ordinamento " +
		") " +
		"values (" +
		"  :idAttivita, " +
		"  :codAttivita, " +
		"  :descrizione, " +
		"  :idFunzione, " +
		"  :link, " +
		"  :ordinamento " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_attivita where " +
		"  id_attivita = :idAttivita ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_attivita";

	//////////////////////////////////////////////////////////////////////


    private Long       idAttivita   ; // Id or Primary Key

    private String     codAttivita  ;
    private String     descrizione  ;
    private Long       idFunzione   ;
    private String     link         ;
    private Integer    ordinamento  ;

    /**
     * Set the "idAttivita" field value
     * This field is mapped on the database column "id_attivita" ( type "int4", NotNull : true )
     * @param idAttivita
     */
	public void setIdAttivita(Long idAttivita) {
        this.idAttivita = idAttivita ;
    }

    /**
     * Get the "idAttivita" field value
     * This field is mapped on the database column "id_attivita" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdAttivita() {
        return this.idAttivita;
    }

    /**
     * Set the "codAttivita" field value
     * This field is mapped on the database column "cod_attivita" ( type "varchar", NotNull : true )
     * @param codAttivita
     */
    public void setCodAttivita(String codAttivita) {
        this.codAttivita = codAttivita;
    }

    /**
     * Get the "codAttivita" field value
     * This field is mapped on the database column "cod_attivita" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodAttivita() {
        return this.codAttivita;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }

    /**
     * Set the "idFunzione" field value
     * This field is mapped on the database column "id_funzione" ( type "int4", NotNull : true )
     * @param idFunzione
     */
    public void setIdFunzione(Long idFunzione) {
        this.idFunzione = idFunzione;
    }

    /**
     * Get the "idFunzione" field value
     * This field is mapped on the database column "id_funzione" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdFunzione() {
        return this.idFunzione;
    }

    /**
     * Set the "link" field value
     * This field is mapped on the database column "link" ( type "varchar", NotNull : false )
     * @param link
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * Get the "link" field value
     * This field is mapped on the database column "link" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getLink() {
        return this.link;
    }

    /**
     * Set the "ordinamento" field value
     * This field is mapped on the database column "ordinamento" ( type "int4", NotNull : false )
     * @param ordinamento
     */
    public void setOrdinamento(Integer ordinamento) {
        this.ordinamento = ordinamento;
    }

    /**
     * Get the "ordinamento" field value
     * This field is mapped on the database column "ordinamento" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Integer getOrdinamento() {
        return this.ordinamento;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idAttivita);
        sb.append("|");
        sb.append(codAttivita);
        sb.append("|");
        sb.append(descrizione);
        sb.append("|");
        sb.append(idFunzione);
        sb.append("|");
        sb.append(link);
        sb.append("|");
        sb.append(ordinamento);
        return sb.toString(); 
    } 

}
