/*
 * Java bean class for entity "iscritto_d_ordine_scuola"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_ordine_scuola"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDOrdineScuola implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_ordine_scuola, " +
		"  descrizione, " +
		"  cod_ordine_scuola " +
		"from iscritto_d_ordine_scuola ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_ordine_scuola (" +
		"  id_ordine_scuola, " +
		"  descrizione, " +
		"  cod_ordine_scuola " +
		") " +
		"values (" +
		"  :idOrdineScuola, " +
		"  :descrizione, " +
		"  :codOrdineScuola " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_ordine_scuola where " +
		"  id_ordine_scuola = :idOrdineScuola ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_ordine_scuola";

	//////////////////////////////////////////////////////////////////////


    private Long       idOrdineScuola ; // Id or Primary Key

    private String     descrizione  ;
    private String     codOrdineScuola ;

    /**
     * Set the "idOrdineScuola" field value
     * This field is mapped on the database column "id_ordine_scuola" ( type "int4", NotNull : true )
     * @param idOrdineScuola
     */
	public void setIdOrdineScuola(Long idOrdineScuola) {
        this.idOrdineScuola = idOrdineScuola ;
    }

    /**
     * Get the "idOrdineScuola" field value
     * This field is mapped on the database column "id_ordine_scuola" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdOrdineScuola() {
        return this.idOrdineScuola;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }

    /**
     * Set the "codOrdineScuola" field value
     * This field is mapped on the database column "cod_ordine_scuola" ( type "varchar", NotNull : true )
     * @param codOrdineScuola
     */
    public void setCodOrdineScuola(String codOrdineScuola) {
        this.codOrdineScuola = codOrdineScuola;
    }

    /**
     * Get the "codOrdineScuola" field value
     * This field is mapped on the database column "cod_ordine_scuola" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodOrdineScuola() {
        return this.codOrdineScuola;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idOrdineScuola);
        sb.append("|");
        sb.append(descrizione);
        sb.append("|");
        sb.append(codOrdineScuola);
        return sb.toString(); 
    } 

}
