/*
 * Java bean class for entity "iscritto_t_autonomo"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_autonomo"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTAutonomo implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_condizione_occupazionale, " +
		"  partitaiva_cf, " +
		"  comune_lavoro, " +
		"  indirizzo_lavoro, " +
		"  provincia_lavoro " +
		"from iscritto_t_autonomo ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_autonomo (" +
		"  id_condizione_occupazionale, " +
		"  partitaiva_cf, " +
		"  comune_lavoro, " +
		"  indirizzo_lavoro, " +
		"  provincia_lavoro " +
		") " +
		"values (" +
		"  :idCondizioneOccupazionale, " +
		"  :partitaivaCf, " +
		"  :comuneLavoro, " +
		"  :indirizzoLavoro, " +
		"  :provinciaLavoro " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_autonomo where " +
		"  id_condizione_occupazionale = :idCondizioneOccupazionale ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_autonomo";

	//////////////////////////////////////////////////////////////////////


    private Long       idCondizioneOccupazionale ; // Id or Primary Key

    private String     partitaivaCf ;
    private String     comuneLavoro ;
    private String     indirizzoLavoro ;
    private String     provinciaLavoro ;

    /**
     * Set the "idCondizioneOccupazionale" field value
     * This field is mapped on the database column "id_condizione_occupazionale" ( type "int4", NotNull : true )
     * @param idCondizioneOccupazionale
     */
	public void setIdCondizioneOccupazionale(Long idCondizioneOccupazionale) {
        this.idCondizioneOccupazionale = idCondizioneOccupazionale ;
    }

    /**
     * Get the "idCondizioneOccupazionale" field value
     * This field is mapped on the database column "id_condizione_occupazionale" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdCondizioneOccupazionale() {
        return this.idCondizioneOccupazionale;
    }

    /**
     * Set the "partitaivaCf" field value
     * This field is mapped on the database column "partitaiva_cf" ( type "varchar", NotNull : true )
     * @param partitaivaCf
     */
    public void setPartitaivaCf(String partitaivaCf) {
        this.partitaivaCf = partitaivaCf;
    }

    /**
     * Get the "partitaivaCf" field value
     * This field is mapped on the database column "partitaiva_cf" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getPartitaivaCf() {
        return this.partitaivaCf;
    }

    /**
     * Set the "comuneLavoro" field value
     * This field is mapped on the database column "comune_lavoro" ( type "varchar", NotNull : true )
     * @param comuneLavoro
     */
    public void setComuneLavoro(String comuneLavoro) {
        this.comuneLavoro = comuneLavoro;
    }

    /**
     * Get the "comuneLavoro" field value
     * This field is mapped on the database column "comune_lavoro" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getComuneLavoro() {
        return this.comuneLavoro;
    }

    /**
     * Set the "indirizzoLavoro" field value
     * This field is mapped on the database column "indirizzo_lavoro" ( type "varchar", NotNull : true )
     * @param indirizzoLavoro
     */
    public void setIndirizzoLavoro(String indirizzoLavoro) {
        this.indirizzoLavoro = indirizzoLavoro;
    }

    /**
     * Get the "indirizzoLavoro" field value
     * This field is mapped on the database column "indirizzo_lavoro" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getIndirizzoLavoro() {
        return this.indirizzoLavoro;
    }

    /**
     * Set the "provinciaLavoro" field value
     * This field is mapped on the database column "provincia_lavoro" ( type "varchar", NotNull : false )
     * @param provinciaLavoro
     */
    public void setProvinciaLavoro(String provinciaLavoro) {
        this.provinciaLavoro = provinciaLavoro;
    }

    /**
     * Get the "provinciaLavoro" field value
     * This field is mapped on the database column "provincia_lavoro" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getProvinciaLavoro() {
        return this.provinciaLavoro;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idCondizioneOccupazionale);
        sb.append("|");
        sb.append(partitaivaCf);
        sb.append("|");
        sb.append(comuneLavoro);
        sb.append("|");
        sb.append(indirizzoLavoro);
        sb.append("|");
        sb.append(provinciaLavoro);
        return sb.toString(); 
    } 

}
