/*
 * Java bean class for entity "iscritto_t_trasferimento"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:24 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_trasferimento"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTTrasferimento implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_domanda_iscrizione, " +
		"  dt_cambio_residenza, " +
		"  indirizzo_residenza_pre, " +
		"  indirizzo_residenza_new, " +
		"  indirizzo_nido_prov, " +
		"  frequenza_dal, " +
		"  frequenza_al " +
		"from iscritto_t_trasferimento ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_trasferimento (" +
		"  id_domanda_iscrizione, " +
		"  dt_cambio_residenza, " +
		"  indirizzo_residenza_pre, " +
		"  indirizzo_residenza_new, " +
		"  indirizzo_nido_prov, " +
		"  frequenza_dal, " +
		"  frequenza_al " +
		") " +
		"values (" +
		"  :idDomandaIscrizione, " +
		"  :dtCambioResidenza, " +
		"  :indirizzoResidenzaPre, " +
		"  :indirizzoResidenzaNew, " +
		"  :indirizzoNidoProv, " +
		"  :frequenzaDal, " +
		"  :frequenzaAl " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_trasferimento where " +
		"  id_domanda_iscrizione = :idDomandaIscrizione ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_trasferimento";

	//////////////////////////////////////////////////////////////////////


    private Long       idDomandaIscrizione ; // Id or Primary Key

    private Date       dtCambioResidenza ;
    private String     indirizzoResidenzaPre ;
    private String     indirizzoResidenzaNew ;
    private String     indirizzoNidoProv ;
    private Date       frequenzaDal ;
    private Date       frequenzaAl  ;

    /**
     * Set the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @param idDomandaIscrizione
     */
	public void setIdDomandaIscrizione(Long idDomandaIscrizione) {
        this.idDomandaIscrizione = idDomandaIscrizione ;
    }

    /**
     * Get the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdDomandaIscrizione() {
        return this.idDomandaIscrizione;
    }

    /**
     * Set the "dtCambioResidenza" field value
     * This field is mapped on the database column "dt_cambio_residenza" ( type "timestamp", NotNull : true )
     * @param dtCambioResidenza
     */
    public void setDtCambioResidenza(Date dtCambioResidenza) {
        this.dtCambioResidenza = dtCambioResidenza;
    }

    /**
     * Get the "dtCambioResidenza" field value
     * This field is mapped on the database column "dt_cambio_residenza" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtCambioResidenza() {
        return this.dtCambioResidenza;
    }

    /**
     * Set the "indirizzoResidenzaPre" field value
     * This field is mapped on the database column "indirizzo_residenza_pre" ( type "varchar", NotNull : true )
     * @param indirizzoResidenzaPre
     */
    public void setIndirizzoResidenzaPre(String indirizzoResidenzaPre) {
        this.indirizzoResidenzaPre = indirizzoResidenzaPre;
    }

    /**
     * Get the "indirizzoResidenzaPre" field value
     * This field is mapped on the database column "indirizzo_residenza_pre" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getIndirizzoResidenzaPre() {
        return this.indirizzoResidenzaPre;
    }

    /**
     * Set the "indirizzoResidenzaNew" field value
     * This field is mapped on the database column "indirizzo_residenza_new" ( type "varchar", NotNull : true )
     * @param indirizzoResidenzaNew
     */
    public void setIndirizzoResidenzaNew(String indirizzoResidenzaNew) {
        this.indirizzoResidenzaNew = indirizzoResidenzaNew;
    }

    /**
     * Get the "indirizzoResidenzaNew" field value
     * This field is mapped on the database column "indirizzo_residenza_new" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getIndirizzoResidenzaNew() {
        return this.indirizzoResidenzaNew;
    }

    /**
     * Set the "indirizzoNidoProv" field value
     * This field is mapped on the database column "indirizzo_nido_prov" ( type "varchar", NotNull : true )
     * @param indirizzoNidoProv
     */
    public void setIndirizzoNidoProv(String indirizzoNidoProv) {
        this.indirizzoNidoProv = indirizzoNidoProv;
    }

    /**
     * Get the "indirizzoNidoProv" field value
     * This field is mapped on the database column "indirizzo_nido_prov" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getIndirizzoNidoProv() {
        return this.indirizzoNidoProv;
    }

    /**
     * Set the "frequenzaDal" field value
     * This field is mapped on the database column "frequenza_dal" ( type "timestamp", NotNull : true )
     * @param frequenzaDal
     */
    public void setFrequenzaDal(Date frequenzaDal) {
        this.frequenzaDal = frequenzaDal;
    }

    /**
     * Get the "frequenzaDal" field value
     * This field is mapped on the database column "frequenza_dal" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getFrequenzaDal() {
        return this.frequenzaDal;
    }

    /**
     * Set the "frequenzaAl" field value
     * This field is mapped on the database column "frequenza_al" ( type "timestamp", NotNull : true )
     * @param frequenzaAl
     */
    public void setFrequenzaAl(Date frequenzaAl) {
        this.frequenzaAl = frequenzaAl;
    }

    /**
     * Get the "frequenzaAl" field value
     * This field is mapped on the database column "frequenza_al" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getFrequenzaAl() {
        return this.frequenzaAl;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idDomandaIscrizione);
        sb.append("|");
        sb.append(dtCambioResidenza);
        sb.append("|");
        sb.append(indirizzoResidenzaPre);
        sb.append("|");
        sb.append(indirizzoResidenzaNew);
        sb.append("|");
        sb.append(indirizzoNidoProv);
        sb.append("|");
        sb.append(frequenzaDal);
        sb.append("|");
        sb.append(frequenzaAl);
        return sb.toString(); 
    } 

}
