/*
 * Java bean class for entity "iscritto_t_allegato_wrk"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_allegato_wrk"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTAllegatoWrk implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  documento, " +
		"  protocollo, " +
		"  id_allegato, " +
		"  id_anagrafica_soggetto, " +
		"  id_tipo_allegato, " +
		"  data_inserimento, " +
		"  nome_file, " +
		"  mime_type " +
		"from iscritto_t_allegato_wrk ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_allegato_wrk (" +
		"  documento, " +
		"  protocollo, " +
		"  id_allegato, " +
		"  id_anagrafica_soggetto, " +
		"  id_tipo_allegato, " +
		"  data_inserimento, " +
		"  nome_file, " +
		"  mime_type " +
		") " +
		"values (" +
		"  :documento, " +
		"  :protocollo, " +
		"  :idAllegato, " +
		"  :idAnagraficaSoggetto, " +
		"  :idTipoAllegato, " +
		"  :dataInserimento, " +
		"  :nomeFile, " +
		"  :mimeType " +
		")";

	//////////////////////////////////////////////////////////////////////


	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_allegato_wrk";

	//////////////////////////////////////////////////////////////////////



    private byte[]     documento    ;
    private String     protocollo   ;
    private Long       idAllegato   ;
    private Long       idAnagraficaSoggetto ;
    private Long       idTipoAllegato ;
    private Date       dataInserimento ;
    private String     nomeFile     ;
    private String     mimeType     ;


    /**
     * Set the "documento" field value
     * This field is mapped on the database column "documento" ( type "bytea", NotNull : false )
     * @param documento
     */
    public void setDocumento(byte[] documento) {
        this.documento = documento;
    }

    /**
     * Get the "documento" field value
     * This field is mapped on the database column "documento" ( type "bytea", NotNull : false )
     * @return the field value
     */
    public byte[] getDocumento() {
        return this.documento;
    }

    /**
     * Set the "protocollo" field value
     * This field is mapped on the database column "protocollo" ( type "varchar", NotNull : false )
     * @param protocollo
     */
    public void setProtocollo(String protocollo) {
        this.protocollo = protocollo;
    }

    /**
     * Get the "protocollo" field value
     * This field is mapped on the database column "protocollo" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getProtocollo() {
        return this.protocollo;
    }

    /**
     * Set the "idAllegato" field value
     * This field is mapped on the database column "id_allegato" ( type "int4", NotNull : false )
     * @param idAllegato
     */
    public void setIdAllegato(Long idAllegato) {
        this.idAllegato = idAllegato;
    }

    /**
     * Get the "idAllegato" field value
     * This field is mapped on the database column "id_allegato" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdAllegato() {
        return this.idAllegato;
    }

    /**
     * Set the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : false )
     * @param idAnagraficaSoggetto
     */
    public void setIdAnagraficaSoggetto(Long idAnagraficaSoggetto) {
        this.idAnagraficaSoggetto = idAnagraficaSoggetto;
    }

    /**
     * Get the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdAnagraficaSoggetto() {
        return this.idAnagraficaSoggetto;
    }

    /**
     * Set the "idTipoAllegato" field value
     * This field is mapped on the database column "id_tipo_allegato" ( type "int4", NotNull : false )
     * @param idTipoAllegato
     */
    public void setIdTipoAllegato(Long idTipoAllegato) {
        this.idTipoAllegato = idTipoAllegato;
    }

    /**
     * Get the "idTipoAllegato" field value
     * This field is mapped on the database column "id_tipo_allegato" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdTipoAllegato() {
        return this.idTipoAllegato;
    }

    /**
     * Set the "dataInserimento" field value
     * This field is mapped on the database column "data_inserimento" ( type "timestamp", NotNull : false )
     * @param dataInserimento
     */
    public void setDataInserimento(Date dataInserimento) {
        this.dataInserimento = dataInserimento;
    }

    /**
     * Get the "dataInserimento" field value
     * This field is mapped on the database column "data_inserimento" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDataInserimento() {
        return this.dataInserimento;
    }

    /**
     * Set the "nomeFile" field value
     * This field is mapped on the database column "nome_file" ( type "varchar", NotNull : false )
     * @param nomeFile
     */
    public void setNomeFile(String nomeFile) {
        this.nomeFile = nomeFile;
    }

    /**
     * Get the "nomeFile" field value
     * This field is mapped on the database column "nome_file" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getNomeFile() {
        return this.nomeFile;
    }

    /**
     * Set the "mimeType" field value
     * This field is mapped on the database column "mime_type" ( type "varchar", NotNull : false )
     * @param mimeType
     */
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    /**
     * Get the "mimeType" field value
     * This field is mapped on the database column "mime_type" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getMimeType() {
        return this.mimeType;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        // attribute 'documento' not usable (type = byte[])
        sb.append(protocollo);
        sb.append("|");
        sb.append(idAllegato);
        sb.append("|");
        sb.append(idAnagraficaSoggetto);
        sb.append("|");
        sb.append(idTipoAllegato);
        sb.append("|");
        sb.append(dataInserimento);
        sb.append("|");
        sb.append(nomeFile);
        sb.append("|");
        sb.append(mimeType);
        return sb.toString(); 
    } 

}
