/*
 * Java bean class for entity "iscritto_t_log_errore_domanda"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_log_errore_domanda"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTLogErroreDomanda implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  data_inserimento, " +
		"  codice_fiscale_operatore, " +
		"  dettaglio_errore, " +
		"  json_domanda " +
		"from iscritto_t_log_errore_domanda ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_log_errore_domanda (" +
		"  data_inserimento, " +
		"  codice_fiscale_operatore, " +
		"  dettaglio_errore, " +
		"  json_domanda " +
		") " +
		"values (" +
		"  :dataInserimento, " +
		"  :codiceFiscaleOperatore, " +
		"  :dettaglioErrore, " +
		"  :jsonDomanda " +
		")";

	//////////////////////////////////////////////////////////////////////


	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_log_errore_domanda";

	//////////////////////////////////////////////////////////////////////



    private Date       dataInserimento ;
    private String     codiceFiscaleOperatore ;
    private String     dettaglioErrore ;
    private String     jsonDomanda  ;


    /**
     * Set the "dataInserimento" field value
     * This field is mapped on the database column "data_inserimento" ( type "timestamp", NotNull : true )
     * @param dataInserimento
     */
    public void setDataInserimento(Date dataInserimento) {
        this.dataInserimento = dataInserimento;
    }

    /**
     * Get the "dataInserimento" field value
     * This field is mapped on the database column "data_inserimento" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDataInserimento() {
        return this.dataInserimento;
    }

    /**
     * Set the "codiceFiscaleOperatore" field value
     * This field is mapped on the database column "codice_fiscale_operatore" ( type "varchar", NotNull : false )
     * @param codiceFiscaleOperatore
     */
    public void setCodiceFiscaleOperatore(String codiceFiscaleOperatore) {
        this.codiceFiscaleOperatore = codiceFiscaleOperatore;
    }

    /**
     * Get the "codiceFiscaleOperatore" field value
     * This field is mapped on the database column "codice_fiscale_operatore" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getCodiceFiscaleOperatore() {
        return this.codiceFiscaleOperatore;
    }

    /**
     * Set the "dettaglioErrore" field value
     * This field is mapped on the database column "dettaglio_errore" ( type "text", NotNull : false )
     * @param dettaglioErrore
     */
    public void setDettaglioErrore(String dettaglioErrore) {
        this.dettaglioErrore = dettaglioErrore;
    }

    /**
     * Get the "dettaglioErrore" field value
     * This field is mapped on the database column "dettaglio_errore" ( type "text", NotNull : false )
     * @return the field value
     */
    public String getDettaglioErrore() {
        return this.dettaglioErrore;
    }

    /**
     * Set the "jsonDomanda" field value
     * This field is mapped on the database column "json_domanda" ( type "bytea", NotNull : false )
     * @param jsonDomanda
     */
    public void setJsonDomanda(String jsonDomanda) {
        this.jsonDomanda = jsonDomanda;
    }

    /**
     * Get the "jsonDomanda" field value
     * This field is mapped on the database column "json_domanda" ( type "bytea", NotNull : false )
     * @return the field value
     */
    public String getJsonDomanda() {
        return this.jsonDomanda;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(dataInserimento);
        sb.append("|");
        sb.append(codiceFiscaleOperatore);
        sb.append("|");
        sb.append(dettaglioErrore);
        sb.append("|");
        sb.append(jsonDomanda);
        return sb.toString(); 
    } 

}
