/*
 * Java bean class for entity "iscritto_t_parametri_generali"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_parametri_generali"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTParametriGenerali implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  cd_parametro, " +
		"  s_descrizione, " +
		"  s_valore, " +
		"  n_valore, " +
		"  d_valore, " +
		"  s_tipo_dato, " +
		"  b_loglev1, " +
		"  b_loglev2, " +
		"  b_loglev3, " +
		"  b_loglev4 " +
		"from iscritto_t_parametri_generali ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_parametri_generali (" +
		"  cd_parametro, " +
		"  s_descrizione, " +
		"  s_valore, " +
		"  n_valore, " +
		"  d_valore, " +
		"  s_tipo_dato, " +
		"  b_loglev1, " +
		"  b_loglev2, " +
		"  b_loglev3, " +
		"  b_loglev4 " +
		") " +
		"values (" +
		"  :cdParametro, " +
		"  :sDescrizione, " +
		"  :sValore, " +
		"  :nValore, " +
		"  :dValore, " +
		"  :sTipoDato, " +
		"  :bLoglev1, " +
		"  :bLoglev2, " +
		"  :bLoglev3, " +
		"  :bLoglev4 " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_parametri_generali where " +
		"  cd_parametro = :cdParametro ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_parametri_generali";

	//////////////////////////////////////////////////////////////////////


    private String     cdParametro  ; // Id or Primary Key

    private String     sDescrizione ;
    private String     sValore      ;
    private Long       nValore      ;
    private Date       dValore      ;
    private String     sTipoDato    ;
    private Boolean    bLoglev1     ;
    private Boolean    bLoglev2     ;
    private Boolean    bLoglev3     ;
    private Boolean    bLoglev4     ;

    /**
     * Set the "cdParametro" field value
     * This field is mapped on the database column "cd_parametro" ( type "varchar", NotNull : true )
     * @param cdParametro
     */
	public void setCdParametro(String cdParametro) {
        this.cdParametro = cdParametro ;
    }

    /**
     * Get the "cdParametro" field value
     * This field is mapped on the database column "cd_parametro" ( type "varchar", NotNull : true )
     * @return the field value
     */
	public String getCdParametro() {
        return this.cdParametro;
    }

    /**
     * Set the "sDescrizione" field value
     * This field is mapped on the database column "s_descrizione" ( type "varchar", NotNull : false )
     * @param sDescrizione
     */
    public void setSDescrizione(String sDescrizione) {
        this.sDescrizione = sDescrizione;
    }

    /**
     * Get the "sDescrizione" field value
     * This field is mapped on the database column "s_descrizione" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getSDescrizione() {
        return this.sDescrizione;
    }

    /**
     * Set the "sValore" field value
     * This field is mapped on the database column "s_valore" ( type "varchar", NotNull : false )
     * @param sValore
     */
    public void setSValore(String sValore) {
        this.sValore = sValore;
    }

    /**
     * Get the "sValore" field value
     * This field is mapped on the database column "s_valore" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getSValore() {
        return this.sValore;
    }

    /**
     * Set the "nValore" field value
     * This field is mapped on the database column "n_valore" ( type "numeric", NotNull : false )
     * @param nValore
     */
    public void setNValore(Long nValore) {
        this.nValore = nValore;
    }

    /**
     * Get the "nValore" field value
     * This field is mapped on the database column "n_valore" ( type "numeric", NotNull : false )
     * @return the field value
     */
    public Long getNValore() {
        return this.nValore;
    }

    /**
     * Set the "dValore" field value
     * This field is mapped on the database column "d_valore" ( type "timestamp", NotNull : false )
     * @param dValore
     */
    public void setDValore(Date dValore) {
        this.dValore = dValore;
    }

    /**
     * Get the "dValore" field value
     * This field is mapped on the database column "d_valore" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDValore() {
        return this.dValore;
    }

    /**
     * Set the "sTipoDato" field value
     * This field is mapped on the database column "s_tipo_dato" ( type "varchar", NotNull : false )
     * @param sTipoDato
     */
    public void setSTipoDato(String sTipoDato) {
        this.sTipoDato = sTipoDato;
    }

    /**
     * Get the "sTipoDato" field value
     * This field is mapped on the database column "s_tipo_dato" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getSTipoDato() {
        return this.sTipoDato;
    }

    /**
     * Set the "bLoglev1" field value
     * This field is mapped on the database column "b_loglev1" ( type "bool", NotNull : false )
     * @param bLoglev1
     */
    public void setBLoglev1(Boolean bLoglev1) {
        this.bLoglev1 = bLoglev1;
    }

    /**
     * Get the "bLoglev1" field value
     * This field is mapped on the database column "b_loglev1" ( type "bool", NotNull : false )
     * @return the field value
     */
    public Boolean getBLoglev1() {
        return this.bLoglev1;
    }

    /**
     * Set the "bLoglev2" field value
     * This field is mapped on the database column "b_loglev2" ( type "bool", NotNull : false )
     * @param bLoglev2
     */
    public void setBLoglev2(Boolean bLoglev2) {
        this.bLoglev2 = bLoglev2;
    }

    /**
     * Get the "bLoglev2" field value
     * This field is mapped on the database column "b_loglev2" ( type "bool", NotNull : false )
     * @return the field value
     */
    public Boolean getBLoglev2() {
        return this.bLoglev2;
    }

    /**
     * Set the "bLoglev3" field value
     * This field is mapped on the database column "b_loglev3" ( type "bool", NotNull : false )
     * @param bLoglev3
     */
    public void setBLoglev3(Boolean bLoglev3) {
        this.bLoglev3 = bLoglev3;
    }

    /**
     * Get the "bLoglev3" field value
     * This field is mapped on the database column "b_loglev3" ( type "bool", NotNull : false )
     * @return the field value
     */
    public Boolean getBLoglev3() {
        return this.bLoglev3;
    }

    /**
     * Set the "bLoglev4" field value
     * This field is mapped on the database column "b_loglev4" ( type "bool", NotNull : false )
     * @param bLoglev4
     */
    public void setBLoglev4(Boolean bLoglev4) {
        this.bLoglev4 = bLoglev4;
    }

    /**
     * Get the "bLoglev4" field value
     * This field is mapped on the database column "b_loglev4" ( type "bool", NotNull : false )
     * @return the field value
     */
    public Boolean getBLoglev4() {
        return this.bLoglev4;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(cdParametro);
        sb.append("|");
        sb.append(sDescrizione);
        sb.append("|");
        sb.append(sValore);
        sb.append("|");
        sb.append(nValore);
        sb.append("|");
        sb.append(dValore);
        sb.append("|");
        sb.append(sTipoDato);
        sb.append("|");
        sb.append(bLoglev1);
        sb.append("|");
        sb.append(bLoglev2);
        sb.append("|");
        sb.append(bLoglev3);
        sb.append("|");
        sb.append(bLoglev4);
        return sb.toString(); 
    } 

}
