/*
 * Java bean class for entity "iscritto_t_comune"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_comune"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTComune implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_comune, " +
		"  desc_comune, " +
		"  desc_regione, " +
		"  sigla_prov, " +
		"  cod_catasto, " +
		"  id_comune_sorg, " +
		"  dt_start, " +
		"  dt_stop, " +
		"  rel_status, " +
		"  istat_comune, " +
		"  cap, " +
		"  istat_provincia, " +
		"  desc_provincia, " +
		"  istat_regione " +
		"from iscritto_t_comune ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_comune (" +
		"  id_comune, " +
		"  desc_comune, " +
		"  desc_regione, " +
		"  sigla_prov, " +
		"  cod_catasto, " +
		"  id_comune_sorg, " +
		"  dt_start, " +
		"  dt_stop, " +
		"  rel_status, " +
		"  istat_comune, " +
		"  cap, " +
		"  istat_provincia, " +
		"  desc_provincia, " +
		"  istat_regione " +
		") " +
		"values (" +
		"  :idComune, " +
		"  :descComune, " +
		"  :descRegione, " +
		"  :siglaProv, " +
		"  :codCatasto, " +
		"  :idComuneSorg, " +
		"  :dtStart, " +
		"  :dtStop, " +
		"  :relStatus, " +
		"  :istatComune, " +
		"  :cap, " +
		"  :istatProvincia, " +
		"  :descProvincia, " +
		"  :istatRegione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_comune where " +
		"  id_comune = :idComune ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_comune";

	//////////////////////////////////////////////////////////////////////


    private Long       idComune     ; // Id or Primary Key

    private String     descComune   ;
    private String     descRegione  ;
    private String     siglaProv    ;
    private String     codCatasto   ;
    private Long       idComuneSorg ;
    private Date       dtStart      ;
    private Date       dtStop       ;
    private String     relStatus    ;
    private String     istatComune  ;
    private String     cap          ;
    private String     istatProvincia ;
    private String     descProvincia ;
    private String     istatRegione ;

    /**
     * Set the "idComune" field value
     * This field is mapped on the database column "id_comune" ( type "int4", NotNull : true )
     * @param idComune
     */
	public void setIdComune(Long idComune) {
        this.idComune = idComune ;
    }

    /**
     * Get the "idComune" field value
     * This field is mapped on the database column "id_comune" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdComune() {
        return this.idComune;
    }

    /**
     * Set the "descComune" field value
     * This field is mapped on the database column "desc_comune" ( type "varchar", NotNull : true )
     * @param descComune
     */
    public void setDescComune(String descComune) {
        this.descComune = descComune;
    }

    /**
     * Get the "descComune" field value
     * This field is mapped on the database column "desc_comune" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescComune() {
        return this.descComune;
    }

    /**
     * Set the "descRegione" field value
     * This field is mapped on the database column "desc_regione" ( type "varchar", NotNull : true )
     * @param descRegione
     */
    public void setDescRegione(String descRegione) {
        this.descRegione = descRegione;
    }

    /**
     * Get the "descRegione" field value
     * This field is mapped on the database column "desc_regione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescRegione() {
        return this.descRegione;
    }

    /**
     * Set the "siglaProv" field value
     * This field is mapped on the database column "sigla_prov" ( type "varchar", NotNull : true )
     * @param siglaProv
     */
    public void setSiglaProv(String siglaProv) {
        this.siglaProv = siglaProv;
    }

    /**
     * Get the "siglaProv" field value
     * This field is mapped on the database column "sigla_prov" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getSiglaProv() {
        return this.siglaProv;
    }

    /**
     * Set the "codCatasto" field value
     * This field is mapped on the database column "cod_catasto" ( type "varchar", NotNull : true )
     * @param codCatasto
     */
    public void setCodCatasto(String codCatasto) {
        this.codCatasto = codCatasto;
    }

    /**
     * Get the "codCatasto" field value
     * This field is mapped on the database column "cod_catasto" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodCatasto() {
        return this.codCatasto;
    }

    /**
     * Set the "idComuneSorg" field value
     * This field is mapped on the database column "id_comune_sorg" ( type "int4", NotNull : true )
     * @param idComuneSorg
     */
    public void setIdComuneSorg(Long idComuneSorg) {
        this.idComuneSorg = idComuneSorg;
    }

    /**
     * Get the "idComuneSorg" field value
     * This field is mapped on the database column "id_comune_sorg" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdComuneSorg() {
        return this.idComuneSorg;
    }

    /**
     * Set the "dtStart" field value
     * This field is mapped on the database column "dt_start" ( type "timestamp", NotNull : true )
     * @param dtStart
     */
    public void setDtStart(Date dtStart) {
        this.dtStart = dtStart;
    }

    /**
     * Get the "dtStart" field value
     * This field is mapped on the database column "dt_start" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtStart() {
        return this.dtStart;
    }

    /**
     * Set the "dtStop" field value
     * This field is mapped on the database column "dt_stop" ( type "timestamp", NotNull : true )
     * @param dtStop
     */
    public void setDtStop(Date dtStop) {
        this.dtStop = dtStop;
    }

    /**
     * Get the "dtStop" field value
     * This field is mapped on the database column "dt_stop" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtStop() {
        return this.dtStop;
    }

    /**
     * Set the "relStatus" field value
     * This field is mapped on the database column "rel_status" ( type "varchar", NotNull : true )
     * @param relStatus
     */
    public void setRelStatus(String relStatus) {
        this.relStatus = relStatus;
    }

    /**
     * Get the "relStatus" field value
     * This field is mapped on the database column "rel_status" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getRelStatus() {
        return this.relStatus;
    }

    /**
     * Set the "istatComune" field value
     * This field is mapped on the database column "istat_comune" ( type "varchar", NotNull : true )
     * @param istatComune
     */
    public void setIstatComune(String istatComune) {
        this.istatComune = istatComune;
    }

    /**
     * Get the "istatComune" field value
     * This field is mapped on the database column "istat_comune" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getIstatComune() {
        return this.istatComune;
    }

    /**
     * Set the "cap" field value
     * This field is mapped on the database column "cap" ( type "varchar", NotNull : true )
     * @param cap
     */
    public void setCap(String cap) {
        this.cap = cap;
    }

    /**
     * Get the "cap" field value
     * This field is mapped on the database column "cap" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCap() {
        return this.cap;
    }

    /**
     * Set the "istatProvincia" field value
     * This field is mapped on the database column "istat_provincia" ( type "varchar", NotNull : true )
     * @param istatProvincia
     */
    public void setIstatProvincia(String istatProvincia) {
        this.istatProvincia = istatProvincia;
    }

    /**
     * Get the "istatProvincia" field value
     * This field is mapped on the database column "istat_provincia" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getIstatProvincia() {
        return this.istatProvincia;
    }

    /**
     * Set the "descProvincia" field value
     * This field is mapped on the database column "desc_provincia" ( type "varchar", NotNull : true )
     * @param descProvincia
     */
    public void setDescProvincia(String descProvincia) {
        this.descProvincia = descProvincia;
    }

    /**
     * Get the "descProvincia" field value
     * This field is mapped on the database column "desc_provincia" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescProvincia() {
        return this.descProvincia;
    }

    /**
     * Set the "istatRegione" field value
     * This field is mapped on the database column "istat_regione" ( type "varchar", NotNull : true )
     * @param istatRegione
     */
    public void setIstatRegione(String istatRegione) {
        this.istatRegione = istatRegione;
    }

    /**
     * Get the "istatRegione" field value
     * This field is mapped on the database column "istat_regione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getIstatRegione() {
        return this.istatRegione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idComune);
        sb.append("|");
        sb.append(descComune);
        sb.append("|");
        sb.append(descRegione);
        sb.append("|");
        sb.append(siglaProv);
        sb.append("|");
        sb.append(codCatasto);
        sb.append("|");
        sb.append(idComuneSorg);
        sb.append("|");
        sb.append(dtStart);
        sb.append("|");
        sb.append(dtStop);
        sb.append("|");
        sb.append(relStatus);
        sb.append("|");
        sb.append(istatComune);
        sb.append("|");
        sb.append(cap);
        sb.append("|");
        sb.append(istatProvincia);
        sb.append("|");
        sb.append(descProvincia);
        sb.append("|");
        sb.append(istatRegione);
        return sb.toString(); 
    } 

}
