/*
 * Java bean class for entity "iscritto_d_relazione_par"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_relazione_par"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDRelazionePar implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_rel_parentela, " +
		"  cod_parentela, " +
		"  descrizione, " +
		"  fl_punteggio " +
		"from iscritto_d_relazione_par ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_relazione_par (" +
		"  id_rel_parentela, " +
		"  cod_parentela, " +
		"  descrizione, " +
		"  fl_punteggio " +
		") " +
		"values (" +
		"  :idRelParentela, " +
		"  :codParentela, " +
		"  :descrizione, " +
		"  :flPunteggio " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_relazione_par where " +
		"  id_rel_parentela = :idRelParentela ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_relazione_par";

	//////////////////////////////////////////////////////////////////////


    private Long       idRelParentela ; // Id or Primary Key

    private String     codParentela ;
    private String     descrizione  ;
    private String     flPunteggio  ;

    /**
     * Set the "idRelParentela" field value
     * This field is mapped on the database column "id_rel_parentela" ( type "int4", NotNull : true )
     * @param idRelParentela
     */
	public void setIdRelParentela(Long idRelParentela) {
        this.idRelParentela = idRelParentela ;
    }

    /**
     * Get the "idRelParentela" field value
     * This field is mapped on the database column "id_rel_parentela" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdRelParentela() {
        return this.idRelParentela;
    }

    /**
     * Set the "codParentela" field value
     * This field is mapped on the database column "cod_parentela" ( type "varchar", NotNull : true )
     * @param codParentela
     */
    public void setCodParentela(String codParentela) {
        this.codParentela = codParentela;
    }

    /**
     * Get the "codParentela" field value
     * This field is mapped on the database column "cod_parentela" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodParentela() {
        return this.codParentela;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }

    /**
     * Set the "flPunteggio" field value
     * This field is mapped on the database column "fl_punteggio" ( type "varchar", NotNull : false )
     * @param flPunteggio
     */
    public void setFlPunteggio(String flPunteggio) {
        this.flPunteggio = flPunteggio;
    }

    /**
     * Get the "flPunteggio" field value
     * This field is mapped on the database column "fl_punteggio" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlPunteggio() {
        return this.flPunteggio;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idRelParentela);
        sb.append("|");
        sb.append(codParentela);
        sb.append("|");
        sb.append(descrizione);
        sb.append("|");
        sb.append(flPunteggio);
        return sb.toString(); 
    } 

}
