/*
 * Java bean class for entity "iscritto_d_circoscrizione"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_circoscrizione"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDCircoscrizione implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_circoscrizione, " +
		"  cod_circoscrizione, " +
		"  descrizione " +
		"from iscritto_d_circoscrizione ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_circoscrizione (" +
		"  id_circoscrizione, " +
		"  cod_circoscrizione, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idCircoscrizione, " +
		"  :codCircoscrizione, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_circoscrizione where " +
		"  id_circoscrizione = :idCircoscrizione ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_circoscrizione";

	//////////////////////////////////////////////////////////////////////


    private Long       idCircoscrizione ; // Id or Primary Key

    private String     codCircoscrizione ;
    private String     descrizione  ;

    /**
     * Set the "idCircoscrizione" field value
     * This field is mapped on the database column "id_circoscrizione" ( type "int4", NotNull : true )
     * @param idCircoscrizione
     */
	public void setIdCircoscrizione(Long idCircoscrizione) {
        this.idCircoscrizione = idCircoscrizione ;
    }

    /**
     * Get the "idCircoscrizione" field value
     * This field is mapped on the database column "id_circoscrizione" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdCircoscrizione() {
        return this.idCircoscrizione;
    }

    /**
     * Set the "codCircoscrizione" field value
     * This field is mapped on the database column "cod_circoscrizione" ( type "varchar", NotNull : true )
     * @param codCircoscrizione
     */
    public void setCodCircoscrizione(String codCircoscrizione) {
        this.codCircoscrizione = codCircoscrizione;
    }

    /**
     * Get the "codCircoscrizione" field value
     * This field is mapped on the database column "cod_circoscrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodCircoscrizione() {
        return this.codCircoscrizione;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idCircoscrizione);
        sb.append("|");
        sb.append(codCircoscrizione);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
