/*
 * Java bean class for entity "iscritto_t_anno_sco"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_anno_sco"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTAnnoSco implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_anno_scolastico, " +
		"  cod_anno_scolastico, " +
		"  descrizione, " +
		"  data_da, " +
		"  data_a " +
		"from iscritto_t_anno_sco ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_anno_sco (" +
		"  id_anno_scolastico, " +
		"  cod_anno_scolastico, " +
		"  descrizione, " +
		"  data_da, " +
		"  data_a " +
		") " +
		"values (" +
		"  :idAnnoScolastico, " +
		"  :codAnnoScolastico, " +
		"  :descrizione, " +
		"  :dataDa, " +
		"  :dataA " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_anno_sco where " +
		"  id_anno_scolastico = :idAnnoScolastico ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_anno_sco";

	//////////////////////////////////////////////////////////////////////


    private Long       idAnnoScolastico ; // Id or Primary Key

    private String     codAnnoScolastico ;
    private String     descrizione  ;
    private Date       dataDa       ;
    private Date       dataA        ;

    /**
     * Set the "idAnnoScolastico" field value
     * This field is mapped on the database column "id_anno_scolastico" ( type "int4", NotNull : true )
     * @param idAnnoScolastico
     */
	public void setIdAnnoScolastico(Long idAnnoScolastico) {
        this.idAnnoScolastico = idAnnoScolastico ;
    }

    /**
     * Get the "idAnnoScolastico" field value
     * This field is mapped on the database column "id_anno_scolastico" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdAnnoScolastico() {
        return this.idAnnoScolastico;
    }

    /**
     * Set the "codAnnoScolastico" field value
     * This field is mapped on the database column "cod_anno_scolastico" ( type "varchar", NotNull : true )
     * @param codAnnoScolastico
     */
    public void setCodAnnoScolastico(String codAnnoScolastico) {
        this.codAnnoScolastico = codAnnoScolastico;
    }

    /**
     * Get the "codAnnoScolastico" field value
     * This field is mapped on the database column "cod_anno_scolastico" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodAnnoScolastico() {
        return this.codAnnoScolastico;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }

    /**
     * Set the "dataDa" field value
     * This field is mapped on the database column "data_da" ( type "timestamp", NotNull : true )
     * @param dataDa
     */
    public void setDataDa(Date dataDa) {
        this.dataDa = dataDa;
    }

    /**
     * Get the "dataDa" field value
     * This field is mapped on the database column "data_da" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDataDa() {
        return this.dataDa;
    }

    /**
     * Set the "dataA" field value
     * This field is mapped on the database column "data_a" ( type "timestamp", NotNull : true )
     * @param dataA
     */
    public void setDataA(Date dataA) {
        this.dataA = dataA;
    }

    /**
     * Get the "dataA" field value
     * This field is mapped on the database column "data_a" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDataA() {
        return this.dataA;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idAnnoScolastico);
        sb.append("|");
        sb.append(codAnnoScolastico);
        sb.append("|");
        sb.append(descrizione);
        sb.append("|");
        sb.append(dataDa);
        sb.append("|");
        sb.append(dataA);
        return sb.toString(); 
    } 

}
