/*
 * Java bean class for entity "iscritto_t_domanda_isc"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_domanda_isc"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTDomandaIsc implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_domanda_iscrizione, " +
		"  data_consegna, " +
		"  id_coabitazione, " +
		"  protocollo, " +
		"  fl_servizi_sociali, " +
		"  note, " +
		"  fl_residenza_forzata, " +
		"  fl_contestazione, " +
		"  fl_trasferimento, " +
		"  id_anno_scolastico, " +
		"  id_ordine_scuola, " +
		"  fl_isee, " +
		"  fl_fratello_freq, " +
		"  dt_modifica, " +
		"  dt_cancellazione, " +
		"  email, " +
		"  fl_istruita, " +
		"  telefono, " +
		"  fl_responsabilita_gen, " +
		"  recapito_no_res, " +
		"  fl_info_autocertificazione, " +
		"  id_stato_dom, " +
		"  fl_info_gdpr, " +
		"  fl_minore_pre_nuc, " +
		"  fl_res_con_ric, " +
		"  id_utente_ins, " +
		"  fl_genitore_due_pre_nuc, " +
		"  fl_altri_componenti, " +
		"  id_utente_mod, " +
		"  fl_affido, " +
		"  fl_nao, " +
		"  fl_soggetto_tre, " +
		"  fl_consenso_td_conv, " +
		"  fl_cinque_anni, " +
		"  fl_lista_attesa, " +
		"  fl_fratello_contiguo, " +
		"  fl_irc " +
		"from iscritto_t_domanda_isc ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_domanda_isc (" +
		"  id_domanda_iscrizione, " +
		"  data_consegna, " +
		"  id_coabitazione, " +
		"  protocollo, " +
		"  fl_servizi_sociali, " +
		"  note, " +
		"  fl_residenza_forzata, " +
		"  fl_contestazione, " +
		"  fl_trasferimento, " +
		"  id_anno_scolastico, " +
		"  id_ordine_scuola, " +
		"  fl_isee, " +
		"  fl_fratello_freq, " +
		"  dt_modifica, " +
		"  dt_cancellazione, " +
		"  email, " +
		"  fl_istruita, " +
		"  telefono, " +
		"  fl_responsabilita_gen, " +
		"  recapito_no_res, " +
		"  fl_info_autocertificazione, " +
		"  id_stato_dom, " +
		"  fl_info_gdpr, " +
		"  fl_minore_pre_nuc, " +
		"  fl_res_con_ric, " +
		"  id_utente_ins, " +
		"  fl_genitore_due_pre_nuc, " +
		"  fl_altri_componenti, " +
		"  id_utente_mod, " +
		"  fl_affido, " +
		"  fl_nao, " +
		"  fl_soggetto_tre, " +
		"  fl_consenso_td_conv, " +
		"  fl_cinque_anni, " +
		"  fl_lista_attesa, " +
		"  fl_fratello_contiguo " +
		"  fl_irc" +
		") " +
		"values (" +
		"  :idDomandaIscrizione, " +
		"  :dataConsegna, " +
		"  :idCoabitazione, " +
		"  :protocollo, " +
		"  :flServiziSociali, " +
		"  :note, " +
		"  :flResidenzaForzata, " +
		"  :flContestazione, " +
		"  :flTrasferimento, " +
		"  :idAnnoScolastico, " +
		"  :idOrdineScuola, " +
		"  :flIsee, " +
		"  :flFratelloFreq, " +
		"  :dtModifica, " +
		"  :dtCancellazione, " +
		"  :email, " +
		"  :flIstruita, " +
		"  :telefono, " +
		"  :flResponsabilitaGen, " +
		"  :recapitoNoRes, " +
		"  :flInfoAutocertificazione, " +
		"  :idStatoDom, " +
		"  :flInfoGdpr, " +
		"  :flMinorePreNuc, " +
		"  :flResConRic, " +
		"  :idUtenteIns, " +
		"  :flGenitoreDuePreNuc, " +
		"  :flAltriComponenti, " +
		"  :idUtenteMod, " +
		"  :flAffido, " +
		"  :flNao, " +
		"  :flSoggettoTre, " +
		"  :flConsensoTdConv, " +
		"  :flCinqueAnni, " +
		"  :flListaAttesa, " +
		"  :flFratelloContiguo " +
		"  :flIrc" +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_domanda_isc where " +
		"  id_domanda_iscrizione = :idDomandaIscrizione ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_domanda_isc";

	//////////////////////////////////////////////////////////////////////


    private Long       idDomandaIscrizione ; // Id or Primary Key

    private Date       dataConsegna ;
    private Long       idCoabitazione ;
    private String     protocollo   ;
    private String     flServiziSociali ;
    private String     note         ;
    private String     flResidenzaForzata ;
    private String     flContestazione ;
    private String     flTrasferimento ;
    private Long       idAnnoScolastico ;
    private Long       idOrdineScuola ;
    private String     flIsee       ;
    private String     flFratelloFreq ;
    private Date       dtModifica   ;
    private Date       dtCancellazione ;
    private String     email        ;
    private String     flIstruita   ;
    private String     telefono     ;
    private String     flResponsabilitaGen ;
    private String     recapitoNoRes ;
    private String     flInfoAutocertificazione ;
    private Long       idStatoDom   ;
    private String     flInfoGdpr   ;
    private String     flMinorePreNuc ;
    private String     flResConRic  ;
    private Long       idUtenteIns  ;
    private String     flGenitoreDuePreNuc ;
    private String     flAltriComponenti ;
    private Long       idUtenteMod  ;
    private String     flAffido     ;
    private String     flNao        ;
    private String     flSoggettoTre ;
    private String     flConsensoTdConv;
    private String     flCinqueAnni;
    private String     flListaAttesa;
    private String     flFratelloContiguo;
    private String	   flIrc;


	public String getFlIrc() {
		return flIrc;
	}

	public void setFlIrc(String flIrc) {
		this.flIrc = flIrc;
	}

	/**
     * Set the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @param idDomandaIscrizione
     */
	public void setIdDomandaIscrizione(Long idDomandaIscrizione) {
        this.idDomandaIscrizione = idDomandaIscrizione ;
    }

    /**
     * Get the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdDomandaIscrizione() {
        return this.idDomandaIscrizione;
    }

    /**
     * Set the "dataConsegna" field value
     * This field is mapped on the database column "data_consegna" ( type "timestamp", NotNull : true )
     * @param dataConsegna
     */
    public void setDataConsegna(Date dataConsegna) {
        this.dataConsegna = dataConsegna;
    }

    /**
     * Get the "dataConsegna" field value
     * This field is mapped on the database column "data_consegna" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDataConsegna() {
        return this.dataConsegna;
    }

    /**
     * Set the "idCoabitazione" field value
     * This field is mapped on the database column "id_coabitazione" ( type "int4", NotNull : true )
     * @param idCoabitazione
     */
    public void setIdCoabitazione(Long idCoabitazione) {
        this.idCoabitazione = idCoabitazione;
    }

    /**
     * Get the "idCoabitazione" field value
     * This field is mapped on the database column "id_coabitazione" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdCoabitazione() {
        return this.idCoabitazione;
    }

    /**
     * Set the "protocollo" field value
     * This field is mapped on the database column "protocollo" ( type "varchar", NotNull : false )
     * @param protocollo
     */
    public void setProtocollo(String protocollo) {
        this.protocollo = protocollo;
    }

    /**
     * Get the "protocollo" field value
     * This field is mapped on the database column "protocollo" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getProtocollo() {
        return this.protocollo;
    }

    /**
     * Set the "flServiziSociali" field value
     * This field is mapped on the database column "fl_servizi_sociali" ( type "bytea", NotNull : true )
     * @param flServiziSociali
     */
    public void setFlServiziSociali(String flServiziSociali) {
        this.flServiziSociali = flServiziSociali;
    }

    /**
     * Get the "flServiziSociali" field value
     * This field is mapped on the database column "fl_servizi_sociali" ( type "bytea", NotNull : true )
     * @return the field value
     */
    public String getFlServiziSociali() {
        return this.flServiziSociali;
    }

    /**
     * Set the "note" field value
     * This field is mapped on the database column "note" ( type "text", NotNull : false )
     * @param note
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * Get the "note" field value
     * This field is mapped on the database column "note" ( type "text", NotNull : false )
     * @return the field value
     */
    public String getNote() {
        return this.note;
    }

    /**
     * Set the "flResidenzaForzata" field value
     * This field is mapped on the database column "fl_residenza_forzata" ( type "varchar", NotNull : true )
     * @param flResidenzaForzata
     */
    public void setFlResidenzaForzata(String flResidenzaForzata) {
        this.flResidenzaForzata = flResidenzaForzata;
    }

    /**
     * Get the "flResidenzaForzata" field value
     * This field is mapped on the database column "fl_residenza_forzata" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlResidenzaForzata() {
        return this.flResidenzaForzata;
    }

    /**
     * Set the "flContestazione" field value
     * This field is mapped on the database column "fl_contestazione" ( type "varchar", NotNull : true )
     * @param flContestazione
     */
    public void setFlContestazione(String flContestazione) {
        this.flContestazione = flContestazione;
    }

    /**
     * Get the "flContestazione" field value
     * This field is mapped on the database column "fl_contestazione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlContestazione() {
        return this.flContestazione;
    }

    /**
     * Set the "flTrasferimento" field value
     * This field is mapped on the database column "fl_trasferimento" ( type "varchar", NotNull : true )
     * @param flTrasferimento
     */
    public void setFlTrasferimento(String flTrasferimento) {
        this.flTrasferimento = flTrasferimento;
    }

    /**
     * Get the "flTrasferimento" field value
     * This field is mapped on the database column "fl_trasferimento" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlTrasferimento() {
        return this.flTrasferimento;
    }

    /**
     * Set the "idAnnoScolastico" field value
     * This field is mapped on the database column "id_anno_scolastico" ( type "int4", NotNull : true )
     * @param idAnnoScolastico
     */
    public void setIdAnnoScolastico(Long idAnnoScolastico) {
        this.idAnnoScolastico = idAnnoScolastico;
    }

    /**
     * Get the "idAnnoScolastico" field value
     * This field is mapped on the database column "id_anno_scolastico" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdAnnoScolastico() {
        return this.idAnnoScolastico;
    }

    /**
     * Set the "idOrdineScuola" field value
     * This field is mapped on the database column "id_ordine_scuola" ( type "int4", NotNull : true )
     * @param idOrdineScuola
     */
    public void setIdOrdineScuola(Long idOrdineScuola) {
        this.idOrdineScuola = idOrdineScuola;
    }

    /**
     * Get the "idOrdineScuola" field value
     * This field is mapped on the database column "id_ordine_scuola" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdOrdineScuola() {
        return this.idOrdineScuola;
    }

    /**
     * Set the "flIsee" field value
     * This field is mapped on the database column "fl_isee" ( type "varchar", NotNull : true )
     * @param flIsee
     */
    public void setFlIsee(String flIsee) {
        this.flIsee = flIsee;
    }

    /**
     * Get the "flIsee" field value
     * This field is mapped on the database column "fl_isee" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlIsee() {
        return this.flIsee;
    }

    /**
     * Set the "flFratelloFreq" field value
     * This field is mapped on the database column "fl_fratello_freq" ( type "varchar", NotNull : true )
     * @param flFratelloFreq
     */
    public void setFlFratelloFreq(String flFratelloFreq) {
        this.flFratelloFreq = flFratelloFreq;
    }

    /**
     * Get the "flFratelloFreq" field value
     * This field is mapped on the database column "fl_fratello_freq" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlFratelloFreq() {
        return this.flFratelloFreq;
    }

    /**
     * Set the "dtModifica" field value
     * This field is mapped on the database column "dt_modifica" ( type "timestamp", NotNull : false )
     * @param dtModifica
     */
    public void setDtModifica(Date dtModifica) {
        this.dtModifica = dtModifica;
    }

    /**
     * Get the "dtModifica" field value
     * This field is mapped on the database column "dt_modifica" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtModifica() {
        return this.dtModifica;
    }

    /**
     * Set the "dtCancellazione" field value
     * This field is mapped on the database column "dt_cancellazione" ( type "timestamp", NotNull : false )
     * @param dtCancellazione
     */
    public void setDtCancellazione(Date dtCancellazione) {
        this.dtCancellazione = dtCancellazione;
    }

    /**
     * Get the "dtCancellazione" field value
     * This field is mapped on the database column "dt_cancellazione" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtCancellazione() {
        return this.dtCancellazione;
    }

    /**
     * Set the "email" field value
     * This field is mapped on the database column "email" ( type "varchar", NotNull : false )
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Get the "email" field value
     * This field is mapped on the database column "email" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Set the "flIstruita" field value
     * This field is mapped on the database column "fl_istruita" ( type "varchar", NotNull : false )
     * @param flIstruita
     */
    public void setFlIstruita(String flIstruita) {
        this.flIstruita = flIstruita;
    }

    /**
     * Get the "flIstruita" field value
     * This field is mapped on the database column "fl_istruita" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlIstruita() {
        return this.flIstruita;
    }

    /**
     * Set the "telefono" field value
     * This field is mapped on the database column "telefono" ( type "varchar", NotNull : true )
     * @param telefono
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * Get the "telefono" field value
     * This field is mapped on the database column "telefono" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getTelefono() {
        return this.telefono;
    }

    /**
     * Set the "flResponsabilitaGen" field value
     * This field is mapped on the database column "fl_responsabilita_gen" ( type "varchar", NotNull : true )
     * @param flResponsabilitaGen
     */
    public void setFlResponsabilitaGen(String flResponsabilitaGen) {
        this.flResponsabilitaGen = flResponsabilitaGen;
    }

    /**
     * Get the "flResponsabilitaGen" field value
     * This field is mapped on the database column "fl_responsabilita_gen" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlResponsabilitaGen() {
        return this.flResponsabilitaGen;
    }

    /**
     * Set the "recapitoNoRes" field value
     * This field is mapped on the database column "recapito_no_res" ( type "varchar", NotNull : false )
     * @param recapitoNoRes
     */
    public void setRecapitoNoRes(String recapitoNoRes) {
        this.recapitoNoRes = recapitoNoRes;
    }

    /**
     * Get the "recapitoNoRes" field value
     * This field is mapped on the database column "recapito_no_res" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getRecapitoNoRes() {
        return this.recapitoNoRes;
    }

    /**
     * Set the "flInfoAutocertificazione" field value
     * This field is mapped on the database column "fl_info_autocertificazione" ( type "varchar", NotNull : true )
     * @param flInfoAutocertificazione
     */
    public void setFlInfoAutocertificazione(String flInfoAutocertificazione) {
        this.flInfoAutocertificazione = flInfoAutocertificazione;
    }

    /**
     * Get the "flInfoAutocertificazione" field value
     * This field is mapped on the database column "fl_info_autocertificazione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlInfoAutocertificazione() {
        return this.flInfoAutocertificazione;
    }

    /**
     * Set the "idStatoDom" field value
     * This field is mapped on the database column "id_stato_dom" ( type "int4", NotNull : true )
     * @param idStatoDom
     */
    public void setIdStatoDom(Long idStatoDom) {
        this.idStatoDom = idStatoDom;
    }

    /**
     * Get the "idStatoDom" field value
     * This field is mapped on the database column "id_stato_dom" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdStatoDom() {
        return this.idStatoDom;
    }

    /**
     * Set the "flInfoGdpr" field value
     * This field is mapped on the database column "fl_info_gdpr" ( type "varchar", NotNull : true )
     * @param flInfoGdpr
     */
    public void setFlInfoGdpr(String flInfoGdpr) {
        this.flInfoGdpr = flInfoGdpr;
    }

    /**
     * Get the "flInfoGdpr" field value
     * This field is mapped on the database column "fl_info_gdpr" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlInfoGdpr() {
        return this.flInfoGdpr;
    }

    /**
     * Set the "flMinorePreNuc" field value
     * This field is mapped on the database column "fl_minore_pre_nuc" ( type "varchar", NotNull : false )
     * @param flMinorePreNuc
     */
    public void setFlMinorePreNuc(String flMinorePreNuc) {
        this.flMinorePreNuc = flMinorePreNuc;
    }

    /**
     * Get the "flMinorePreNuc" field value
     * This field is mapped on the database column "fl_minore_pre_nuc" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlMinorePreNuc() {
        return this.flMinorePreNuc;
    }

    /**
     * Set the "flResConRic" field value
     * This field is mapped on the database column "fl_res_con_ric" ( type "varchar", NotNull : false )
     * @param flResConRic
     */
    public void setFlResConRic(String flResConRic) {
        this.flResConRic = flResConRic;
    }

    /**
     * Get the "flResConRic" field value
     * This field is mapped on the database column "fl_res_con_ric" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlResConRic() {
        return this.flResConRic;
    }

    /**
     * Set the "idUtenteIns" field value
     * This field is mapped on the database column "id_utente_ins" ( type "int4", NotNull : false )
     * @param idUtenteIns
     */
    public void setIdUtenteIns(Long idUtenteIns) {
        this.idUtenteIns = idUtenteIns;
    }

    /**
     * Get the "idUtenteIns" field value
     * This field is mapped on the database column "id_utente_ins" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdUtenteIns() {
        return this.idUtenteIns;
    }

    /**
     * Set the "flGenitoreDuePreNuc" field value
     * This field is mapped on the database column "fl_genitore_due_pre_nuc" ( type "varchar", NotNull : false )
     * @param flGenitoreDuePreNuc
     */
    public void setFlGenitoreDuePreNuc(String flGenitoreDuePreNuc) {
        this.flGenitoreDuePreNuc = flGenitoreDuePreNuc;
    }

    /**
     * Get the "flGenitoreDuePreNuc" field value
     * This field is mapped on the database column "fl_genitore_due_pre_nuc" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlGenitoreDuePreNuc() {
        return this.flGenitoreDuePreNuc;
    }

    /**
     * Set the "flAltriComponenti" field value
     * This field is mapped on the database column "fl_altri_componenti" ( type "varchar", NotNull : false )
     * @param flAltriComponenti
     */
    public void setFlAltriComponenti(String flAltriComponenti) {
        this.flAltriComponenti = flAltriComponenti;
    }

    /**
     * Get the "flAltriComponenti" field value
     * This field is mapped on the database column "fl_altri_componenti" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlAltriComponenti() {
        return this.flAltriComponenti;
    }

    /**
     * Set the "idUtenteMod" field value
     * This field is mapped on the database column "id_utente_mod" ( type "int4", NotNull : false )
     * @param idUtenteMod
     */
    public void setIdUtenteMod(Long idUtenteMod) {
        this.idUtenteMod = idUtenteMod;
    }

    /**
     * Get the "idUtenteMod" field value
     * This field is mapped on the database column "id_utente_mod" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdUtenteMod() {
        return this.idUtenteMod;
    }

    /**
     * Set the "flAffido" field value
     * This field is mapped on the database column "fl_affido" ( type "varchar", NotNull : false )
     * @param flAffido
     */
    public void setFlAffido(String flAffido) {
        this.flAffido = flAffido;
    }

    /**
     * Get the "flAffido" field value
     * This field is mapped on the database column "fl_affido" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlAffido() {
        return this.flAffido;
    }

    /**
     * Set the "flNao" field value
     * This field is mapped on the database column "fl_nao" ( type "varchar", NotNull : false )
     * @param flNao
     */
    public void setFlNao(String flNao) {
        this.flNao = flNao;
    }

    /**
     * Get the "flNao" field value
     * This field is mapped on the database column "fl_nao" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlNao() {
        return this.flNao;
    }

    /**
     * Set the "flSoggettoTre" field value
     * This field is mapped on the database column "fl_soggetto_tre" ( type "varchar", NotNull : false )
     * @param flSoggettoTre
     */
    public void setFlSoggettoTre(String flSoggettoTre) {
        this.flSoggettoTre = flSoggettoTre;
    }

    /**
     * Get the "flSoggettoTre" field value
     * This field is mapped on the database column "fl_soggetto_tre" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlSoggettoTre() {
        return this.flSoggettoTre;
    }

	public String getFlConsensoTdConv() {
		return flConsensoTdConv;
	}

	public void setFlConsensoTdConv(String flConsensoTdConv) {
		this.flConsensoTdConv = flConsensoTdConv;
	}

	public String getFlCinqueAnni() {
		return flCinqueAnni;
	}

	public void setFlCinqueAnni(String flCinqueAnni) {
		this.flCinqueAnni = flCinqueAnni;
	}

	public String getFlListaAttesa() {
		return flListaAttesa;
	}

	public void setFlListaAttesa(String flListaAttesa) {
		this.flListaAttesa = flListaAttesa;
	}

	public String getFlFratelloContiguo() {
		return flFratelloContiguo;
	}

	public void setFlFratelloContiguo(String flFratelloContiguo) {
		this.flFratelloContiguo = flFratelloContiguo;
	}

    @Override
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(idDomandaIscrizione);
        sb.append("|");
        sb.append(dataConsegna);
        sb.append("|");
        sb.append(idCoabitazione);
        sb.append("|");
        sb.append(protocollo);
        sb.append("|");
        sb.append(flServiziSociali);
        sb.append("|");
        sb.append(note);
        sb.append("|");
        sb.append(flResidenzaForzata);
        sb.append("|");
        sb.append(flContestazione);
        sb.append("|");
        sb.append(flTrasferimento);
        sb.append("|");
        sb.append(idAnnoScolastico);
        sb.append("|");
        sb.append(idOrdineScuola);
        sb.append("|");
        sb.append(flIsee);
        sb.append("|");
        sb.append(flFratelloFreq);
        sb.append("|");
        sb.append(dtModifica);
        sb.append("|");
        sb.append(dtCancellazione);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(flIstruita);
        sb.append("|");
        sb.append(telefono);
        sb.append("|");
        sb.append(flResponsabilitaGen);
        sb.append("|");
        sb.append(recapitoNoRes);
        sb.append("|");
        sb.append(flInfoAutocertificazione);
        sb.append("|");
        sb.append(idStatoDom);
        sb.append("|");
        sb.append(flInfoGdpr);
        sb.append("|");
        sb.append(flMinorePreNuc);
        sb.append("|");
        sb.append(flResConRic);
        sb.append("|");
        sb.append(idUtenteIns);
        sb.append("|");
        sb.append(flGenitoreDuePreNuc);
        sb.append("|");
        sb.append(flAltriComponenti);
        sb.append("|");
        sb.append(idUtenteMod);
        sb.append("|");
        sb.append(flAffido);
        sb.append("|");
        sb.append(flNao);
        sb.append("|");
        sb.append(flSoggettoTre);
        sb.append("|");
        sb.append(flConsensoTdConv);
        sb.append("|");
        sb.append(flCinqueAnni);
        sb.append("|");
        sb.append(flListaAttesa);
        sb.append("|");
        sb.append(flFratelloContiguo);
        sb.append("|");
        sb.append(flIrc);
        return sb.toString();
    }

}
