/*
 * Java bean class for entity "iscritto_r_soggetto_rel"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_r_soggetto_rel"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoRSoggettoRel implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_anagrafica_soggetto, " +
		"  id_tipo_soggetto " +
		"from iscritto_r_soggetto_rel ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_r_soggetto_rel (" +
		"  id_anagrafica_soggetto, " +
		"  id_tipo_soggetto " +
		") " +
		"values (" +
		"  :idAnagraficaSoggetto, " +
		"  :idTipoSoggetto " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_r_soggetto_rel where " +
		"  id_anagrafica_soggetto = :idAnagraficaSoggetto and " +
		"  id_tipo_soggetto = :idTipoSoggetto ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_r_soggetto_rel";

	//////////////////////////////////////////////////////////////////////


    private Long       idAnagraficaSoggetto ; // Id or Primary Key
    private Long       idTipoSoggetto ; // Id or Primary Key


    /**
     * Set the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : true )
     * @param idAnagraficaSoggetto
     */
	public void setIdAnagraficaSoggetto(Long idAnagraficaSoggetto) {
        this.idAnagraficaSoggetto = idAnagraficaSoggetto ;
    }

    /**
     * Get the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdAnagraficaSoggetto() {
        return this.idAnagraficaSoggetto;
    }
    /**
     * Set the "idTipoSoggetto" field value
     * This field is mapped on the database column "id_tipo_soggetto" ( type "int4", NotNull : true )
     * @param idTipoSoggetto
     */
	public void setIdTipoSoggetto(Long idTipoSoggetto) {
        this.idTipoSoggetto = idTipoSoggetto ;
    }

    /**
     * Get the "idTipoSoggetto" field value
     * This field is mapped on the database column "id_tipo_soggetto" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdTipoSoggetto() {
        return this.idTipoSoggetto;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idAnagraficaSoggetto);
        sb.append("|");
        sb.append(idTipoSoggetto);
        return sb.toString(); 
    } 

}
