/*
 * Java bean class for entity "iscritto_d_tipo_corso"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_tipo_corso"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDTipoCorso implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_tipo_corso, " +
		"  cod_tipo_corso, " +
		"  descrizione " +
		"from iscritto_d_tipo_corso ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_tipo_corso (" +
		"  id_tipo_corso, " +
		"  cod_tipo_corso, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idTipoCorso, " +
		"  :codTipoCorso, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_tipo_corso where " +
		"  id_tipo_corso = :idTipoCorso ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_tipo_corso";

	//////////////////////////////////////////////////////////////////////


    private Long       idTipoCorso  ; // Id or Primary Key

    private String     codTipoCorso ;
    private String     descrizione  ;

    /**
     * Set the "idTipoCorso" field value
     * This field is mapped on the database column "id_tipo_corso" ( type "int4", NotNull : true )
     * @param idTipoCorso
     */
	public void setIdTipoCorso(Long idTipoCorso) {
        this.idTipoCorso = idTipoCorso ;
    }

    /**
     * Get the "idTipoCorso" field value
     * This field is mapped on the database column "id_tipo_corso" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdTipoCorso() {
        return this.idTipoCorso;
    }

    /**
     * Set the "codTipoCorso" field value
     * This field is mapped on the database column "cod_tipo_corso" ( type "varchar", NotNull : false )
     * @param codTipoCorso
     */
    public void setCodTipoCorso(String codTipoCorso) {
        this.codTipoCorso = codTipoCorso;
    }

    /**
     * Get the "codTipoCorso" field value
     * This field is mapped on the database column "cod_tipo_corso" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getCodTipoCorso() {
        return this.codTipoCorso;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTipoCorso);
        sb.append("|");
        sb.append(codTipoCorso);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
