/*
 * Java bean class for entity "iscritto_t_parametro"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_parametro"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTParametro implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  num_nidi_pref, " +
		"  num_gg_risposta_amm, " +
		"  num_allegati_x_tip, " +
		"  dim_g_allegati, " +
		"  dt_ult_calcolo_pun, " +
		"  dt_ult_attribuzione_con, " +
		"  testo_sms_amm " +
		"from iscritto_t_parametro ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_parametro (" +
		"  num_nidi_pref, " +
		"  num_gg_risposta_amm, " +
		"  num_allegati_x_tip, " +
		"  dim_g_allegati, " +
		"  dt_ult_calcolo_pun, " +
		"  dt_ult_attribuzione_con, " +
		"  testo_sms_amm " +
		") " +
		"values (" +
		"  :numNidiPref, " +
		"  :numGgRispostaAmm, " +
		"  :numAllegatiXTip, " +
		"  :dimGAllegati, " +
		"  :dtUltCalcoloPun, " +
		"  :dtUltAttribuzioneCon, " +
		"  :testoSmsAmm " +
		")";

	//////////////////////////////////////////////////////////////////////


	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_parametro";

	//////////////////////////////////////////////////////////////////////



    private Integer    numNidiPref  ;
    private Integer    numGgRispostaAmm ;
    private Integer    numAllegatiXTip ;
    private Integer    dimGAllegati ;
    private Date       dtUltCalcoloPun ;
    private Date       dtUltAttribuzioneCon ;
    private String     testoSmsAmm  ;


    /**
     * Set the "numNidiPref" field value
     * This field is mapped on the database column "num_nidi_pref" ( type "int4", NotNull : false )
     * @param numNidiPref
     */
    public void setNumNidiPref(Integer numNidiPref) {
        this.numNidiPref = numNidiPref;
    }

    /**
     * Get the "numNidiPref" field value
     * This field is mapped on the database column "num_nidi_pref" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Integer getNumNidiPref() {
        return this.numNidiPref;
    }

    /**
     * Set the "numGgRispostaAmm" field value
     * This field is mapped on the database column "num_gg_risposta_amm" ( type "int4", NotNull : false )
     * @param numGgRispostaAmm
     */
    public void setNumGgRispostaAmm(Integer numGgRispostaAmm) {
        this.numGgRispostaAmm = numGgRispostaAmm;
    }

    /**
     * Get the "numGgRispostaAmm" field value
     * This field is mapped on the database column "num_gg_risposta_amm" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Integer getNumGgRispostaAmm() {
        return this.numGgRispostaAmm;
    }

    /**
     * Set the "numAllegatiXTip" field value
     * This field is mapped on the database column "num_allegati_x_tip" ( type "int4", NotNull : false )
     * @param numAllegatiXTip
     */
    public void setNumAllegatiXTip(Integer numAllegatiXTip) {
        this.numAllegatiXTip = numAllegatiXTip;
    }

    /**
     * Get the "numAllegatiXTip" field value
     * This field is mapped on the database column "num_allegati_x_tip" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Integer getNumAllegatiXTip() {
        return this.numAllegatiXTip;
    }

    /**
     * Set the "dimGAllegati" field value
     * This field is mapped on the database column "dim_g_allegati" ( type "int4", NotNull : false )
     * @param dimGAllegati
     */
    public void setDimGAllegati(Integer dimGAllegati) {
        this.dimGAllegati = dimGAllegati;
    }

    /**
     * Get the "dimGAllegati" field value
     * This field is mapped on the database column "dim_g_allegati" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Integer getDimGAllegati() {
        return this.dimGAllegati;
    }

    /**
     * Set the "dtUltCalcoloPun" field value
     * This field is mapped on the database column "dt_ult_calcolo_pun" ( type "timestamp", NotNull : false )
     * @param dtUltCalcoloPun
     */
    public void setDtUltCalcoloPun(Date dtUltCalcoloPun) {
        this.dtUltCalcoloPun = dtUltCalcoloPun;
    }

    /**
     * Get the "dtUltCalcoloPun" field value
     * This field is mapped on the database column "dt_ult_calcolo_pun" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtUltCalcoloPun() {
        return this.dtUltCalcoloPun;
    }

    /**
     * Set the "dtUltAttribuzioneCon" field value
     * This field is mapped on the database column "dt_ult_attribuzione_con" ( type "timestamp", NotNull : false )
     * @param dtUltAttribuzioneCon
     */
    public void setDtUltAttribuzioneCon(Date dtUltAttribuzioneCon) {
        this.dtUltAttribuzioneCon = dtUltAttribuzioneCon;
    }

    /**
     * Get the "dtUltAttribuzioneCon" field value
     * This field is mapped on the database column "dt_ult_attribuzione_con" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtUltAttribuzioneCon() {
        return this.dtUltAttribuzioneCon;
    }

    /**
     * Set the "testoSmsAmm" field value
     * This field is mapped on the database column "testo_sms_amm" ( type "varchar", NotNull : false )
     * @param testoSmsAmm
     */
    public void setTestoSmsAmm(String testoSmsAmm) {
        this.testoSmsAmm = testoSmsAmm;
    }

    /**
     * Get the "testoSmsAmm" field value
     * This field is mapped on the database column "testo_sms_amm" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getTestoSmsAmm() {
        return this.testoSmsAmm;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(numNidiPref);
        sb.append("|");
        sb.append(numGgRispostaAmm);
        sb.append("|");
        sb.append(numAllegatiXTip);
        sb.append("|");
        sb.append(dimGAllegati);
        sb.append("|");
        sb.append(dtUltCalcoloPun);
        sb.append("|");
        sb.append(dtUltAttribuzioneCon);
        sb.append("|");
        sb.append(testoSmsAmm);
        return sb.toString(); 
    } 

}
