/*
 * Java bean class for entity "iscritto_t_funzione"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_funzione"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTFunzione implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_funzione, " +
		"  cod_funzione, " +
		"  descrizione, " +
		"  link " +
		"from iscritto_t_funzione ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_funzione (" +
		"  id_funzione, " +
		"  cod_funzione, " +
		"  descrizione, " +
		"  link " +
		") " +
		"values (" +
		"  :idFunzione, " +
		"  :codFunzione, " +
		"  :descrizione, " +
		"  :link " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_funzione where " +
		"  id_funzione = :idFunzione ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_funzione";

	//////////////////////////////////////////////////////////////////////


    private Long       idFunzione   ; // Id or Primary Key

    private String     codFunzione  ;
    private String     descrizione  ;
    private String     link         ;

    /**
     * Set the "idFunzione" field value
     * This field is mapped on the database column "id_funzione" ( type "int4", NotNull : true )
     * @param idFunzione
     */
	public void setIdFunzione(Long idFunzione) {
        this.idFunzione = idFunzione ;
    }

    /**
     * Get the "idFunzione" field value
     * This field is mapped on the database column "id_funzione" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdFunzione() {
        return this.idFunzione;
    }

    /**
     * Set the "codFunzione" field value
     * This field is mapped on the database column "cod_funzione" ( type "varchar", NotNull : true )
     * @param codFunzione
     */
    public void setCodFunzione(String codFunzione) {
        this.codFunzione = codFunzione;
    }

    /**
     * Get the "codFunzione" field value
     * This field is mapped on the database column "cod_funzione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodFunzione() {
        return this.codFunzione;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }

    /**
     * Set the "link" field value
     * This field is mapped on the database column "link" ( type "varchar", NotNull : false )
     * @param link
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * Get the "link" field value
     * This field is mapped on the database column "link" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getLink() {
        return this.link;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idFunzione);
        sb.append("|");
        sb.append(codFunzione);
        sb.append("|");
        sb.append(descrizione);
        sb.append("|");
        sb.append(link);
        return sb.toString(); 
    } 

}
