/*
 * Java bean class for entity "iscritto_d_tip_con_occ"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_tip_con_occ"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDTipConOcc implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_tip_cond_occupazionale, " +
		"  cod_tip_cond_occupazionale, " +
		"  descrizione " +
		"from iscritto_d_tip_con_occ ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_tip_con_occ (" +
		"  id_tip_cond_occupazionale, " +
		"  cod_tip_cond_occupazionale, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idTipCondOccupazionale, " +
		"  :codTipCondOccupazionale, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_tip_con_occ where " +
		"  id_tip_cond_occupazionale = :idTipCondOccupazionale ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_tip_con_occ";

	//////////////////////////////////////////////////////////////////////


    private Long       idTipCondOccupazionale ; // Id or Primary Key

    private String     codTipCondOccupazionale ;
    private String     descrizione  ;

    /**
     * Set the "idTipCondOccupazionale" field value
     * This field is mapped on the database column "id_tip_cond_occupazionale" ( type "int4", NotNull : true )
     * @param idTipCondOccupazionale
     */
	public void setIdTipCondOccupazionale(Long idTipCondOccupazionale) {
        this.idTipCondOccupazionale = idTipCondOccupazionale ;
    }

    /**
     * Get the "idTipCondOccupazionale" field value
     * This field is mapped on the database column "id_tip_cond_occupazionale" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdTipCondOccupazionale() {
        return this.idTipCondOccupazionale;
    }

    /**
     * Set the "codTipCondOccupazionale" field value
     * This field is mapped on the database column "cod_tip_cond_occupazionale" ( type "varchar", NotNull : true )
     * @param codTipCondOccupazionale
     */
    public void setCodTipCondOccupazionale(String codTipCondOccupazionale) {
        this.codTipCondOccupazionale = codTipCondOccupazionale;
    }

    /**
     * Get the "codTipCondOccupazionale" field value
     * This field is mapped on the database column "cod_tip_cond_occupazionale" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodTipCondOccupazionale() {
        return this.codTipCondOccupazionale;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTipCondOccupazionale);
        sb.append("|");
        sb.append(codTipCondOccupazionale);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
