/*
 * Java bean class for entity "iscritto_r_punteggio_scu"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_r_punteggio_scu"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoRPunteggioScu implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  punti_scuola, " +
		"  dt_inizio_validita, " +
		"  dt_fine_validita, " +
		"  id_punteggio, " +
		"  id_scuola " +
		"from iscritto_r_punteggio_scu ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_r_punteggio_scu (" +
		"  punti_scuola, " +
		"  dt_inizio_validita, " +
		"  dt_fine_validita, " +
		"  id_punteggio, " +
		"  id_scuola " +
		") " +
		"values (" +
		"  :puntiScuola, " +
		"  :dtInizioValidita, " +
		"  :dtFineValidita, " +
		"  :idPunteggio, " +
		"  :idScuola " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_r_punteggio_scu where " +
		"  id_punteggio = :idPunteggio and " +
		"  id_scuola = :idScuola ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_r_punteggio_scu";

	//////////////////////////////////////////////////////////////////////


    private Long       idPunteggio  ; // Id or Primary Key
    private Long       idScuola     ; // Id or Primary Key

    private Integer    puntiScuola  ;
    private Date       dtInizioValidita ;
    private Date       dtFineValidita ;

    /**
     * Set the "idPunteggio" field value
     * This field is mapped on the database column "id_punteggio" ( type "int4", NotNull : true )
     * @param idPunteggio
     */
	public void setIdPunteggio(Long idPunteggio) {
        this.idPunteggio = idPunteggio ;
    }

    /**
     * Get the "idPunteggio" field value
     * This field is mapped on the database column "id_punteggio" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdPunteggio() {
        return this.idPunteggio;
    }
    /**
     * Set the "idScuola" field value
     * This field is mapped on the database column "id_scuola" ( type "int4", NotNull : true )
     * @param idScuola
     */
	public void setIdScuola(Long idScuola) {
        this.idScuola = idScuola ;
    }

    /**
     * Get the "idScuola" field value
     * This field is mapped on the database column "id_scuola" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdScuola() {
        return this.idScuola;
    }

    /**
     * Set the "puntiScuola" field value
     * This field is mapped on the database column "punti_scuola" ( type "int4", NotNull : true )
     * @param puntiScuola
     */
    public void setPuntiScuola(Integer puntiScuola) {
        this.puntiScuola = puntiScuola;
    }

    /**
     * Get the "puntiScuola" field value
     * This field is mapped on the database column "punti_scuola" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Integer getPuntiScuola() {
        return this.puntiScuola;
    }

    /**
     * Set the "dtInizioValidita" field value
     * This field is mapped on the database column "dt_inizio_validita" ( type "timestamp", NotNull : true )
     * @param dtInizioValidita
     */
    public void setDtInizioValidita(Date dtInizioValidita) {
        this.dtInizioValidita = dtInizioValidita;
    }

    /**
     * Get the "dtInizioValidita" field value
     * This field is mapped on the database column "dt_inizio_validita" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtInizioValidita() {
        return this.dtInizioValidita;
    }

    /**
     * Set the "dtFineValidita" field value
     * This field is mapped on the database column "dt_fine_validita" ( type "timestamp", NotNull : false )
     * @param dtFineValidita
     */
    public void setDtFineValidita(Date dtFineValidita) {
        this.dtFineValidita = dtFineValidita;
    }

    /**
     * Get the "dtFineValidita" field value
     * This field is mapped on the database column "dt_fine_validita" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtFineValidita() {
        return this.dtFineValidita;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(puntiScuola);
        sb.append("|");
        sb.append(dtInizioValidita);
        sb.append("|");
        sb.append(dtFineValidita);
        sb.append("|");
        sb.append(idPunteggio);
        sb.append("|");
        sb.append(idScuola);
        return sb.toString(); 
    } 

}
