/*
 * Java bean class for entity "iscritto_t_condizione_san"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_condizione_san"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTCondizioneSan implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  fl_disabilita, " +
		"  fl_problemi_salute, " +
		"  fl_stato_gravidanza, " +
		"  id_anagrafica_soggetto " +
		"from iscritto_t_condizione_san ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_condizione_san (" +
		"  fl_disabilita, " +
		"  fl_problemi_salute, " +
		"  fl_stato_gravidanza, " +
		"  id_anagrafica_soggetto " +
		") " +
		"values (" +
		"  :flDisabilita, " +
		"  :flProblemiSalute, " +
		"  :flStatoGravidanza, " +
		"  :idAnagraficaSoggetto " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_condizione_san where " +
		"  id_anagrafica_soggetto = :idAnagraficaSoggetto ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_condizione_san";

	//////////////////////////////////////////////////////////////////////


    private Long       idAnagraficaSoggetto ; // Id or Primary Key

    private String     flDisabilita ;
    private String     flProblemiSalute ;
    private String     flStatoGravidanza ;

    /**
     * Set the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : true )
     * @param idAnagraficaSoggetto
     */
	public void setIdAnagraficaSoggetto(Long idAnagraficaSoggetto) {
        this.idAnagraficaSoggetto = idAnagraficaSoggetto ;
    }

    /**
     * Get the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdAnagraficaSoggetto() {
        return this.idAnagraficaSoggetto;
    }

    /**
     * Set the "flDisabilita" field value
     * This field is mapped on the database column "fl_disabilita" ( type "bytea", NotNull : true )
     * @param flDisabilita
     */
    public void setFlDisabilita(String flDisabilita) {
        this.flDisabilita = flDisabilita;
    }

    /**
     * Get the "flDisabilita" field value
     * This field is mapped on the database column "fl_disabilita" ( type "bytea", NotNull : true )
     * @return the field value
     */
    public String getFlDisabilita() {
        return this.flDisabilita;
    }

    /**
     * Set the "flProblemiSalute" field value
     * This field is mapped on the database column "fl_problemi_salute" ( type "bytea", NotNull : true )
     * @param flProblemiSalute
     */
    public void setFlProblemiSalute(String flProblemiSalute) {
        this.flProblemiSalute = flProblemiSalute;
    }

    /**
     * Get the "flProblemiSalute" field value
     * This field is mapped on the database column "fl_problemi_salute" ( type "bytea", NotNull : true )
     * @return the field value
     */
    public String getFlProblemiSalute() {
        return this.flProblemiSalute;
    }

    /**
     * Set the "flStatoGravidanza" field value
     * This field is mapped on the database column "fl_stato_gravidanza" ( type "bytea", NotNull : true )
     * @param flStatoGravidanza
     */
    public void setFlStatoGravidanza(String flStatoGravidanza) {
        this.flStatoGravidanza = flStatoGravidanza;
    }

    /**
     * Get the "flStatoGravidanza" field value
     * This field is mapped on the database column "fl_stato_gravidanza" ( type "bytea", NotNull : true )
     * @return the field value
     */
    public String getFlStatoGravidanza() {
        return this.flStatoGravidanza;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(flDisabilita);
        sb.append("|");
        sb.append(flProblemiSalute);
        sb.append("|");
        sb.append(flStatoGravidanza);
        sb.append("|");
        sb.append(idAnagraficaSoggetto);
        return sb.toString(); 
    } 

}
