/*
 * Java bean class for entity "iscritto_t_anagrafica_gra"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_anagrafica_gra"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTAnagraficaGra implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_anagrafica_gra, " +
		"  cod_anagrafica_gra, " +
		"  dt_inizio_iscr, " +
		"  dt_scadenza_iscr, " +
		"  dt_fine_iscr, " +
		"  dt_scadenza_grad, " +
		"  dt_scadenza_ricorsi, " +
		"  id_anno_scolastico, " +
		"  id_ordine_scuola " +
		"from iscritto_t_anagrafica_gra ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_anagrafica_gra (" +
		"  id_anagrafica_gra, " +
		"  cod_anagrafica_gra, " +
		"  dt_inizio_iscr, " +
		"  dt_scadenza_iscr, " +
		"  dt_fine_iscr, " +
		"  dt_scadenza_grad, " +
		"  dt_scadenza_ricorsi, " +
		"  id_anno_scolastico, " +
		"  id_ordine_scuola " +
		") " +
		"values (" +
		"  :idAnagraficaGra, " +
		"  :codAnagraficaGra, " +
		"  :dtInizioIscr, " +
		"  :dtScadenzaIscr, " +
		"  :dtFineIscr, " +
		"  :dtScadenzaGrad, " +
		"  :dtScadenzaRicorsi, " +
		"  :idAnnoScolastico, " +
		"  :idOrdineScuola " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_anagrafica_gra where " +
		"  id_anagrafica_gra = :idAnagraficaGra ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_anagrafica_gra";

	//////////////////////////////////////////////////////////////////////


    private Long       idAnagraficaGra ; // Id or Primary Key

    private String     codAnagraficaGra ;
    private Date       dtInizioIscr ;
    private Date       dtScadenzaIscr ;
    private Date       dtFineIscr   ;
    private Date       dtScadenzaGrad ;
    private Date       dtScadenzaRicorsi ;
    private Long       idAnnoScolastico ;
    private Long       idOrdineScuola ;

    /**
     * Set the "idAnagraficaGra" field value
     * This field is mapped on the database column "id_anagrafica_gra" ( type "int4", NotNull : true )
     * @param idAnagraficaGra
     */
	public void setIdAnagraficaGra(Long idAnagraficaGra) {
        this.idAnagraficaGra = idAnagraficaGra ;
    }

    /**
     * Get the "idAnagraficaGra" field value
     * This field is mapped on the database column "id_anagrafica_gra" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdAnagraficaGra() {
        return this.idAnagraficaGra;
    }

    /**
     * Set the "codAnagraficaGra" field value
     * This field is mapped on the database column "cod_anagrafica_gra" ( type "varchar", NotNull : true )
     * @param codAnagraficaGra
     */
    public void setCodAnagraficaGra(String codAnagraficaGra) {
        this.codAnagraficaGra = codAnagraficaGra;
    }

    /**
     * Get the "codAnagraficaGra" field value
     * This field is mapped on the database column "cod_anagrafica_gra" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodAnagraficaGra() {
        return this.codAnagraficaGra;
    }

    /**
     * Set the "dtInizioIscr" field value
     * This field is mapped on the database column "dt_inizio_iscr" ( type "timestamp", NotNull : true )
     * @param dtInizioIscr
     */
    public void setDtInizioIscr(Date dtInizioIscr) {
        this.dtInizioIscr = dtInizioIscr;
    }

    /**
     * Get the "dtInizioIscr" field value
     * This field is mapped on the database column "dt_inizio_iscr" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtInizioIscr() {
        return this.dtInizioIscr;
    }

    /**
     * Set the "dtScadenzaIscr" field value
     * This field is mapped on the database column "dt_scadenza_iscr" ( type "timestamp", NotNull : true )
     * @param dtScadenzaIscr
     */
    public void setDtScadenzaIscr(Date dtScadenzaIscr) {
        this.dtScadenzaIscr = dtScadenzaIscr;
    }

    /**
     * Get the "dtScadenzaIscr" field value
     * This field is mapped on the database column "dt_scadenza_iscr" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtScadenzaIscr() {
        return this.dtScadenzaIscr;
    }

    /**
     * Set the "dtFineIscr" field value
     * This field is mapped on the database column "dt_fine_iscr" ( type "timestamp", NotNull : true )
     * @param dtFineIscr
     */
    public void setDtFineIscr(Date dtFineIscr) {
        this.dtFineIscr = dtFineIscr;
    }

    /**
     * Get the "dtFineIscr" field value
     * This field is mapped on the database column "dt_fine_iscr" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtFineIscr() {
        return this.dtFineIscr;
    }

    /**
     * Set the "dtScadenzaGrad" field value
     * This field is mapped on the database column "dt_scadenza_grad" ( type "timestamp", NotNull : true )
     * @param dtScadenzaGrad
     */
    public void setDtScadenzaGrad(Date dtScadenzaGrad) {
        this.dtScadenzaGrad = dtScadenzaGrad;
    }

    /**
     * Get the "dtScadenzaGrad" field value
     * This field is mapped on the database column "dt_scadenza_grad" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtScadenzaGrad() {
        return this.dtScadenzaGrad;
    }

    /**
     * Set the "dtScadenzaRicorsi" field value
     * This field is mapped on the database column "dt_scadenza_ricorsi" ( type "timestamp", NotNull : true )
     * @param dtScadenzaRicorsi
     */
    public void setDtScadenzaRicorsi(Date dtScadenzaRicorsi) {
        this.dtScadenzaRicorsi = dtScadenzaRicorsi;
    }

    /**
     * Get the "dtScadenzaRicorsi" field value
     * This field is mapped on the database column "dt_scadenza_ricorsi" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtScadenzaRicorsi() {
        return this.dtScadenzaRicorsi;
    }

    /**
     * Set the "idAnnoScolastico" field value
     * This field is mapped on the database column "id_anno_scolastico" ( type "int4", NotNull : true )
     * @param idAnnoScolastico
     */
    public void setIdAnnoScolastico(Long idAnnoScolastico) {
        this.idAnnoScolastico = idAnnoScolastico;
    }

    /**
     * Get the "idAnnoScolastico" field value
     * This field is mapped on the database column "id_anno_scolastico" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdAnnoScolastico() {
        return this.idAnnoScolastico;
    }

    /**
     * Set the "idOrdineScuola" field value
     * This field is mapped on the database column "id_ordine_scuola" ( type "int4", NotNull : true )
     * @param idOrdineScuola
     */
    public void setIdOrdineScuola(Long idOrdineScuola) {
        this.idOrdineScuola = idOrdineScuola;
    }

    /**
     * Get the "idOrdineScuola" field value
     * This field is mapped on the database column "id_ordine_scuola" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdOrdineScuola() {
        return this.idOrdineScuola;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idAnagraficaGra);
        sb.append("|");
        sb.append(codAnagraficaGra);
        sb.append("|");
        sb.append(dtInizioIscr);
        sb.append("|");
        sb.append(dtScadenzaIscr);
        sb.append("|");
        sb.append(dtFineIscr);
        sb.append("|");
        sb.append(dtScadenzaGrad);
        sb.append("|");
        sb.append(dtScadenzaRicorsi);
        sb.append("|");
        sb.append(idAnnoScolastico);
        sb.append("|");
        sb.append(idOrdineScuola);
        return sb.toString(); 
    } 

}
