/*
 * Java bean class for entity "iscritto_t_cambio_res"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_cambio_res"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTCambioRes implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_domanda_iscrizione, " +
		"  id_tipo_cambio_res, " +
		"  dt_variazione, " +
		"  dt_appuntamento, " +
		"  motivazione, " +
		"  indirizzo " +
		"from iscritto_t_cambio_res ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_cambio_res (" +
		"  id_domanda_iscrizione, " +
		"  id_tipo_cambio_res, " +
		"  dt_variazione, " +
		"  dt_appuntamento, " +
		"  motivazione, " +
		"  indirizzo " +
		") " +
		"values (" +
		"  :idDomandaIscrizione, " +
		"  :idTipoCambioRes, " +
		"  :dtVariazione, " +
		"  :dtAppuntamento, " +
		"  :motivazione, " +
		"  :indirizzo " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_cambio_res where " +
		"  id_domanda_iscrizione = :idDomandaIscrizione ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_cambio_res";

	//////////////////////////////////////////////////////////////////////


    private Long       idDomandaIscrizione ; // Id or Primary Key

    private Long       idTipoCambioRes ;
    private Date       dtVariazione ;
    private Date       dtAppuntamento ;
    private String     motivazione  ;
    private String 	   indirizzo;

    public String getIndirizzo() {
		return indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	/**
     * Set the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @param idDomandaIscrizione
     */
	public void setIdDomandaIscrizione(Long idDomandaIscrizione) {
        this.idDomandaIscrizione = idDomandaIscrizione ;
    }

    /**
     * Get the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdDomandaIscrizione() {
        return this.idDomandaIscrizione;
    }

    /**
     * Set the "idTipoCambioRes" field value
     * This field is mapped on the database column "id_tipo_cambio_res" ( type "int4", NotNull : false )
     * @param idTipoCambioRes
     */
    public void setIdTipoCambioRes(Long idTipoCambioRes) {
        this.idTipoCambioRes = idTipoCambioRes;
    }

    /**
     * Get the "idTipoCambioRes" field value
     * This field is mapped on the database column "id_tipo_cambio_res" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdTipoCambioRes() {
        return this.idTipoCambioRes;
    }

    /**
     * Set the "dtVariazione" field value
     * This field is mapped on the database column "dt_variazione" ( type "timestamp", NotNull : false )
     * @param dtVariazione
     */
    public void setDtVariazione(Date dtVariazione) {
        this.dtVariazione = dtVariazione;
    }

    /**
     * Get the "dtVariazione" field value
     * This field is mapped on the database column "dt_variazione" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtVariazione() {
        return this.dtVariazione;
    }

    /**
     * Set the "dtAppuntamento" field value
     * This field is mapped on the database column "dt_appuntamento" ( type "timestamp", NotNull : false )
     * @param dtAppuntamento
     */
    public void setDtAppuntamento(Date dtAppuntamento) {
        this.dtAppuntamento = dtAppuntamento;
    }

    /**
     * Get the "dtAppuntamento" field value
     * This field is mapped on the database column "dt_appuntamento" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtAppuntamento() {
        return this.dtAppuntamento;
    }

    /**
     * Set the "motivazione" field value
     * This field is mapped on the database column "motivazione" ( type "varchar", NotNull : false )
     * @param motivazione
     */
    public void setMotivazione(String motivazione) {
        this.motivazione = motivazione;
    }

    /**
     * Get the "motivazione" field value
     * This field is mapped on the database column "motivazione" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getMotivazione() {
        return this.motivazione;
    }


    @Override
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(idDomandaIscrizione);
        sb.append("|");
        sb.append(idTipoCambioRes);
        sb.append("|");
        sb.append(dtVariazione);
        sb.append("|");
        sb.append(dtAppuntamento);
        sb.append("|");
        sb.append(motivazione);
        sb.append("|");
        sb.append(indirizzo);
        return sb.toString();
    }

}
