/*
 * Java bean class for entity "iscritto_d_genitore_sol"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_genitore_sol"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDGenitoreSol implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_tipo_genitore_solo, " +
		"  cod_tipo_genitore_solo, " +
		"  descrizione " +
		"from iscritto_d_genitore_sol ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_genitore_sol (" +
		"  id_tipo_genitore_solo, " +
		"  cod_tipo_genitore_solo, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idTipoGenitoreSolo, " +
		"  :codTipoGenitoreSolo, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_genitore_sol where " +
		"  id_tipo_genitore_solo = :idTipoGenitoreSolo ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_genitore_sol";

	//////////////////////////////////////////////////////////////////////


    private Long       idTipoGenitoreSolo ; // Id or Primary Key

    private String     codTipoGenitoreSolo ;
    private String     descrizione  ;

    /**
     * Set the "idTipoGenitoreSolo" field value
     * This field is mapped on the database column "id_tipo_genitore_solo" ( type "int4", NotNull : true )
     * @param idTipoGenitoreSolo
     */
	public void setIdTipoGenitoreSolo(Long idTipoGenitoreSolo) {
        this.idTipoGenitoreSolo = idTipoGenitoreSolo ;
    }

    /**
     * Get the "idTipoGenitoreSolo" field value
     * This field is mapped on the database column "id_tipo_genitore_solo" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdTipoGenitoreSolo() {
        return this.idTipoGenitoreSolo;
    }

    /**
     * Set the "codTipoGenitoreSolo" field value
     * This field is mapped on the database column "cod_tipo_genitore_solo" ( type "varchar", NotNull : true )
     * @param codTipoGenitoreSolo
     */
    public void setCodTipoGenitoreSolo(String codTipoGenitoreSolo) {
        this.codTipoGenitoreSolo = codTipoGenitoreSolo;
    }

    /**
     * Get the "codTipoGenitoreSolo" field value
     * This field is mapped on the database column "cod_tipo_genitore_solo" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodTipoGenitoreSolo() {
        return this.codTipoGenitoreSolo;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTipoGenitoreSolo);
        sb.append("|");
        sb.append(codTipoGenitoreSolo);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
