/*
 * Java bean class for entity "iscritto_d_tipo_all"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_tipo_all"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDTipoAll implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_tipo_allegato, " +
		"  cod_tipo_allegato, " +
		"  descrizione " +
		"from iscritto_d_tipo_all ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_tipo_all (" +
		"  id_tipo_allegato, " +
		"  cod_tipo_allegato, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idTipoAllegato, " +
		"  :codTipoAllegato, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_tipo_all where " +
		"  id_tipo_allegato = :idTipoAllegato ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_tipo_all";

	//////////////////////////////////////////////////////////////////////


    private Long       idTipoAllegato ; // Id or Primary Key

    private String     codTipoAllegato ;
    private String     descrizione  ;

    /**
     * Set the "idTipoAllegato" field value
     * This field is mapped on the database column "id_tipo_allegato" ( type "int4", NotNull : true )
     * @param idTipoAllegato
     */
	public void setIdTipoAllegato(Long idTipoAllegato) {
        this.idTipoAllegato = idTipoAllegato ;
    }

    /**
     * Get the "idTipoAllegato" field value
     * This field is mapped on the database column "id_tipo_allegato" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdTipoAllegato() {
        return this.idTipoAllegato;
    }

    /**
     * Set the "codTipoAllegato" field value
     * This field is mapped on the database column "cod_tipo_allegato" ( type "varchar", NotNull : true )
     * @param codTipoAllegato
     */
    public void setCodTipoAllegato(String codTipoAllegato) {
        this.codTipoAllegato = codTipoAllegato;
    }

    /**
     * Get the "codTipoAllegato" field value
     * This field is mapped on the database column "cod_tipo_allegato" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodTipoAllegato() {
        return this.codTipoAllegato;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTipoAllegato);
        sb.append("|");
        sb.append(codTipoAllegato);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
