/*
 * Java bean class for entity "iscritto_d_tipo_fre"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_tipo_fre"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDTipoFre implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  cod_tipo_frequenza, " +
		"  descrizione, " +
		"  id_tipo_frequenza " +
		"from iscritto_d_tipo_fre ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_tipo_fre (" +
		"  cod_tipo_frequenza, " +
		"  descrizione, " +
		"  id_tipo_frequenza " +
		") " +
		"values (" +
		"  :codTipoFrequenza, " +
		"  :descrizione, " +
		"  :idTipoFrequenza " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_tipo_fre where " +
		"  id_tipo_frequenza = :idTipoFrequenza ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_tipo_fre";

	//////////////////////////////////////////////////////////////////////


    private Long       idTipoFrequenza ; // Id or Primary Key

    private String     codTipoFrequenza ;
    private String     descrizione  ;

    /**
     * Set the "idTipoFrequenza" field value
     * This field is mapped on the database column "id_tipo_frequenza" ( type "int4", NotNull : true )
     * @param idTipoFrequenza
     */
	public void setIdTipoFrequenza(Long idTipoFrequenza) {
        this.idTipoFrequenza = idTipoFrequenza ;
    }

    /**
     * Get the "idTipoFrequenza" field value
     * This field is mapped on the database column "id_tipo_frequenza" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdTipoFrequenza() {
        return this.idTipoFrequenza;
    }

    /**
     * Set the "codTipoFrequenza" field value
     * This field is mapped on the database column "cod_tipo_frequenza" ( type "varchar", NotNull : true )
     * @param codTipoFrequenza
     */
    public void setCodTipoFrequenza(String codTipoFrequenza) {
        this.codTipoFrequenza = codTipoFrequenza;
    }

    /**
     * Get the "codTipoFrequenza" field value
     * This field is mapped on the database column "cod_tipo_frequenza" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodTipoFrequenza() {
        return this.codTipoFrequenza;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(codTipoFrequenza);
        sb.append("|");
        sb.append(descrizione);
        sb.append("|");
        sb.append(idTipoFrequenza);
        return sb.toString(); 
    } 

}
