/*
 * Java bean class for entity "iscritto_t_anagrafica_sog"
 * Created on 2020-01-30 ( Date ISO 2020-01-30 - Time 14:08:33 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_anagrafica_sog"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTAnagraficaSog implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  cognome, " +
		"  nome, " +
		"  data_nascita, " +
		"  codice_fiscale, " +
		"  sesso, " +
		"  id_domanda_iscrizione, " +
		"  id_anagrafica_soggetto, " +
		"  fl_residenza_nao, " +
		"  id_rel_parentela, " +
		"  id_stato_citt, " +
		"  id_comune_nascita, " +
		"  id_stato_nascita, " +
		"  ora_nascita " +
		"from iscritto_t_anagrafica_sog ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_anagrafica_sog (" +
		"  cognome, " +
		"  nome, " +
		"  data_nascita, " +
		"  codice_fiscale, " +
		"  sesso, " +
		"  id_domanda_iscrizione, " +
		"  id_anagrafica_soggetto, " +
		"  fl_residenza_nao, " +
		"  id_rel_parentela, " +
		"  id_stato_citt, " +
		"  id_comune_nascita, " +
		"  id_stato_nascita, " +
		"  ora_nascita " +
		") " +
		"values (" +
		"  :cognome, " +
		"  :nome, " +
		"  :dataNascita, " +
		"  :codiceFiscale, " +
		"  :sesso, " +
		"  :idDomandaIscrizione, " +
		"  :idAnagraficaSoggetto, " +
		"  :flResidenzaNao, " +
		"  :idRelParentela, " +
		"  :idStatoCitt, " +
		"  :idComuneNascita, " +
		"  :idStatoNascita, " +
		"  :oraNascita " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_anagrafica_sog where " +
		"  id_anagrafica_soggetto = :idAnagraficaSoggetto ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_anagrafica_sog";

	//////////////////////////////////////////////////////////////////////


    private Long       idAnagraficaSoggetto ; // Id or Primary Key

    private String     cognome      ;
    private String     nome         ;
    private Date       dataNascita  ;
    private String     codiceFiscale ;
    private String     sesso        ;
    private Long       idDomandaIscrizione ;
    private String     flResidenzaNao ;
    private Long       idRelParentela ;
    private Long       idStatoCitt  ;
    private Long       idComuneNascita ;
    private Long       idStatoNascita ;
    private String     oraNascita   ;

    /**
     * Set the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : true )
     * @param idAnagraficaSoggetto
     */
	public void setIdAnagraficaSoggetto(Long idAnagraficaSoggetto) {
        this.idAnagraficaSoggetto = idAnagraficaSoggetto ;
    }

    /**
     * Get the "idAnagraficaSoggetto" field value
     * This field is mapped on the database column "id_anagrafica_soggetto" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdAnagraficaSoggetto() {
        return this.idAnagraficaSoggetto;
    }

    /**
     * Set the "cognome" field value
     * This field is mapped on the database column "cognome" ( type "varchar", NotNull : true )
     * @param cognome
     */
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    /**
     * Get the "cognome" field value
     * This field is mapped on the database column "cognome" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCognome() {
        return this.cognome;
    }

    /**
     * Set the "nome" field value
     * This field is mapped on the database column "nome" ( type "varchar", NotNull : true )
     * @param nome
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * Get the "nome" field value
     * This field is mapped on the database column "nome" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getNome() {
        return this.nome;
    }

    /**
     * Set the "dataNascita" field value
     * This field is mapped on the database column "data_nascita" ( type "timestamp", NotNull : false )
     * @param dataNascita
     */
    public void setDataNascita(Date dataNascita) {
        this.dataNascita = dataNascita;
    }

    /**
     * Get the "dataNascita" field value
     * This field is mapped on the database column "data_nascita" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDataNascita() {
        return this.dataNascita;
    }

    /**
     * Set the "codiceFiscale" field value
     * This field is mapped on the database column "codice_fiscale" ( type "varchar", NotNull : false )
     * @param codiceFiscale
     */
    public void setCodiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }

    /**
     * Get the "codiceFiscale" field value
     * This field is mapped on the database column "codice_fiscale" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getCodiceFiscale() {
        return this.codiceFiscale;
    }

    /**
     * Set the "sesso" field value
     * This field is mapped on the database column "sesso" ( type "varchar", NotNull : false )
     * @param sesso
     */
    public void setSesso(String sesso) {
        this.sesso = sesso;
    }

    /**
     * Get the "sesso" field value
     * This field is mapped on the database column "sesso" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getSesso() {
        return this.sesso;
    }

    /**
     * Set the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @param idDomandaIscrizione
     */
    public void setIdDomandaIscrizione(Long idDomandaIscrizione) {
        this.idDomandaIscrizione = idDomandaIscrizione;
    }

    /**
     * Get the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdDomandaIscrizione() {
        return this.idDomandaIscrizione;
    }

    /**
     * Set the "flResidenzaNao" field value
     * This field is mapped on the database column "fl_residenza_nao" ( type "varchar", NotNull : false )
     * @param flResidenzaNao
     */
    public void setFlResidenzaNao(String flResidenzaNao) {
        this.flResidenzaNao = flResidenzaNao;
    }

    /**
     * Get the "flResidenzaNao" field value
     * This field is mapped on the database column "fl_residenza_nao" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlResidenzaNao() {
        return this.flResidenzaNao;
    }

    /**
     * Set the "idRelParentela" field value
     * This field is mapped on the database column "id_rel_parentela" ( type "int4", NotNull : false )
     * @param idRelParentela
     */
    public void setIdRelParentela(Long idRelParentela) {
        this.idRelParentela = idRelParentela;
    }

    /**
     * Get the "idRelParentela" field value
     * This field is mapped on the database column "id_rel_parentela" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdRelParentela() {
        return this.idRelParentela;
    }

    /**
     * Set the "idStatoCitt" field value
     * This field is mapped on the database column "id_stato_citt" ( type "int4", NotNull : false )
     * @param idStatoCitt
     */
    public void setIdStatoCitt(Long idStatoCitt) {
        this.idStatoCitt = idStatoCitt;
    }

    /**
     * Get the "idStatoCitt" field value
     * This field is mapped on the database column "id_stato_citt" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdStatoCitt() {
        return this.idStatoCitt;
    }

    /**
     * Set the "idComuneNascita" field value
     * This field is mapped on the database column "id_comune_nascita" ( type "int4", NotNull : false )
     * @param idComuneNascita
     */
    public void setIdComuneNascita(Long idComuneNascita) {
        this.idComuneNascita = idComuneNascita;
    }

    /**
     * Get the "idComuneNascita" field value
     * This field is mapped on the database column "id_comune_nascita" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdComuneNascita() {
        return this.idComuneNascita;
    }

    /**
     * Set the "idStatoNascita" field value
     * This field is mapped on the database column "id_stato_nascita" ( type "int4", NotNull : false )
     * @param idStatoNascita
     */
    public void setIdStatoNascita(Long idStatoNascita) {
        this.idStatoNascita = idStatoNascita;
    }

    /**
     * Get the "idStatoNascita" field value
     * This field is mapped on the database column "id_stato_nascita" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdStatoNascita() {
        return this.idStatoNascita;
    }

    /**
     * Set the "oraNascita" field value
     * This field is mapped on the database column "ora_nascita" ( type "varchar", NotNull : false )
     * @param oraNascita
     */
    public void setOraNascita(String oraNascita) {
        this.oraNascita = oraNascita;
    }

    /**
     * Get the "oraNascita" field value
     * This field is mapped on the database column "ora_nascita" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getOraNascita() {
        return this.oraNascita;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(cognome);
        sb.append("|");
        sb.append(nome);
        sb.append("|");
        sb.append(dataNascita);
        sb.append("|");
        sb.append(codiceFiscale);
        sb.append("|");
        sb.append(sesso);
        sb.append("|");
        sb.append(idDomandaIscrizione);
        sb.append("|");
        sb.append(idAnagraficaSoggetto);
        sb.append("|");
        sb.append(flResidenzaNao);
        sb.append("|");
        sb.append(idRelParentela);
        sb.append("|");
        sb.append(idStatoCitt);
        sb.append("|");
        sb.append(idComuneNascita);
        sb.append("|");
        sb.append(idStatoNascita);
        sb.append("|");
        sb.append(oraNascita);
        return sb.toString(); 
    } 

}
