/*
 * Java bean class for entity "iscritto_t_disoccupato_ex"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_disoccupato_ex"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTDisoccupatoEx implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  azienda_piva_cf, " +
		"  comune_lavoro, " +
		"  indirizzo, " +
		"  lavoro_dal, " +
		"  lavoro_al, " +
		"  id_disoccupato_ex_lav, " +
		"  id_condizione_occupazionale " +
		"from iscritto_t_disoccupato_ex ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_disoccupato_ex (" +
		"  azienda_piva_cf, " +
		"  comune_lavoro, " +
		"  indirizzo, " +
		"  lavoro_dal, " +
		"  lavoro_al, " +
		"  id_disoccupato_ex_lav, " +
		"  id_condizione_occupazionale " +
		") " +
		"values (" +
		"  :aziendaPivaCf, " +
		"  :comuneLavoro, " +
		"  :indirizzo, " +
		"  :lavoroDal, " +
		"  :lavoroAl, " +
		"  :idDisoccupatoExLav, " +
		"  :idCondizioneOccupazionale " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_disoccupato_ex where " +
		"  id_disoccupato_ex_lav = :idDisoccupatoExLav ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_disoccupato_ex";

	//////////////////////////////////////////////////////////////////////


    private Long       idDisoccupatoExLav ; // Id or Primary Key

    private String     aziendaPivaCf ;
    private String     comuneLavoro ;
    private String     indirizzo    ;
    private Date       lavoroDal    ;
    private Date       lavoroAl     ;
    private Long       idCondizioneOccupazionale ;

    /**
     * Set the "idDisoccupatoExLav" field value
     * This field is mapped on the database column "id_disoccupato_ex_lav" ( type "int4", NotNull : true )
     * @param idDisoccupatoExLav
     */
	public void setIdDisoccupatoExLav(Long idDisoccupatoExLav) {
        this.idDisoccupatoExLav = idDisoccupatoExLav ;
    }

    /**
     * Get the "idDisoccupatoExLav" field value
     * This field is mapped on the database column "id_disoccupato_ex_lav" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdDisoccupatoExLav() {
        return this.idDisoccupatoExLav;
    }

    /**
     * Set the "aziendaPivaCf" field value
     * This field is mapped on the database column "azienda_piva_cf" ( type "varchar", NotNull : true )
     * @param aziendaPivaCf
     */
    public void setAziendaPivaCf(String aziendaPivaCf) {
        this.aziendaPivaCf = aziendaPivaCf;
    }

    /**
     * Get the "aziendaPivaCf" field value
     * This field is mapped on the database column "azienda_piva_cf" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getAziendaPivaCf() {
        return this.aziendaPivaCf;
    }

    /**
     * Set the "comuneLavoro" field value
     * This field is mapped on the database column "comune_lavoro" ( type "varchar", NotNull : true )
     * @param comuneLavoro
     */
    public void setComuneLavoro(String comuneLavoro) {
        this.comuneLavoro = comuneLavoro;
    }

    /**
     * Get the "comuneLavoro" field value
     * This field is mapped on the database column "comune_lavoro" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getComuneLavoro() {
        return this.comuneLavoro;
    }

    /**
     * Set the "indirizzo" field value
     * This field is mapped on the database column "indirizzo" ( type "varchar", NotNull : false )
     * @param indirizzo
     */
    public void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }

    /**
     * Get the "indirizzo" field value
     * This field is mapped on the database column "indirizzo" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getIndirizzo() {
        return this.indirizzo;
    }

    /**
     * Set the "lavoroDal" field value
     * This field is mapped on the database column "lavoro_dal" ( type "timestamp", NotNull : true )
     * @param lavoroDal
     */
    public void setLavoroDal(Date lavoroDal) {
        this.lavoroDal = lavoroDal;
    }

    /**
     * Get the "lavoroDal" field value
     * This field is mapped on the database column "lavoro_dal" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getLavoroDal() {
        return this.lavoroDal;
    }

    /**
     * Set the "lavoroAl" field value
     * This field is mapped on the database column "lavoro_al" ( type "timestamp", NotNull : true )
     * @param lavoroAl
     */
    public void setLavoroAl(Date lavoroAl) {
        this.lavoroAl = lavoroAl;
    }

    /**
     * Get the "lavoroAl" field value
     * This field is mapped on the database column "lavoro_al" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getLavoroAl() {
        return this.lavoroAl;
    }

    /**
     * Set the "idCondizioneOccupazionale" field value
     * This field is mapped on the database column "id_condizione_occupazionale" ( type "int4", NotNull : true )
     * @param idCondizioneOccupazionale
     */
    public void setIdCondizioneOccupazionale(Long idCondizioneOccupazionale) {
        this.idCondizioneOccupazionale = idCondizioneOccupazionale;
    }

    /**
     * Get the "idCondizioneOccupazionale" field value
     * This field is mapped on the database column "id_condizione_occupazionale" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdCondizioneOccupazionale() {
        return this.idCondizioneOccupazionale;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(aziendaPivaCf);
        sb.append("|");
        sb.append(comuneLavoro);
        sb.append("|");
        sb.append(indirizzo);
        sb.append("|");
        sb.append(lavoroDal);
        sb.append("|");
        sb.append(lavoroAl);
        sb.append("|");
        sb.append(idDisoccupatoExLav);
        sb.append("|");
        sb.append(idCondizioneOccupazionale);
        return sb.toString(); 
    } 

}
