/*
 * Java bean class for entity "iscritto_t_classe"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_classe"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTClasse implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_classe, " +
		"  id_scuola, " +
		"  posti_liberi, " +
		"  posti_ammessi, " +
		"  denominazione, " +
		"  id_anno_scolastico, " +
		"  id_tipo_frequenza, " +
		"  id_eta, " +
		"  fl_ammissione_dis " +
		"from iscritto_t_classe ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_classe (" +
		"  id_classe, " +
		"  id_scuola, " +
		"  posti_liberi, " +
		"  posti_ammessi, " +
		"  denominazione, " +
		"  id_anno_scolastico, " +
		"  id_tipo_frequenza, " +
		"  id_eta, " +
		"  fl_ammissione_dis " +
		") " +
		"values (" +
		"  :idClasse, " +
		"  :idScuola, " +
		"  :postiLiberi, " +
		"  :postiAmmessi, " +
		"  :denominazione, " +
		"  :idAnnoScolastico, " +
		"  :idTipoFrequenza, " +
		"  :idEta, " +
		"  :flAmmissioneDis " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_classe where " +
		"  id_classe = :idClasse ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_classe";

	//////////////////////////////////////////////////////////////////////


    private Long       idClasse     ; // Id or Primary Key

    private Long       idScuola     ;
    private Integer    postiLiberi  ;
    private Integer    postiAmmessi ;
    private String     denominazione ;
    private Long       idAnnoScolastico ;
    private Long       idTipoFrequenza ;
    private Long       idEta        ;
    private String     flAmmissioneDis ;

    /**
     * Set the "idClasse" field value
     * This field is mapped on the database column "id_classe" ( type "int4", NotNull : true )
     * @param idClasse
     */
	public void setIdClasse(Long idClasse) {
        this.idClasse = idClasse ;
    }

    /**
     * Get the "idClasse" field value
     * This field is mapped on the database column "id_classe" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdClasse() {
        return this.idClasse;
    }

    /**
     * Set the "idScuola" field value
     * This field is mapped on the database column "id_scuola" ( type "int4", NotNull : true )
     * @param idScuola
     */
    public void setIdScuola(Long idScuola) {
        this.idScuola = idScuola;
    }

    /**
     * Get the "idScuola" field value
     * This field is mapped on the database column "id_scuola" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdScuola() {
        return this.idScuola;
    }

    /**
     * Set the "postiLiberi" field value
     * This field is mapped on the database column "posti_liberi" ( type "int4", NotNull : true )
     * @param postiLiberi
     */
    public void setPostiLiberi(Integer postiLiberi) {
        this.postiLiberi = postiLiberi;
    }

    /**
     * Get the "postiLiberi" field value
     * This field is mapped on the database column "posti_liberi" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Integer getPostiLiberi() {
        return this.postiLiberi;
    }

    /**
     * Set the "postiAmmessi" field value
     * This field is mapped on the database column "posti_ammessi" ( type "int4", NotNull : true )
     * @param postiAmmessi
     */
    public void setPostiAmmessi(Integer postiAmmessi) {
        this.postiAmmessi = postiAmmessi;
    }

    /**
     * Get the "postiAmmessi" field value
     * This field is mapped on the database column "posti_ammessi" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Integer getPostiAmmessi() {
        return this.postiAmmessi;
    }

    /**
     * Set the "denominazione" field value
     * This field is mapped on the database column "denominazione" ( type "varchar", NotNull : true )
     * @param denominazione
     */
    public void setDenominazione(String denominazione) {
        this.denominazione = denominazione;
    }

    /**
     * Get the "denominazione" field value
     * This field is mapped on the database column "denominazione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDenominazione() {
        return this.denominazione;
    }

    /**
     * Set the "idAnnoScolastico" field value
     * This field is mapped on the database column "id_anno_scolastico" ( type "int4", NotNull : true )
     * @param idAnnoScolastico
     */
    public void setIdAnnoScolastico(Long idAnnoScolastico) {
        this.idAnnoScolastico = idAnnoScolastico;
    }

    /**
     * Get the "idAnnoScolastico" field value
     * This field is mapped on the database column "id_anno_scolastico" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdAnnoScolastico() {
        return this.idAnnoScolastico;
    }

    /**
     * Set the "idTipoFrequenza" field value
     * This field is mapped on the database column "id_tipo_frequenza" ( type "int4", NotNull : true )
     * @param idTipoFrequenza
     */
    public void setIdTipoFrequenza(Long idTipoFrequenza) {
        this.idTipoFrequenza = idTipoFrequenza;
    }

    /**
     * Get the "idTipoFrequenza" field value
     * This field is mapped on the database column "id_tipo_frequenza" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdTipoFrequenza() {
        return this.idTipoFrequenza;
    }

    /**
     * Set the "idEta" field value
     * This field is mapped on the database column "id_eta" ( type "int4", NotNull : true )
     * @param idEta
     */
    public void setIdEta(Long idEta) {
        this.idEta = idEta;
    }

    /**
     * Get the "idEta" field value
     * This field is mapped on the database column "id_eta" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdEta() {
        return this.idEta;
    }

    /**
     * Set the "flAmmissioneDis" field value
     * This field is mapped on the database column "fl_ammissione_dis" ( type "varchar", NotNull : false )
     * @param flAmmissioneDis
     */
    public void setFlAmmissioneDis(String flAmmissioneDis) {
        this.flAmmissioneDis = flAmmissioneDis;
    }

    /**
     * Get the "flAmmissioneDis" field value
     * This field is mapped on the database column "fl_ammissione_dis" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlAmmissioneDis() {
        return this.flAmmissioneDis;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idClasse);
        sb.append("|");
        sb.append(idScuola);
        sb.append("|");
        sb.append(postiLiberi);
        sb.append("|");
        sb.append(postiAmmessi);
        sb.append("|");
        sb.append(denominazione);
        sb.append("|");
        sb.append(idAnnoScolastico);
        sb.append("|");
        sb.append(idTipoFrequenza);
        sb.append("|");
        sb.append(idEta);
        sb.append("|");
        sb.append(flAmmissioneDis);
        return sb.toString(); 
    } 

}
