/*
 * Java bean class for entity "iscritto_r_punteggio_dom"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_r_punteggio_dom"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoRPunteggioDom implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_domanda_iscrizione, " +
		"  id_condizione_punteggio, " +
		"  id_utente, " +
		"  fl_valida, " +
		"  dt_inizio_validita, " +
		"  note, " +
		"  dt_fine_validita, " +
		"  ricorrenza, " +
		"  fl_integrazione " +
		"from iscritto_r_punteggio_dom ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_r_punteggio_dom (" +
		"  id_domanda_iscrizione, " +
		"  id_condizione_punteggio, " +
		"  id_utente, " +
		"  fl_valida, " +
		"  dt_inizio_validita, " +
		"  note, " +
		"  dt_fine_validita, " +
		"  ricorrenza, " +
		"  fl_integrazione " +
		") " +
		"values (" +
		"  :idDomandaIscrizione, " +
		"  :idCondizionePunteggio, " +
		"  :idUtente, " +
		"  :flValida, " +
		"  :dtInizioValidita, " +
		"  :note, " +
		"  :dtFineValidita, " +
		"  :ricorrenza, " +
		"  :flIntegrazione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_r_punteggio_dom where " +
		"  id_domanda_iscrizione = :idDomandaIscrizione and " +
		"  id_condizione_punteggio = :idCondizionePunteggio and " +
		"  dt_inizio_validita = :dtInizioValidita ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_r_punteggio_dom";

	//////////////////////////////////////////////////////////////////////


    private Long       idDomandaIscrizione ; // Id or Primary Key
    private Long       idCondizionePunteggio ; // Id or Primary Key
    private Date       dtInizioValidita ; // Id or Primary Key

    private Long       idUtente     ;
    private String     flValida     ;
    private String     note         ;
    private Date       dtFineValidita ;
    private Integer    ricorrenza   ;
    private String     flIntegrazione ;

    /**
     * Set the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @param idDomandaIscrizione
     */
	public void setIdDomandaIscrizione(Long idDomandaIscrizione) {
        this.idDomandaIscrizione = idDomandaIscrizione ;
    }

    /**
     * Get the "idDomandaIscrizione" field value
     * This field is mapped on the database column "id_domanda_iscrizione" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdDomandaIscrizione() {
        return this.idDomandaIscrizione;
    }
    /**
     * Set the "idCondizionePunteggio" field value
     * This field is mapped on the database column "id_condizione_punteggio" ( type "int4", NotNull : true )
     * @param idCondizionePunteggio
     */
	public void setIdCondizionePunteggio(Long idCondizionePunteggio) {
        this.idCondizionePunteggio = idCondizionePunteggio ;
    }

    /**
     * Get the "idCondizionePunteggio" field value
     * This field is mapped on the database column "id_condizione_punteggio" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdCondizionePunteggio() {
        return this.idCondizionePunteggio;
    }
    /**
     * Set the "dtInizioValidita" field value
     * This field is mapped on the database column "dt_inizio_validita" ( type "timestamp", NotNull : true )
     * @param dtInizioValidita
     */
	public void setDtInizioValidita(Date dtInizioValidita) {
        this.dtInizioValidita = dtInizioValidita ;
    }

    /**
     * Get the "dtInizioValidita" field value
     * This field is mapped on the database column "dt_inizio_validita" ( type "timestamp", NotNull : true )
     * @return the field value
     */
	public Date getDtInizioValidita() {
        return this.dtInizioValidita;
    }

    /**
     * Set the "idUtente" field value
     * This field is mapped on the database column "id_utente" ( type "int4", NotNull : false )
     * @param idUtente
     */
    public void setIdUtente(Long idUtente) {
        this.idUtente = idUtente;
    }

    /**
     * Get the "idUtente" field value
     * This field is mapped on the database column "id_utente" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdUtente() {
        return this.idUtente;
    }

    /**
     * Set the "flValida" field value
     * This field is mapped on the database column "fl_valida" ( type "varchar", NotNull : false )
     * @param flValida
     */
    public void setFlValida(String flValida) {
        this.flValida = flValida;
    }

    /**
     * Get the "flValida" field value
     * This field is mapped on the database column "fl_valida" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlValida() {
        return this.flValida;
    }

    /**
     * Set the "note" field value
     * This field is mapped on the database column "note" ( type "varchar", NotNull : false )
     * @param note
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * Get the "note" field value
     * This field is mapped on the database column "note" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getNote() {
        return this.note;
    }

    /**
     * Set the "dtFineValidita" field value
     * This field is mapped on the database column "dt_fine_validita" ( type "timestamp", NotNull : false )
     * @param dtFineValidita
     */
    public void setDtFineValidita(Date dtFineValidita) {
        this.dtFineValidita = dtFineValidita;
    }

    /**
     * Get the "dtFineValidita" field value
     * This field is mapped on the database column "dt_fine_validita" ( type "timestamp", NotNull : false )
     * @return the field value
     */
    public Date getDtFineValidita() {
        return this.dtFineValidita;
    }

    /**
     * Set the "ricorrenza" field value
     * This field is mapped on the database column "ricorrenza" ( type "int4", NotNull : false )
     * @param ricorrenza
     */
    public void setRicorrenza(Integer ricorrenza) {
        this.ricorrenza = ricorrenza;
    }

    /**
     * Get the "ricorrenza" field value
     * This field is mapped on the database column "ricorrenza" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Integer getRicorrenza() {
        return this.ricorrenza;
    }

    /**
     * Set the "flIntegrazione" field value
     * This field is mapped on the database column "fl_integrazione" ( type "varchar", NotNull : false )
     * @param flIntegrazione
     */
    public void setFlIntegrazione(String flIntegrazione) {
        this.flIntegrazione = flIntegrazione;
    }

    /**
     * Get the "flIntegrazione" field value
     * This field is mapped on the database column "fl_integrazione" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlIntegrazione() {
        return this.flIntegrazione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idDomandaIscrizione);
        sb.append("|");
        sb.append(idCondizionePunteggio);
        sb.append("|");
        sb.append(idUtente);
        sb.append("|");
        sb.append(flValida);
        sb.append("|");
        sb.append(dtInizioValidita);
        sb.append("|");
        sb.append(note);
        sb.append("|");
        sb.append(dtFineValidita);
        sb.append("|");
        sb.append(ricorrenza);
        sb.append("|");
        sb.append(flIntegrazione);
        return sb.toString(); 
    } 

}
