/*
 * Java bean class for entity "iscritto_t_studente"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_studente"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTStudente implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_condizione_occupazionale, " +
		"  denominazione_scuola, " +
		"  indirizzo, " +
		"  id_tipo_corso " +
		"from iscritto_t_studente ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_studente (" +
		"  id_condizione_occupazionale, " +
		"  denominazione_scuola, " +
		"  indirizzo, " +
		"  id_tipo_corso " +
		") " +
		"values (" +
		"  :idCondizioneOccupazionale, " +
		"  :denominazioneScuola, " +
		"  :indirizzo, " +
		"  :idTipoCorso " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_studente where " +
		"  id_condizione_occupazionale = :idCondizioneOccupazionale ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_studente";

	//////////////////////////////////////////////////////////////////////


    private Long       idCondizioneOccupazionale ; // Id or Primary Key

    private String     denominazioneScuola ;
    private String     indirizzo    ;
    private Long       idTipoCorso  ;

    /**
     * Set the "idCondizioneOccupazionale" field value
     * This field is mapped on the database column "id_condizione_occupazionale" ( type "int4", NotNull : true )
     * @param idCondizioneOccupazionale
     */
	public void setIdCondizioneOccupazionale(Long idCondizioneOccupazionale) {
        this.idCondizioneOccupazionale = idCondizioneOccupazionale ;
    }

    /**
     * Get the "idCondizioneOccupazionale" field value
     * This field is mapped on the database column "id_condizione_occupazionale" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdCondizioneOccupazionale() {
        return this.idCondizioneOccupazionale;
    }

    /**
     * Set the "denominazioneScuola" field value
     * This field is mapped on the database column "denominazione_scuola" ( type "varchar", NotNull : false )
     * @param denominazioneScuola
     */
    public void setDenominazioneScuola(String denominazioneScuola) {
        this.denominazioneScuola = denominazioneScuola;
    }

    /**
     * Get the "denominazioneScuola" field value
     * This field is mapped on the database column "denominazione_scuola" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getDenominazioneScuola() {
        return this.denominazioneScuola;
    }

    /**
     * Set the "indirizzo" field value
     * This field is mapped on the database column "indirizzo" ( type "varchar", NotNull : true )
     * @param indirizzo
     */
    public void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }

    /**
     * Get the "indirizzo" field value
     * This field is mapped on the database column "indirizzo" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getIndirizzo() {
        return this.indirizzo;
    }

    /**
     * Set the "idTipoCorso" field value
     * This field is mapped on the database column "id_tipo_corso" ( type "int4", NotNull : false )
     * @param idTipoCorso
     */
    public void setIdTipoCorso(Long idTipoCorso) {
        this.idTipoCorso = idTipoCorso;
    }

    /**
     * Get the "idTipoCorso" field value
     * This field is mapped on the database column "id_tipo_corso" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdTipoCorso() {
        return this.idTipoCorso;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idCondizioneOccupazionale);
        sb.append("|");
        sb.append(denominazioneScuola);
        sb.append("|");
        sb.append(indirizzo);
        sb.append("|");
        sb.append(idTipoCorso);
        return sb.toString(); 
    } 

}
