/*
 * Java bean class for entity "iscritto_t_lista_attesa"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_t_lista_attesa"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTListaAttesa implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  codice_fiscale, " +
		"  cognome, " +
		"  nome, " +
		"  fl_anno1, " +
		"  fl_anno2 " +
		"from iscritto_t_lista_attesa ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_lista_attesa (" +
		"  codice_fiscale, " +
		"  cognome, " +
		"  nome, " +
		"  fl_anno1, " +
		"  fl_anno2 " +
		") " +
		"values (" +
		"  :codiceFiscale, " +
		"  :cognome, " +
		"  :nome, " +
		"  :flAnno1, " +
		"  :flAnno2 " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_lista_attesa where " +
		"  codice_fiscale = :codiceFiscale ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_lista_attesa";

	//////////////////////////////////////////////////////////////////////


    private String     codiceFiscale ; // Id or Primary Key

    private String     cognome      ;
    private String     nome         ;
    private String     flAnno1      ;
    private String     flAnno2      ;

    /**
     * Set the "codiceFiscale" field value
     * This field is mapped on the database column "codice_fiscale" ( type "varchar", NotNull : true )
     * @param codiceFiscale
     */
	public void setCodiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale ;
    }

    /**
     * Get the "codiceFiscale" field value
     * This field is mapped on the database column "codice_fiscale" ( type "varchar", NotNull : true )
     * @return the field value
     */
	public String getCodiceFiscale() {
        return this.codiceFiscale;
    }

    /**
     * Set the "cognome" field value
     * This field is mapped on the database column "cognome" ( type "varchar", NotNull : true )
     * @param cognome
     */
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    /**
     * Get the "cognome" field value
     * This field is mapped on the database column "cognome" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCognome() {
        return this.cognome;
    }

    /**
     * Set the "nome" field value
     * This field is mapped on the database column "nome" ( type "varchar", NotNull : false )
     * @param nome
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * Get the "nome" field value
     * This field is mapped on the database column "nome" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getNome() {
        return this.nome;
    }

    /**
     * Set the "flAnno1" field value
     * This field is mapped on the database column "fl_anno1" ( type "varchar", NotNull : true )
     * @param flAnno1
     */
    public void setFlAnno1(String flAnno1) {
        this.flAnno1 = flAnno1;
    }

    /**
     * Get the "flAnno1" field value
     * This field is mapped on the database column "fl_anno1" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlAnno1() {
        return this.flAnno1;
    }

    /**
     * Set the "flAnno2" field value
     * This field is mapped on the database column "fl_anno2" ( type "varchar", NotNull : true )
     * @param flAnno2
     */
    public void setFlAnno2(String flAnno2) {
        this.flAnno2 = flAnno2;
    }

    /**
     * Get the "flAnno2" field value
     * This field is mapped on the database column "fl_anno2" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getFlAnno2() {
        return this.flAnno2;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(codiceFiscale);
        sb.append("|");
        sb.append(cognome);
        sb.append("|");
        sb.append(nome);
        sb.append("|");
        sb.append(flAnno1);
        sb.append("|");
        sb.append(flAnno2);
        return sb.toString(); 
    } 

}
