/*
 * Java bean class for entity "iscritto_d_profilo"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_profilo"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDProfilo implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_profilo, " +
		"  codice_profilo, " +
		"  descrizione " +
		"from iscritto_d_profilo ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_profilo (" +
		"  id_profilo, " +
		"  codice_profilo, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idProfilo, " +
		"  :codiceProfilo, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_profilo where " +
		"  id_profilo = :idProfilo ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_profilo";

	//////////////////////////////////////////////////////////////////////


    private Long       idProfilo    ; // Id or Primary Key

    private String     codiceProfilo ;
    private String     descrizione  ;

    /**
     * Set the "idProfilo" field value
     * This field is mapped on the database column "id_profilo" ( type "int4", NotNull : true )
     * @param idProfilo
     */
	public void setIdProfilo(Long idProfilo) {
        this.idProfilo = idProfilo ;
    }

    /**
     * Get the "idProfilo" field value
     * This field is mapped on the database column "id_profilo" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdProfilo() {
        return this.idProfilo;
    }

    /**
     * Set the "codiceProfilo" field value
     * This field is mapped on the database column "codice_profilo" ( type "varchar", NotNull : true )
     * @param codiceProfilo
     */
    public void setCodiceProfilo(String codiceProfilo) {
        this.codiceProfilo = codiceProfilo;
    }

    /**
     * Get the "codiceProfilo" field value
     * This field is mapped on the database column "codice_profilo" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodiceProfilo() {
        return this.codiceProfilo;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idProfilo);
        sb.append("|");
        sb.append(codiceProfilo);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
