/*
 * Java bean class for entity "iscritto_d_condizione_pun"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_condizione_pun"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDCondizionePun implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  cod_condizione, " +
		"  descrizione, " +
		"  id_condizione_punteggio, " +
		"  fl_istruttoria, " +
		"  id_tipo_istruttoria, " +
		"  id_tipo_allegato " +
		"from iscritto_d_condizione_pun ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_condizione_pun (" +
		"  cod_condizione, " +
		"  descrizione, " +
		"  id_condizione_punteggio, " +
		"  fl_istruttoria, " +
		"  id_tipo_istruttoria, " +
		"  id_tipo_allegato " +
		") " +
		"values (" +
		"  :codCondizione, " +
		"  :descrizione, " +
		"  :idCondizionePunteggio, " +
		"  :flIstruttoria, " +
		"  :idTipoIstruttoria, " +
		"  :idTipoAllegato " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_condizione_pun where " +
		"  id_condizione_punteggio = :idCondizionePunteggio ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_condizione_pun";

	//////////////////////////////////////////////////////////////////////


    private Long       idCondizionePunteggio ; // Id or Primary Key

    private String     codCondizione ;
    private String     descrizione  ;
    private String     flIstruttoria ;
    private Long       idTipoIstruttoria ;
    private Long       idTipoAllegato ;

    /**
     * Set the "idCondizionePunteggio" field value
     * This field is mapped on the database column "id_condizione_punteggio" ( type "int4", NotNull : true )
     * @param idCondizionePunteggio
     */
	public void setIdCondizionePunteggio(Long idCondizionePunteggio) {
        this.idCondizionePunteggio = idCondizionePunteggio ;
    }

    /**
     * Get the "idCondizionePunteggio" field value
     * This field is mapped on the database column "id_condizione_punteggio" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdCondizionePunteggio() {
        return this.idCondizionePunteggio;
    }

    /**
     * Set the "codCondizione" field value
     * This field is mapped on the database column "cod_condizione" ( type "varchar", NotNull : true )
     * @param codCondizione
     */
    public void setCodCondizione(String codCondizione) {
        this.codCondizione = codCondizione;
    }

    /**
     * Get the "codCondizione" field value
     * This field is mapped on the database column "cod_condizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodCondizione() {
        return this.codCondizione;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }

    /**
     * Set the "flIstruttoria" field value
     * This field is mapped on the database column "fl_istruttoria" ( type "varchar", NotNull : false )
     * @param flIstruttoria
     */
    public void setFlIstruttoria(String flIstruttoria) {
        this.flIstruttoria = flIstruttoria;
    }

    /**
     * Get the "flIstruttoria" field value
     * This field is mapped on the database column "fl_istruttoria" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getFlIstruttoria() {
        return this.flIstruttoria;
    }

    /**
     * Set the "idTipoIstruttoria" field value
     * This field is mapped on the database column "id_tipo_istruttoria" ( type "int4", NotNull : false )
     * @param idTipoIstruttoria
     */
    public void setIdTipoIstruttoria(Long idTipoIstruttoria) {
        this.idTipoIstruttoria = idTipoIstruttoria;
    }

    /**
     * Get the "idTipoIstruttoria" field value
     * This field is mapped on the database column "id_tipo_istruttoria" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdTipoIstruttoria() {
        return this.idTipoIstruttoria;
    }

    /**
     * Set the "idTipoAllegato" field value
     * This field is mapped on the database column "id_tipo_allegato" ( type "int4", NotNull : false )
     * @param idTipoAllegato
     */
    public void setIdTipoAllegato(Long idTipoAllegato) {
        this.idTipoAllegato = idTipoAllegato;
    }

    /**
     * Get the "idTipoAllegato" field value
     * This field is mapped on the database column "id_tipo_allegato" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdTipoAllegato() {
        return this.idTipoAllegato;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(codCondizione);
        sb.append("|");
        sb.append(descrizione);
        sb.append("|");
        sb.append(idCondizionePunteggio);
        sb.append("|");
        sb.append(flIstruttoria);
        sb.append("|");
        sb.append(idTipoIstruttoria);
        sb.append("|");
        sb.append(idTipoAllegato);
        return sb.toString(); 
    } 

}
