/*
 * Java bean class for entity "iscritto_t_versione_gra"
 * Created on 2019-03-06 ( Date ISO 2019-03-06 - Time 14:38:29 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_versione_gra"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTVersioneGra implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  versione, " +
		"  dt_versione_gra, " +
		"  id_versione_gra, " +
		"  note, " +
		"  id_stato_gra, " +
		"  id_step_gra " +
		"from iscritto_t_versione_gra ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_versione_gra (" +
		"  versione, " +
		"  dt_versione_gra, " +
		"  id_versione_gra, " +
		"  note, " +
		"  id_stato_gra, " +
		"  id_step_gra " +
		") " +
		"values (" +
		"  :versione, " +
		"  :dtVersioneGra, " +
		"  :idVersioneGra, " +
		"  :note, " +
		"  :idStatoGra, " +
		"  :idStepGra " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_versione_gra where " +
		"  id_versione_gra = :idVersioneGra ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_versione_gra";

	//////////////////////////////////////////////////////////////////////


    private Long       idVersioneGra ; // Id or Primary Key

    private Integer    versione     ;
    private Date       dtVersioneGra ;
    private String     note         ;
    private Long       idStatoGra   ;
    private Long       idStepGra    ;

    /**
     * Set the "idVersioneGra" field value
     * This field is mapped on the database column "id_versione_gra" ( type "int4", NotNull : true )
     * @param idVersioneGra
     */
	public void setIdVersioneGra(Long idVersioneGra) {
        this.idVersioneGra = idVersioneGra ;
    }

    /**
     * Get the "idVersioneGra" field value
     * This field is mapped on the database column "id_versione_gra" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdVersioneGra() {
        return this.idVersioneGra;
    }

    /**
     * Set the "versione" field value
     * This field is mapped on the database column "versione" ( type "int4", NotNull : true )
     * @param versione
     */
    public void setVersione(Integer versione) {
        this.versione = versione;
    }

    /**
     * Get the "versione" field value
     * This field is mapped on the database column "versione" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Integer getVersione() {
        return this.versione;
    }

    /**
     * Set the "dtVersioneGra" field value
     * This field is mapped on the database column "dt_versione_gra" ( type "timestamp", NotNull : true )
     * @param dtVersioneGra
     */
    public void setDtVersioneGra(Date dtVersioneGra) {
        this.dtVersioneGra = dtVersioneGra;
    }

    /**
     * Get the "dtVersioneGra" field value
     * This field is mapped on the database column "dt_versione_gra" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDtVersioneGra() {
        return this.dtVersioneGra;
    }

    /**
     * Set the "note" field value
     * This field is mapped on the database column "note" ( type "varchar", NotNull : false )
     * @param note
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * Get the "note" field value
     * This field is mapped on the database column "note" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getNote() {
        return this.note;
    }

    /**
     * Set the "idStatoGra" field value
     * This field is mapped on the database column "id_stato_gra" ( type "int4", NotNull : true )
     * @param idStatoGra
     */
    public void setIdStatoGra(Long idStatoGra) {
        this.idStatoGra = idStatoGra;
    }

    /**
     * Get the "idStatoGra" field value
     * This field is mapped on the database column "id_stato_gra" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdStatoGra() {
        return this.idStatoGra;
    }

    /**
     * Set the "idStepGra" field value
     * This field is mapped on the database column "id_step_gra" ( type "int4", NotNull : true )
     * @param idStepGra
     */
    public void setIdStepGra(Long idStepGra) {
        this.idStepGra = idStepGra;
    }

    /**
     * Get the "idStepGra" field value
     * This field is mapped on the database column "id_step_gra" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdStepGra() {
        return this.idStepGra;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(versione);
        sb.append("|");
        sb.append(dtVersioneGra);
        sb.append("|");
        sb.append(idVersioneGra);
        sb.append("|");
        sb.append(note);
        sb.append("|");
        sb.append(idStatoGra);
        sb.append("|");
        sb.append(idStepGra);
        return sb.toString(); 
    } 

}
