/*
 * Java bean class for entity "iscritto_d_stato_scu"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:20 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_stato_scu"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDStatoScu implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_stato_scu, " +
		"  cod_stato_scu, " +
		"  descrizione " +
		"from iscritto_d_stato_scu ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_stato_scu (" +
		"  id_stato_scu, " +
		"  cod_stato_scu, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idStatoScu, " +
		"  :codStatoScu, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_stato_scu where " +
		"  id_stato_scu = :idStatoScu ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_stato_scu";

	//////////////////////////////////////////////////////////////////////


    private Long       idStatoScu   ; // Id or Primary Key

    private String     codStatoScu  ;
    private String     descrizione  ;

    /**
     * Set the "idStatoScu" field value
     * This field is mapped on the database column "id_stato_scu" ( type "int4", NotNull : true )
     * @param idStatoScu
     */
	public void setIdStatoScu(Long idStatoScu) {
        this.idStatoScu = idStatoScu ;
    }

    /**
     * Get the "idStatoScu" field value
     * This field is mapped on the database column "id_stato_scu" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdStatoScu() {
        return this.idStatoScu;
    }

    /**
     * Set the "codStatoScu" field value
     * This field is mapped on the database column "cod_stato_scu" ( type "varchar", NotNull : true )
     * @param codStatoScu
     */
    public void setCodStatoScu(String codStatoScu) {
        this.codStatoScu = codStatoScu;
    }

    /**
     * Get the "codStatoScu" field value
     * This field is mapped on the database column "cod_stato_scu" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodStatoScu() {
        return this.codStatoScu;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idStatoScu);
        sb.append("|");
        sb.append(codStatoScu);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
