/*
 * Java bean class for entity "iscritto_d_tipo_sog"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_tipo_sog"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDTipoSog implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_tipo_soggetto, " +
		"  cod_tipo_soggetto, " +
		"  descrizione " +
		"from iscritto_d_tipo_sog ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_tipo_sog (" +
		"  id_tipo_soggetto, " +
		"  cod_tipo_soggetto, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idTipoSoggetto, " +
		"  :codTipoSoggetto, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_tipo_sog where " +
		"  id_tipo_soggetto = :idTipoSoggetto ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_tipo_sog";

	//////////////////////////////////////////////////////////////////////


    private Long       idTipoSoggetto ; // Id or Primary Key

    private String     codTipoSoggetto ;
    private String     descrizione  ;

    /**
     * Set the "idTipoSoggetto" field value
     * This field is mapped on the database column "id_tipo_soggetto" ( type "int4", NotNull : true )
     * @param idTipoSoggetto
     */
	public void setIdTipoSoggetto(Long idTipoSoggetto) {
        this.idTipoSoggetto = idTipoSoggetto ;
    }

    /**
     * Get the "idTipoSoggetto" field value
     * This field is mapped on the database column "id_tipo_soggetto" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdTipoSoggetto() {
        return this.idTipoSoggetto;
    }

    /**
     * Set the "codTipoSoggetto" field value
     * This field is mapped on the database column "cod_tipo_soggetto" ( type "varchar", NotNull : false )
     * @param codTipoSoggetto
     */
    public void setCodTipoSoggetto(String codTipoSoggetto) {
        this.codTipoSoggetto = codTipoSoggetto;
    }

    /**
     * Get the "codTipoSoggetto" field value
     * This field is mapped on the database column "cod_tipo_soggetto" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getCodTipoSoggetto() {
        return this.codTipoSoggetto;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : false )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTipoSoggetto);
        sb.append("|");
        sb.append(codTipoSoggetto);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
