/*
 * Java bean class for entity "iscritto_d_tipo_ist"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;


/**
 * Java bean for entity "iscritto_d_tipo_ist"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoDTipoIst implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_tipo_istruttoria, " +
		"  cod_tipo_istruttoria, " +
		"  descrizione " +
		"from iscritto_d_tipo_ist ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_d_tipo_ist (" +
		"  id_tipo_istruttoria, " +
		"  cod_tipo_istruttoria, " +
		"  descrizione " +
		") " +
		"values (" +
		"  :idTipoIstruttoria, " +
		"  :codTipoIstruttoria, " +
		"  :descrizione " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_d_tipo_ist where " +
		"  id_tipo_istruttoria = :idTipoIstruttoria ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_d_tipo_ist";

	//////////////////////////////////////////////////////////////////////


    private Long       idTipoIstruttoria ; // Id or Primary Key

    private String     codTipoIstruttoria ;
    private String     descrizione  ;

    /**
     * Set the "idTipoIstruttoria" field value
     * This field is mapped on the database column "id_tipo_istruttoria" ( type "int4", NotNull : true )
     * @param idTipoIstruttoria
     */
	public void setIdTipoIstruttoria(Long idTipoIstruttoria) {
        this.idTipoIstruttoria = idTipoIstruttoria ;
    }

    /**
     * Get the "idTipoIstruttoria" field value
     * This field is mapped on the database column "id_tipo_istruttoria" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdTipoIstruttoria() {
        return this.idTipoIstruttoria;
    }

    /**
     * Set the "codTipoIstruttoria" field value
     * This field is mapped on the database column "cod_tipo_istruttoria" ( type "varchar", NotNull : true )
     * @param codTipoIstruttoria
     */
    public void setCodTipoIstruttoria(String codTipoIstruttoria) {
        this.codTipoIstruttoria = codTipoIstruttoria;
    }

    /**
     * Get the "codTipoIstruttoria" field value
     * This field is mapped on the database column "cod_tipo_istruttoria" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getCodTipoIstruttoria() {
        return this.codTipoIstruttoria;
    }

    /**
     * Set the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @param descrizione
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Get the "descrizione" field value
     * This field is mapped on the database column "descrizione" ( type "varchar", NotNull : true )
     * @return the field value
     */
    public String getDescrizione() {
        return this.descrizione;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTipoIstruttoria);
        sb.append("|");
        sb.append(codTipoIstruttoria);
        sb.append("|");
        sb.append(descrizione);
        return sb.toString(); 
    } 

}
