/*
 * Java bean class for entity "iscritto_t_eta"
 * Created on 2019-04-01 ( Date ISO 2019-04-01 - Time 09:21:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.csi.iscritto.serviscritto.business.integration.dao.table.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "iscritto_t_eta"
 *
 * @author Telosys Tools Generator
 *
 */
public class IscrittoTEta implements Serializable {
    private static final long serialVersionUID = 1L;

	public static final String SQL_SELECT_ALL =
		"select " +
		"  id_eta, " +
		"  data_da, " +
		"  data_a, " +
		"  id_anagrafica_gra, " +
		"  id_fascia_eta " +
		"from iscritto_t_eta ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_INSERT =
		"insert into iscritto_t_eta (" +
		"  id_eta, " +
		"  data_da, " +
		"  data_a, " +
		"  id_anagrafica_gra, " +
		"  id_fascia_eta " +
		") " +
		"values (" +
		"  :idEta, " +
		"  :dataDa, " +
		"  :dataA, " +
		"  :idAnagraficaGra, " +
		"  :idFasciaEta " +
		")";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_DELETE =
		"delete from iscritto_t_eta where " +
		"  id_eta = :idEta ";

	//////////////////////////////////////////////////////////////////////

	public static final String SQL_COUNT_ALL =
		"select count(*) from iscritto_t_eta";

	//////////////////////////////////////////////////////////////////////


    private Long       idEta        ; // Id or Primary Key

    private Date       dataDa       ;
    private Date       dataA        ;
    private Long       idAnagraficaGra ;
    private Long       idFasciaEta  ;

    /**
     * Set the "idEta" field value
     * This field is mapped on the database column "id_eta" ( type "int4", NotNull : true )
     * @param idEta
     */
	public void setIdEta(Long idEta) {
        this.idEta = idEta ;
    }

    /**
     * Get the "idEta" field value
     * This field is mapped on the database column "id_eta" ( type "int4", NotNull : true )
     * @return the field value
     */
	public Long getIdEta() {
        return this.idEta;
    }

    /**
     * Set the "dataDa" field value
     * This field is mapped on the database column "data_da" ( type "timestamp", NotNull : true )
     * @param dataDa
     */
    public void setDataDa(Date dataDa) {
        this.dataDa = dataDa;
    }

    /**
     * Get the "dataDa" field value
     * This field is mapped on the database column "data_da" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDataDa() {
        return this.dataDa;
    }

    /**
     * Set the "dataA" field value
     * This field is mapped on the database column "data_a" ( type "timestamp", NotNull : true )
     * @param dataA
     */
    public void setDataA(Date dataA) {
        this.dataA = dataA;
    }

    /**
     * Get the "dataA" field value
     * This field is mapped on the database column "data_a" ( type "timestamp", NotNull : true )
     * @return the field value
     */
    public Date getDataA() {
        return this.dataA;
    }

    /**
     * Set the "idAnagraficaGra" field value
     * This field is mapped on the database column "id_anagrafica_gra" ( type "int4", NotNull : true )
     * @param idAnagraficaGra
     */
    public void setIdAnagraficaGra(Long idAnagraficaGra) {
        this.idAnagraficaGra = idAnagraficaGra;
    }

    /**
     * Get the "idAnagraficaGra" field value
     * This field is mapped on the database column "id_anagrafica_gra" ( type "int4", NotNull : true )
     * @return the field value
     */
    public Long getIdAnagraficaGra() {
        return this.idAnagraficaGra;
    }

    /**
     * Set the "idFasciaEta" field value
     * This field is mapped on the database column "id_fascia_eta" ( type "int4", NotNull : false )
     * @param idFasciaEta
     */
    public void setIdFasciaEta(Long idFasciaEta) {
        this.idFasciaEta = idFasciaEta;
    }

    /**
     * Get the "idFasciaEta" field value
     * This field is mapped on the database column "id_fascia_eta" ( type "int4", NotNull : false )
     * @return the field value
     */
    public Long getIdFasciaEta() {
        return this.idFasciaEta;
    }


    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idEta);
        sb.append("|");
        sb.append(dataDa);
        sb.append("|");
        sb.append(dataA);
        sb.append("|");
        sb.append(idAnagraficaGra);
        sb.append("|");
        sb.append(idFasciaEta);
        return sb.toString(); 
    } 

}
